### ISSUE TITLE
Abbruch aktuelle Aktion mit "Escape"

### ISSUE THREAD

**Issue by M-Reimer** [hneemann/Digital#1]
Ich hoffe Issues in Deutsch sind OK. Andernfalls schreibe ich in Zukunft in Englisch.

Bei meiner ersten Verwendung von "Digital" habe ich intuitiv versucht begonnene Aktionen, wie das Zeichnen von Linien, via "Esc" abzubrechen, was leider nicht möglich ist. Mein Vorschlag wäre, die Taste dafür nutzbar zu machen.

**Comment by hneemann** [comment]
Fixed.
