### ISSUE TITLE
Checkbox visible in Background Color section of the Edit Circuit Attributes window

### ISSUE THREAD

**Issue by guiweber** [hneemann/Digital#10]
In the Edit Circuit Attributes window, one of the two checkboxes (DIL package, Modification Locked) appears in the Background Color section. The checkbox appears only after moving the mouse over the Background Color section. The checkbox that appears is the last one over which the mouse moved over.

![image](https://cloud.githubusercontent.com/assets/7825368/26501286/2c374b42-4207-11e7-9c72-197651bda360.png)

**Comment by hneemann** [comment]
Not reproducible on my machines. But i think it is a problem with the use of transparent colors.
Now I fill the button first with non transparent white and afterwards the with desired color.
Hope that helps. v0.12

**Comment by guiweber** [comment]
@hneemann Since this was not reproducible on your machine, I just want ton confirm that the issue is fixed in the new build you provided. Cheers!
