### ISSUE TITLE
Probe in counter-mode displays too many digits 

### ISSUE THREAD

**Issue by mengstr** [hneemann/Digital#1004]
If I set the display mode to Octal or Binary (not sure why anyone actually would to that for a counter-probe) I get a lot of digits :-)
<img width="1547" alt="Screenshot 2022-07-28 at 00 42 16" src="https://user-images.githubusercontent.com/325326/181385437-96306ab4-5618-4417-b495-45f54a4d002a.png">

**Comment by hneemann** [comment]
The OCTAL, HEX and BIN formats display all bits, even those that are zero.
And the counter value is a 64-bit value, so 64 bits are displayed. I'm not sure if it's worth the effort to change this specifically for the probe in the counter mode.
