### ISSUE TITLE
Find easily names of tunnels and in/outputs in a complex circuit (Ctrl-F function ?)

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#1010]
### Discussed in https://github.com/hneemann/Digital/discussions/999

<div type='discussions-op-text'>

<sup>Originally posted by **jongena** July 27, 2022</sup>
My question is perhaps not clear, thus I reformulate it slightly: I have developed several large circuits. Is there a possibility to do a search in a complex circuit with many in- and outputs for various names of tunnels or in/outputs ? (e.g. using ctrl-f, as in a text editor ?) This would be very useful to my opinion. </div>

**Comment by mengstr** [comment]
This is a nice addition to Digital. But the markers are very very subtle.

<img width="1782" alt="Screenshot 2022-08-01 at 08 49 34" src="https://user-images.githubusercontent.com/325326/182089381-9fafed40-0c4d-4975-b6ea-64d436644a9c.png">
