### ISSUE TITLE
Display label inside of Button

### ISSUE THREAD

**Issue by odog8** [hneemann/Digital#1021]
Currently, the label for a button is displayed outside of it, opposite of the direction it is facing:

![image](https://user-images.githubusercontent.com/36713157/185724741-e44bc58e-1ce6-4062-88b7-a12336350d46.png)

Which can be bothersome when having multiple buttons close together. I feel like it would be a lot better looking if the button label was displayed inside of it.

**Comment by hneemann** [comment]
Hmm! 
That's not a bad idea, but I would only enable that if the button is mapped to a key on the keyboard.
