### ISSUE TITLE
the order of inputs and outputs get messed up when I save as a chip/embedded circuit

### ISSUE THREAD

**Issue by metoshinakamoto** [hneemann/Digital#1022]
attached is the picture of the chip along with the inside of it, notice how the order is completely different

![image](https://user-images.githubusercontent.com/98441823/188664691-dcd3c37d-f53f-4b0e-819b-706f35fed53d.png)
![image](https://user-images.githubusercontent.com/98441823/188664818-2a5b0cc6-984b-422f-b5cd-9e1d05f75327.png)

**Comment by hneemann** [comment]
Use "Edit->Order Inputs" and "Edit->Order Outputs" to order the inputs and outputs accordingly.

**Comment by xotmatrix** [comment]
That's probably the best option but you could also use:
* From the parent circuit: "Right-click Adder -> Shape: Layout"
* From the embedded circuit: "Edit -> Circuit specific settings -> Advanced -> Shape: Layout"

**Comment by metoshinakamoto** [comment]
👍
