### ISSUE TITLE
request: Add registers with increment option

### ISSUE THREAD

**Issue by Hamid1382** [hneemann/Digital#1048]
Hi thanks for powerful app but a small problem i have encountered is that there is no register with INC input that increments data stored by one , in computer architecture they are very useful. until then i have to implement inc by myself. tnx again

**Comment by hneemann** [comment]
But it is not a big deal to build such a component as a sub circuit.
It is hardly worth to add something like this as a built-in component.

**Comment by TheWildJarvi** [comment]
Use the built in up down counter and set it up to increment or load a value.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Hamid1382 ***@***.***>
Sent: Saturday, October 29, 2022 1:40:08 PM
To: hneemann/Digital ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hneemann/Digital] request: Add registers with increment option (Issue #1048)


Hi thanks for powerful app but a small problem i have encountered is that there is no register with INC input that increments data stored by one , in computer architecture they are very useful. until then i have to implement inc by myself. tnx again

**Comment by hneemann** [comment]
@TheWildJarvi 
That's right! I didn't think of that at all! :smile: 
The built in up down counter is essentially a register with inc and dec input.

**Comment by Hamid1382** [comment]
> But it is not a big deal to build such a component as a sub circuit. It is hardly worth to add something like this as a built-in component.

I have to use up to 128 registers and i haven't seen any button like create Integrated circuit

**Comment by hneemann** [comment]
Copy the attached file to your circuit folder and import the register with _Components->Custom->incReg_.
Then set the Bits value accordingly.

[incReg.dig.zip](https://github.com/hneemann/Digital/files/9943867/incReg.dig.zip)
