### ISSUE TITLE
Disable components from simulation

### ISSUE THREAD

**Issue by minecon1776** [hneemann/Digital#1051]
I want a way for components that are not being used to be disabled by the user because when I'm doing some testing, I want to be able to throw a piece of a circuit off to the side without a bunch of errors that the circuit isn't connected. It would be easy if I could just disable the components in question so they aren't used, but can be used later. It would be useful to make such components greyed out or something so that there is visual distinction that they are disabled. (This should be marked as enhancement, but I am kinda new to writing these so I don't know where the option is)

**Comment by hneemann** [comment]
I don't think that's a good idea. You can also just delete the components and add them back later. If a component is removed/deactivated, the corresponding output is also unconnected, which would also lead to errors.
