### ISSUE TITLE
[SIMULATION] Error when using output feedback as input for custom counter

### ISSUE THREAD

**Issue by PlaygroundGITTraining** [hneemann/Digital#1072]
Hi, I am trying to implement a counter from scratch using just NAND gates as basic building blocks. Starting with that idea I have decided that I will need to implement a DFlipFlop using just NAND gates, and worked out as expected **starting simulation**:
![image](https://user-images.githubusercontent.com/35568111/206477387-be4fbea5-d04e-40f8-9540-5ee6b5115500.png)
Unfortunately if I try to do Analysis:
![image](https://user-images.githubusercontent.com/35568111/206477704-65cec5a8-4cc2-44c0-80b5-e00df60f14f3.png)
That I would say it is normal as Analysis will return infinite propagation cycles for the last 2 gates without a concrete result (I tried to simulate also same behaviour in PROTEUS ISIS ASPICE same gate setup and can say a result without being an error) I know that PROTEUS ASPICE is complex and use virtualized MOSFET transistors with some parametrizable specifications like delays, temp coefficients, switching times and so on, see: https://techweb.rohm.com/knowledge/simulation/s-simulation/01-s-simulation/8331 to implement logic gates. After that I started to dig and search if such kind of issues were reported already and they are a lot of them, one of course was solved using propagation delays with somehow NOT gates.
But I was happy because the simulation worked and I didn't care too much about analysis anymore and continued further naming this circuit as DFlipFlop and saving it.
Starting with the implementation of the 2-bit counter using this custom DFlipFlop sub-circuit like in the picture below there is now a error in simulation because circuit oscillates.
![image](https://user-images.githubusercontent.com/35568111/206476244-d035015c-e139-4e04-8824-9602b1e7240e.png)
Simulating a single entity is fine by the way:
![image](https://user-images.githubusercontent.com/35568111/206480435-d520510d-20a8-4125-b5dd-f8f9ad04fa75.png)
Why now DFlipFlop input feedbacks have a problem causing oscillation if the single DFlipFlop already can start simulation correctly independently?
Remember that this feedback loop is working in sub-circuit simulation (hapens in the NAND implementation).
I really appreciate if there is a alternative to this using any kind of hacks with NAND delays or something. Thank you!

**Comment by PlaygroundGITTraining** [comment]
Single steep is working:
![image](https://user-images.githubusercontent.com/35568111/206485638-8cd7b9e9-c129-40a0-a4c0-64bf1682b972.png)
![image](https://user-images.githubusercontent.com/35568111/206485755-3e8f88b5-5f60-4ea3-96e8-e9228fe70a2a.png)

**Comment by hneemann** [comment]
This is not a problem of the simulation. It would not work with real gates either.
The flip-flop shown above, built from NAND gates, is not edge-triggered. That means it is transparent when the clock is high. In this case this leads to an oscillation when essentially an inverter is created which is fed back to itself.
For such a counter, one must use edge-triggered or master-slave flop-flops.

**Comment by PlaygroundGITTraining** [comment]
I created master slave jk but does not work at all simulation with feedbacks, I really don't have any clue.
**Step 1 (3 input nand gate)**
![image](https://user-images.githubusercontent.com/35568111/206726494-be3d47e6-4d85-40d8-adcd-79551e72df54.png)
**Step 2 (JK Flip Flop)**
![image](https://user-images.githubusercontent.com/35568111/206726765-04eddedd-fd60-4948-926c-75e756921643.png)
**Step 3 (Master Slave JK Flip Flop)**
![image](https://user-images.githubusercontent.com/35568111/206727062-8d13b2d4-68dc-4953-8404-52793fbce2c7.png)

**In the step 3 all inputs are logic low.**

**Observations:**
1. I understand that SR Latches, in non master slave configuration toggle for the whole high signal width until it goes to a stable low state, this means circuit enters in a racing condition (undefined state) and high/low clock pulse should be reduced to fit in the gate propagation times, actually needs to be a short like a pulse I think in MHZ frequency range to avoid this.
2. Normally Master Slave Flip Flops should overcome this in theory and just toggle on signal transition once, does not matter the low/high signals width.

Now I am not able to create Master JK FlipFlop at all by following a couple of designs.

Is there any solution to simulate this kind of circuit using basic nand gates or not?

I really hate now oscillators and the third state (high impedance) or so called Z-state.

**Comment by PlaygroundGITTraining** [comment]
I have also expanded and added all inputs with enabled 3 state:
![image](https://user-images.githubusercontent.com/35568111/206732522-10631906-fe66-4a66-a5d7-5d139c11ad82.png)
It leads to the same behaviour.

**Comment by hneemann** [comment]
The example folder contains some example flipflops. The file _D-T2.dig_ contains an edge triggered variant, which is built with Nand gates only.

Isn't it great that you can build short circuits in the simulator without them causing any damage at all? With real components you probably had one destroyed every time. :smile:
