### ISSUE TITLE
Truth Table of IOs with "Data bits" greater 1

### ISSUE THREAD

**Issue by roy77** [hneemann/Digital#108]
The truth table of IOs with "Data bits" greater 1 start with LSB, but it make more sense to start with MSB. 

If a data bus is used, it would be a good idea that Create Circuit ...  generate a data bus, too.

**Comment by hneemann** [comment]
> The truth table of IOs with "Data bits" greater 1 start with LSB, but it make more sense to start with MSB.

I will think about it

> If a data bus is used, it would be a good idea that Create Circuit ... generate a data bus, too.

This is a nice idea, but difficult to implement.
The model analyzer is unable to analyze models with multi-bit inputs or outputs. To enable such inputs and outputs, the model is modified and the inputs and outputs are converted to a new model by replacing such inputs and outputs with splitters and many single-bit inputs or outputs.
To implement this, you must log these changes, pass the log all the way to the circuit builder, and then again insert splitters.
A lot of work for little benefit.
