### ISSUE TITLE
74161 strange behaviour

### ISSUE THREAD

**Issue by gnaghi** [hneemann/Digital#1082]
I'm playing with the 74161 component to create a counter to 8.
I use QD to enable the CLR input, and reset the counter. 

But even if the counter is indeed reset, I don't see the CLR signal coming from QD, to /CLR.
![74161 error](https://user-images.githubusercontent.com/11958151/209552165-592d0c64-5fc7-49d2-8174-bc77c6ce1e9a.png)

**Comment by hneemann** [comment]
The 74161 has an asynchronous clear, i.e. as soon as the QD pin rises, it is reset to zero. Compared to the time scale of the clock, this pulse is invisible short.
To make it visible, the graph must be operated in microstep mode. Only then events on the timescale of the propagation time are visible.
