### ISSUE TITLE
Problem with custom components path

### ISSUE THREAD

**Issue by gnaghi** [hneemann/Digital#1083]
The custom path of a project changes when I open another project in a new window, located in a different directory.

- Open project A located in directory zzz. Inside this directory, I have components A1 A2 and A3. They are available when opening the menu «Components/Custom».
- Open in a new window project B, located in directory yyy where components B1 and B2 are located in this directory. I can choose them in «Components/Custom».
- Come back into project A : I can no longer select A1 or A2, but B1 and B2 are available. And if A1 component was integrated into the project A, I have now an error message indicating that component A1 is no longer available.

**Comment by hneemann** [comment]
This is how it works. A single instance can open only one project.
