### ISSUE TITLE
Documentation: Improvement of English translation

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#109]
The English translation of the documentation could be improved.
It would be nice if a native speaker could look at it.

The source text can be found [here](https://github.com/hneemann/Digital/blob/master/src/test/resources/docu/static_en.xml).

**Comment by juecoree** [comment]
I have a PR on documentation improvement for static_en.xml. I have done some improvements on the Introduction, First Step, and Wires of the static_en.xml. I hope it could be helpful to this project.

**Comment by hneemann** [comment]
@juecoree Thank you for your contribution. I will integrate your suggestions soon.

**Comment by aaraujo666** [comment]
Reviewed the entire text... very few modifications... but there were some...

[static_en.zip](https://github.com/hneemann/Digital/files/1757360/static_en.zip)
