### ISSUE TITLE
Chinese translation update

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#1091]
@itviewer
It has been a long time since there was a new release. 
In the next few weeks I plan a new release, and again I would appreciate your help with the translation.

[lang_diff_zh.xml.zip](https://github.com/hneemann/Digital/files/10368484/lang_diff_zh.xml.zip)

**Comment by itviewer** [comment]
[lang_diff_zh.zip](https://github.com/hneemann/Digital/files/10370049/lang_diff_zh.zip)

**Comment by hneemann** [comment]
@itviewer 
Thanks again for your help!
