### ISSUE TITLE
French translation update

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#1092]
@maltaisn
It has been a long time since there was a new release. 
In the next few weeks I plan a new release, and again I would appreciate your help with the translation.

[lang_diff_fr.xml.zip](https://github.com/hneemann/Digital/files/10368493/lang_diff_fr.xml.zip)

**Comment by maltaisn** [comment]
[lang_diff_fr.zip](https://github.com/hneemann/Digital/files/10368778/lang_diff_fr.zip)

**Comment by hneemann** [comment]
@maltaisn 
Thanks for your help!
