### ISSUE TITLE
Analysis error message improvement

### ISSUE THREAD

**Issue by guiweber** [hneemann/Digital#11]
When starting analysis for a circuit, the following message appears if the input are not labeled. A similar message also appears of the outputs are not labeled.

![image](https://cloud.githubusercontent.com/assets/7825368/26502078/6acb1044-4209-11e7-83ff-3a30b2d348b7.png)

This is confusing as the circuit actually has inputs, they are just not labeled. The message should be changed to reflect that the inputs and outputs are not labeled.

**Comment by hneemann** [comment]
en translation improved in v0.12
