### ISSUE TITLE
Better/more highlighting for the Find function

### ISSUE THREAD

**Issue by mengstr** [hneemann/Digital#1128]
The find function is a really nice addition, but it is not particularly good at highlighting the found objects in the schematic - especially when the design is a bit larger. Could you make more visible somehow? Maybe a much larger and colourful blob than the current pale cyan. Or maybe even better - lines drawn from the top of the screen that ends at the objects.

<img width="1772" alt="DigitalFind" src="https://user-images.githubusercontent.com/325326/224476473-3b385b1d-bd1c-402f-9b4d-9505d19e0475.png">

**Comment by hneemann** [comment]
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/) and let me know how it feels.

**Comment by mengstr** [comment]
Ohh...  That is good!  Fat and, compared to other items, large when zoomed out, and then shrinks to a more normal size when you zoom in so it doesn't block the view.  Now I don't have pan and hunt all over the schematics to locate the found items. Thank you.
