### ISSUE TITLE
How to deal with custom n bit input?

### ISSUE THREAD

**Issue by parthokr** [hneemann/Digital#1138]
Hi,
How can I define an input other than 0-16 and 32 bits?

**Comment by hneemann** [comment]
Just enter the desired number. The maximum is 64 bit.

**Comment by parthokr** [comment]
> Just enter the desired number. The maximum is 64 bit.

Oops! Such a stupid mistake I made!
Thank you @hneemann

**Comment by hneemann** [comment]
Never mind!
