### ISSUE TITLE
Open-drain output bus not working wth bundled pullups.

### ISSUE THREAD

**Issue by nimaid** [hneemann/Digital#1150]
I have found a bug when using multiple open-drain outputs (using N-channel FETs) bundled in a bus. First, let me show you an equivalent example of what I want to do that *does* work like intended:
![digital_bus_pullup_good](https://user-images.githubusercontent.com/7099866/233641401-3721b5d8-fee7-420b-b49c-b355ffecacdf.PNG)
As you can see, the left-hand side of the screen has 4 simple open-drain NOT gates, with their outputs bundled into a 4-channel bus. The signals are `0`'s and `Z`'s. They then get unsplit into separate wires again, each with a pullup resistor. The pullup resolves the `Z`s into `1`'s, and leaves the `0`'s as `0`'s. As you can see in the output nodes, this is working as intended, and I get a fully digital output that is the inverse (NOT) of the input nodes.
Here is another example that works, using a 4-channel pullup resistor component:
![digital_bus_pullup_good2](https://user-images.githubusercontent.com/7099866/233645962-c0cdf5cf-56e4-4140-88ed-069b2c6b0249.PNG)
In this example as well, we know that the a pullup was connected to each wire in the bus using the 4-channel pullup. This, again, results in my desired behavior.
The problem only arises when I try to use bundled sets of pullup resistors to resolve those `Z`'s into `1`'s on the bus itself. Look at this image to see what I mean:
![digital_bus_pullup_bad](https://user-images.githubusercontent.com/7099866/233641421-ff0e098c-376d-4e73-8643-8da8c6dd58f4.PNG)
As you can see, I have a circuit which should in theory be electrically equivalent to the first two examples. Each open-drain output is connected to it's own pullup resistor at some point in the schematic. The key difference, which is what I suspect trips the simulator up, Is that in the second example, the pullups are seperated from the outputs by the bus and 2 splitters.

I propose that the optimal defined behavior in this case is to make the setup in the third image match the behavior in the first 2 images. This will probably require propagating pulled-up signals through splitters and onto buses.

**Comment by hneemann** [comment]
Splitters do have a derection.
The upper splitter has the wrong direction.
When it is rotated, it behaves as expected.
