### ISSUE TITLE
How do you scale down this gui?

### ISSUE THREAD

**Issue by Lucretia** [hneemann/Digital#1180]
I'm on a 4K screen, which has the UI scaled in KDE, the UI on this app is massive and doesn't respond to either ```GDK_DPI_SCALE=0.5``` nor ```QT_AUTO_SCREEN_SCALE_FACTOR=0.25``` and no matter what combination of these params I use ```java -Dsun.java2d.dpiaware=false -Dsun.java2d.uiScale=0.5 -jar ~/opt/Digital/Digital.jar``` it doesn't change.

Also, how do you move objects around?

**Comment by hneemann** [comment]
What font size is set in the settings?

**Comment by Lucretia** [comment]
I looked there but didn't see anything, all sorted, thanks.
