### ISSUE TITLE
Multiple formats in "raw" hex file?

### ISSUE THREAD

**Issue by aaraujo666** [hneemann/Digital#120]
In ROMLoader.java, you use the DataField class to parse the raw hex file.

I think the DataField class could be easily modified to allow more than just 2-digit hex.

For backwards compatibility, all other things being equal, parse it as hex (Bits.decode(line, 0, 16))

But could you implement:

if (line.StartsWith("0b") && (line.length > 2)) {
   v = Bits.decode(line.Substring(2), 0, 2);
}
if line.StartsWith("0x") {
   v = Bits.decode(line.Substring(2), 0, 16);
}
if line.StartsWith("0o") {
   v = Bits.decode(line.Substring(2), 0, 8);
}
if (line.StartsWith("0d") && (line.length > 2)) {
   v = Bits.decode(line.Substring(2), 0, 10);
}

Excuse my possibly wrong java syntax... just writing this out here :)

By the way... love the new rendered overbar on active-low signals :)

**Comment by hneemann** [comment]
Unfortunately that is not possible.
There are people out there witch edit their hex files manually.
And I'm sure there files like this:

00a
0b1
1b5
0d2
