### ISSUE TITLE
LaTeX formatting of truth table export

### ISSUE THREAD

**Issue by SirClickALot** [hneemann/Digital#1205]
I find the ability to export a truth table and associated expression(s) from the Analysis window in LaTeX format to be a really useful feature.

The TT itself is spot on but currently, I get expressions in the form...

```
\begin{eqnarray*}
F &=& (\overline{A} \und \overline{C}) \oder (A \und C) \oder (B \und C)\\
F &=& (\overline{A} \und \overline{C}) \oder (A \und C) \oder (\overline{A} \und B)\\
\end{eqnarray*}
```

I was wondering if there is any way to swap out:

1. \und for \cdot
2. \oder for +

To give...
```
\begin{eqnarray*}
F &=& \overline{A} \cdot{\overline{C}} + A \cdot{C} + B \cdot{C}\\
F &=& \overline{A} \cdot{\overline{C}} + A \cdot{C} + \overline{A} \cdot{B}\\
\end{eqnarray*}
```
Because my LaTeX set up does not understand and therefore does not render the (German?) \und and \oder.

My local version of Digital is already configured with English as its default language so that's not it!

Is there a way we can configure this?

Thank you

**Comment by hneemann** [comment]
This is done to allow formatting of expressions as needed.
I always use

```
\newcommand{\und}{~}
\newcommand{\oder}{\vee}
```
above the `\begin{document}` statement, in your case it would be
```
\newcommand{\und}{\cdot}
\newcommand{\oder}{+}
```
I choose to use the german `und` and `oder` to avoid to interfere with other LaTeX commands.

**Comment by hneemann** [comment]
You can insert these commands above \begin{document} in the tex-file, or in any imported sty-file.
