### ISSUE TITLE
Bug in AND component 

### ISSUE THREAD

**Issue by esbenovich** [hneemann/Digital#1220]
This is my very first try of the software, so I might be doing something wrong.

However I have this very [strange behaviour ](https://yourimageshare.com/ib/iKjmZIGnXX) the very simplest of circuits that I don't  understand.

Running on Ubuntu 18.04

**Comment by hneemann** [comment]
I'm not able to open the link above.

**Comment by esbenovich** [comment]
/

**Comment by hneemann** [comment]
See #665
