### ISSUE TITLE
Bidirectional EEPROM not loaded completely the attached file

### ISSUE THREAD

**Issue by stollenm** [hneemann/Digital#1236]
I use the Digital Version 0.30 EEPROM with bidirectional databus. The databus is 64 bits wide and the address bus 11 bits.

If I try to load the file at the bottom of this text, the following addresses are not loaded. They still hold the value 0.

0x718

0x719

0x738

0x739

0x798

0x799

0x7B8

0x7B9

v2.0 raw
10c000181
0
10c000284
10c000484
100001082
10c000284
100001082
0
10c000082
247*0
5046e00008086
563*0
5046e0000a080
127*0
586660000a080
95*0
5044e0000a080
11*0
7302c00004
22000000000040
0
0
5044e00008080
15*0
5044e0000a080
43*0
8020000000080
51*0
5045e0000a080
11*0
c200c00004
102000044
5050200000080
0
5045e00008080
15*0
5045e0000a080
43*0
8028000000080
51*0
5046e0000a080
11*0
7302c00004
4040
0
0
5046e00008080
11*0
100001080
47*0
8080000000080
51*0
586660000a080
11*0
c200c00004
102000044
15040200002080
0
5866600008080
59*0
8088000000080
47*0
2001000c0
0
0
0
2000040c0
0
0
0
2000200c0
7*0
5047200180000
7*0
5044200022000
7*0
2001000c0
0
0
0
2000040c0
0
0
0
2000200c0
7*0
10c000082
31*0
5044200102000
7*0
5044200420000
23*0
15040200080080
7*0
15040200010080
7*0
5044200080080
0
0
0
5044200002080
0
0
0
5044200010080
7*0
5044200084000
0
0
0
15040200002080
0
0
0
4044200014000
7*0
5044200080080
0
0
0
5044200002080
0
0
0
5044200010080
39*0
8800000000080
7*0
5044200810000
23*0
5069600200080
15*0
5069600200080
0
0
0
5069600008080
0
0
0
3200001084
25047000000140
0
0
0
504c200180000
0
0
0
5069600008080
0
0
0
5047200030000
7*0
5069600200080
0
0
0
5069600008080
0
0
0
3200001084
250470000000c0
0
3200001084
250470000000c0
35*0
8100000000080
31*0
5069600040080
15*0
5069600040080
0
0
0
586560000a080
0
0
0
200001084
2504c0000000c0
0
200001084
2504c0000000c0
0
0
0
504c200030000
0
0
0
5865600008080
0
0
0
80
7*0
5069600040080
0
0
0
586560000a080
0
0
0
200001084
2504c0000000c0
0
200001084
2504c0000000c0
35*0
8108000000080

**Comment by hneemann** [comment]
The file seems to be truncated. Can you zip the complete file and attach it here?
