### ISSUE TITLE
Multibit test gives unexpected result

### ISSUE THREAD

**Issue by me-nkr** [hneemann/Digital#1245]
![image](https://github.com/hneemann/Digital/assets/60778845/760e4054-f3a6-41d6-b1c4-11a9e1b3341f)

![image](https://github.com/hneemann/Digital/assets/60778845/30755b33-ce47-475b-8ac3-76cf2cf78552)

All are Not gates connected in parallel. And as you can see in the first SS, it does work as intended when run manually.

**Comment by hneemann** [comment]
It looks like the `0b` is missing at the beginning of the binary numbers used in the test case.

**Comment by me-nkr** [comment]
That was the issue, it would be better if there was better documentation for the test cases though.
