### ISSUE TITLE
allow specifying all delays in ps

### ISSUE THREAD

**Issue by sxpert** [hneemann/Digital#1249]
It would be a great feature to be able to specify delay per gate in picoseconds, according to what the various datasheets say, so as to simulate what the circuit actually does. 
It could also be useful to be able to specify a delay per wire, as that could also have significant effect depending on the length.

**Comment by hneemann** [comment]
This simulator does not support the simulation of real-time behavior of circuits. Only one propagation time per gate is supported, which is not further specified. It is a compromise between performance and simulation quality, which in my opinion covers all the important things for teaching and also enables the simulation of an entire processor sufficiently quickly.
