### ISSUE TITLE
something is wrong, but i cant figure out what

### ISSUE THREAD

**Issue by aimnrt** [hneemann/Digital#1254]
[gpunotworking.zip](https://github.com/hneemann/Digital/files/14152424/gpunotworking.zip)

the time module is working fine but the main part keeps saying this error: error calculating a step. Video mode was not detected (line len=800, hSync len=96: hNegative=false, line count=525, vSync len=2, vNegative=false)
does someone know what that means?

**Comment by aimnrt** [comment]
whait nvm, fixed it

**Comment by hneemann** [comment]
Can the issue be closed?

**Comment by aimnrt** [comment]
Yes

**Comment by agkaminski** [comment]
Had similar problem, for future reference (pls share solutions!): both `hNegative` and `vNegative` should be `true` in this mode.
