### ISSUE TITLE
Library not working

### ISSUE THREAD

**Issue by mehdimess24** [hneemann/Digital#1267]
I set the pathname correctly but it doesn't seem to pull up any chips from the library.

**Comment by hneemann** [comment]
Are you using a Mac?

**Comment by mehdimess24** [comment]
yes I am

**Comment by hneemann** [comment]
For some reason, MacOS pretends to running programs that certain folders do not contain any files.
And it seems that this happens silently, without the OS generating an error message like "Access denied". The folder simply appears empty. Please see #550. The last comment seems to suggest a solution.
