### ISSUE TITLE
Support for polarity aware LEDs?

### ISSUE THREAD

**Issue by n3rdopolis** [hneemann/Digital#127]
Hi

One feature that it might be worth simulating is to simulate the polarity of the LED, so that you can have  gates controlling both poles, like an example shown below that I made in kolourpaint to show what I mean. I guess the closest to this is the lightbulb, but those don't seem to be dependent on polarity, like LEDs are
![image](https://user-images.githubusercontent.com/6219356/37878001-8c2d54ca-3030-11e8-991a-e9b3c857d9ed.png)

**Comment by hneemann** [comment]
Do you have any idea what the graphical representation should look like?
I think the diodes symbol should be visible, but also the state "lights" must be clearly visible.
The above figure does not show the condition "lights" very clearly.

**Comment by n3rdopolis** [comment]
maybe the inside of the triangle could change color
or maybe better, ones that care about polarity can be a semi circle like this 
![image](https://user-images.githubusercontent.com/6219356/38088259-2ae390ca-3329-11e8-870c-9c8e1c130774.png)
since usually the base of a real LED, the cathode side is marked by the flat side of the base

**Comment by hneemann** [comment]
Can you explain what your use case is? What kind of exercise do you want to do?

**Comment by hneemann** [comment]
@n3rdopolis 
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/). What do you think about it?

**Comment by n3rdopolis** [comment]
Awesome!

**Comment by hneemann** [comment]
added in v0.18
