### ISSUE TITLE
Squashed Signals When Creating a Hierarchical Design

### ISSUE THREAD

**Issue by tthompsongmsi** [hneemann/Digital#1270]
I created an alu and then placed it in my current design. the signals are all squashed together. I Looked at the section on the SVGs but I don't see how to fix this problem. Please see attached immage.
![alu](https://github.com/hneemann/Digital/assets/146874450/b1a3cc1f-02a5-4865-9979-9d26fd09754a)

**Comment by hneemann** [comment]
In the settings of the alu you can define a width.

**Comment by tthompsongmsi** [comment]
Thank you!
