### ISSUE TITLE
Highlight the selected input pin on a Multiplexer

### ISSUE THREAD

**Issue by viniciusmiguel** [hneemann/Digital#1299]
Problem:
It is hard to identify when an input pin is selected on a multiplexer.

Solution:

Highlight the input connection port in the multiplexer when the input is selected.

**Comment by hneemann** [comment]
That's an interesting idea!

**Comment by hneemann** [comment]
You can try the latest [pre-realeae build](https://infdigital.dhbw-mosbach.de/).
