### ISSUE TITLE
Nand inconsistent

### ISSUE THREAD

**Issue by Shevvv** [hneemann/Digital#1317]
version: v0.30, OS: Cinnamon Mint 21.2

Looks like a very powerful tool. Unfortunately, Nand is seemingly inconsistent (or I'm stupid). Here are my versions of NOT and AND using Nand gates only, but in AND.dig it function as NOR instead, firing up only when both inputs are 0 for some reason. In NOT.dig it works as expected, firing up as long as there's at least one 0 input.

[Custom.zip](https://github.com/user-attachments/files/16606598/Custom.zip)

**Comment by hneemann** [comment]
On my machine it works perfectly fine.

**Comment by Shevvv** [comment]
Dark green = off, light green = on. Not the other way around. I am an idiot!
