### ISSUE TITLE
Expanding components, D-Flip-Flop 4 input

### ISSUE THREAD

**Issue by frsj8112** [hneemann/Digital#1318]
Hi, is it possible to expand the library so that it is possible to use a single component D-Flip-Flop with 4 bit input instead of 4 seperate D-Flip-Flop components?

**Comment by hneemann** [comment]
Why not setting the number of data bits to 4?

**Comment by frsj8112** [comment]
Sorry, I meant Number of Inputs.

Like the NAND, where you for example, can specify the amount of inputs from 2 to 4.

**Comment by hneemann** [comment]
If four data bits are configured in the d-ff, the data input is 4-bit wide, so a bus can be connected that is 4 bits wide.

**Comment by frsj8112** [comment]
But I can still just connect one input.
I would like to consilidate this:

![image](https://github.com/user-attachments/assets/5a8f54e6-20cb-4e5c-aaf4-58681199882e)

To this:
![image](https://github.com/user-attachments/assets/9436c8cf-22fd-4c78-8d01-8ad2f4aeeca9)

**Comment by hneemann** [comment]
Simply create a subcircuit that contains four d-ff.

**Comment by hneemann** [comment]
Put this file alongside your main circuit.

[D-FF4.dig.zip](https://github.com/user-attachments/files/16645282/D-FF4.dig.zip)
