### ISSUE TITLE
Error creating the circuitNo output connected to a wire ([1; Splitter, In_1; And, in; Not]). The state ofthe wire is undefined.Occurredinfile

### ISSUE THREAD

**Issue by EricBridy** [hneemann/Digital#1322]
![problem](https://github.com/user-attachments/assets/e8eec3b4-9389-4de5-b7ed-9905a133e61d)
![image](https://github.com/user-attachments/assets/08c2192d-b4c8-4398-b421-827afae0e9d6)
![image](https://github.com/user-attachments/assets/025a5a4a-fdf4-43ef-8c4b-9edcd65b0250)
Hello author, I am a beginner, I want to ask how to solve this situation

**Comment by hneemann** [comment]
The inputs and outputs of the Din splitter are the wrong way round.
