### ISSUE TITLE
Unable to Access Jarfile

### ISSUE THREAD

**Issue by NexoChan** [hneemann/Digital#1324]
I installed the required JRE and I still got this, even through command prompt.
![image](https://github.com/user-attachments/assets/a0893723-2115-48e3-a133-72c65166174d)

**Comment by hneemann** [comment]
It looks like you have cloned the repository. In this case there is no jar file. This must first be built. 
Only the distribution, which is available as a zip file via the download button, contains a pre-built jar file.

**Comment by NexoChan** [comment]
I'm sorry I'm kinda new here, how do I do that exactly? 
I downloaded the zip file vie download button, and it still says unable to access jarfile.

**Comment by NexoChan** [comment]
Nevermind, I'm dumb, I forgot about the "releases" section...

Thankss
