### ISSUE TITLE
Bug (I guess) in the Triggered Data Graph

### ISSUE THREAD

**Issue by mengstr** [hneemann/Digital#1331]
If I start the circuit (attached) directly with the RUN button I only get  a few samples in the Data Graph (even if the probe says there was 100 clocks into the graph).  But if I "prime" the Data Graph by pressing the MANUAL button a few times and then RUN, I get all 100 samples into it. 

The number of samples when "unprimed"  sometimes varies from run to run. Sometimes it about 20 and sometimes just 10. Sometimes the first few samples are shifted out of the stored data so I just see samples 3 to 15. So I almost looks like it's a variable that's not initialised properly unless the graph is reset by a user action in the same cycle.

(Another thing - it would be nice if the graph was reset when starting the simulation, as it is now the old data is still visible until the first new sample is captured clearing the old data and starts to show the new ones.)

EDIT: Maybe relevant
<img width="268" alt="Screenshot 2024-09-21 at 10 58 39" src="https://github.com/user-attachments/assets/4d6a1a17-139d-4421-843c-c0614095998f">

[TriggeredDataGraph.dig.txt](https://github.com/user-attachments/files/17083337/TriggeredDataGraph.dig.txt)

<img width="1058" alt="TriggeredDataGraph" src="https://github.com/user-attachments/assets/b032bed4-d9cf-4c96-bde6-b723e854360a">

<img width="969" alt="Screenshot 2024-09-21 at 09 58 30" src="https://github.com/user-attachments/assets/1cafb374-f62f-4a5b-bce9-0d27b0e746e9">

<img width="980" alt="Screenshot 2024-09-21 at 09 58 48" src="https://github.com/user-attachments/assets/f40fc957-8673-4054-a36b-94b9f100adc7">

**Comment by hneemann** [comment]
That's an interesting one! I'll have to think about that!
Thanks for pointing out!

**Comment by hneemann** [comment]
Would you try version v0.31-2 found [here](https://infdigital.dhbw-mosbach.de/)?
Please let me know if this helps!

**Comment by mengstr** [comment]
I've tried it on two of my current projects and it seems to work fine now. All triggered samples shows up, no annoying rapid opening/closing of the scope window and slowdown due to that.  🎉 

Two minor niggles remain.

1) The slightly annoying focus capture when the scope window is created necessitating the need to click on the main window to be able to continue using the button-shortcuts in my design. Unless it's a 1-line fix I can live with this. ;-)

2) The scope screen is not cleared at simulation start. Not really a problem, it just feels a bit strange.

**Comment by mengstr** [comment]
Fantastic. I really appreciate that you fixed this issue. Thanks.
