### ISSUE TITLE
Assign bin file to eproms

### ISSUE THREAD

**Issue by malcrom** [hneemann/Digital#1353]
Would it be possible to assign a bin file to individual eproms to properly test circuits?

**Comment by hneemann** [comment]
If you give the EPROMS a label, you can assign data in the circuit-specific settings under Advanced->Content of ROMs.

**Comment by malcrom** [comment]
> If you give the EPROMS a label, you can assign data in the circuit-specific settings under Advanced->Content of ROMs.

Thank you.
