### ISSUE TITLE
More comfortable splitter

### ISSUE THREAD

**Issue by Valaphee** [hneemann/Digital#141]
Signals can be splitted, but they can't be combined with a splitter like a splitter in logisim. This is a big problem for custom components like a complex ALU which is splitted in cells.

An another problem is the pin order, which cannot be changed and the splitter can't be flipped (are lefthanded and cannot be changed to righthanded splitter)

**Comment by hneemann** [comment]
As far as I understand Logisim, the splitter in digital is more configurable than the splitter in Logisim.
The big difference between Logisim and Digital is that the splitters in Digital have a direction, while a splitter in Logisim  does not. And that's essentially a decision in favor of performance.

![splitter](https://user-images.githubusercontent.com/7190563/39371802-f74e5d2c-4a42-11e8-8c26-21b0435bc805.png)

**Comment by Valaphee** [comment]
Oh okay, that's new for me.

I'm started working with Digital just 4 days ago.
It would be great, to make the use of splitter more understandable.

But so far, thanks.

**Comment by hneemann** [comment]
Did you not find the help text or was it not helpful? See #70
