### ISSUE TITLE
add blank rows to the input and output lists

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#149]
It would be nice to have the ability to organize the inputs and outputs of an embedded circuit into groups using blank rows.

e.g. for a dual 4-bit counter the 2CLK and 2CLR inputs would be shifted down 2 lines to line up with the matching 2Q0-4 outputs.

**Comment by hneemann** [comment]
Currently I'm working on importing SVG graphics to use them as shapes. See #39
If the SVG import is working, you are free to place the pins at any location you want.
So I decided not to implement this feature.
