### ISSUE TITLE
Suggestion: Implement additional shortcuts for frequent actions

### ISSUE THREAD

**Issue by guiweber** [hneemann/Digital#15]
I would suggest implementing the following shortcuts:
- CTRL+S : Save
- CTRL+X: Cut. Cut and paste would be different from selecting and moving since the cut functionality would disconnect the wires.
- SPACE : Start/Stop the simulation

**Comment by hneemann** [comment]
added in v0.12

**Comment by guiweber** [comment]
@hneemann I forgot this one which is also useful when you have to do a lot of clock cycles manually :

CTRL : Cycle the clocks in the circuit when the simulation is active

**Comment by guiweber** [comment]
@hneemann And now that we have Undo:

CTRL+Z: Undo
CTRL+Y: Redo

**Comment by hneemann** [comment]
Fixed in v0.12
Added a list of shortcuts to the documentation.
