### ISSUE TITLE
Cannot open half adder

### ISSUE THREAD

**Issue by dmolony** [hneemann/Digital#157]
I built a half adder according to the example in the manual. When I select it from the custom menu, I get an error dialog:

Error importing the circuit half adder.dig!
Error importing the circuit /Users/me/Documents/half adder.dig!
caused by: Found a pin without a name.

All four pins have the correct names. The circuit runs correctly by itself. The Order Inputs and Order Outputs menu options show the correct inputs and outputs.

**Comment by hneemann** [comment]
That's strange. 
Can you attach the circuit to the issue. Than i can dig into it.

**Comment by dmolony** [comment]
[halfAdder.dig.txt](https://github.com/hneemann/Digital/files/2064950/halfAdder.dig.txt)
I don't know if this will work, I added .txt to the file name to bypass github's check.

**Comment by dmolony** [comment]
The error message is also slightly wrong, it has left a folder out of the path. Perhaps it can't actually find the file?

**Comment by hneemann** [comment]
Are you sure you sent the correct file?
It works as expected on my machine.

**Comment by dmolony** [comment]
It's the only file I have, so it must be the correct one. I'm using macOS if that makes any difference. Also, see my previous message about the incorrect path.

**Comment by dmolony** [comment]
I just tried quitting the program and restarting, and now it works. There's still a bug in there, but now I can't recreate it.

**Comment by hneemann** [comment]
See also #33
