### ISSUE TITLE
Edge trigger option for flip-flops

### ISSUE THREAD

**Issue by guiweber** [hneemann/Digital#16]
Logisim allows setting the trigger for flip-flops to rising or falling edge. It would be nice to have the same option in Digital.

**Comment by hneemann** [comment]
Is it a question of convenience or have you had trouble using an inverter caused by the additional delay time of the inverter?

**Comment by guiweber** [comment]
No, I haven't had issues. I assumed this would be needed to replicate packages such as the 74112 without introducing delay issues. But thinking about it, you are probably right, I don' think it would actually cause any issues to use an inverter.
