### ISSUE TITLE
How do I start this on Fedora ?

### ISSUE THREAD

**Issue by stehgold** [hneemann/Digital#162]
Hi,
how do I start this ? When I ran Digital.sh I get:
Error: Unable to access jarfile Digital.jar
Digital.jar is in the same directory.

**Comment by hneemann** [comment]
I do not know Fedora, but I guess you can just click on the `Digital.jar` file.

At the command line you can type:

`java -jar Digital.jar`

If you want to use the shell script, you must correct the path used in the shell script.

**Comment by stehgold** [comment]
Hi,
double click opened it with the zip tool. I'm using the fully qualified path in Digital.sh now and this works.
Thanks
