### ISSUE TITLE
Can not change input and output names of a opened truth table

### ISSUE THREAD

**Issue by roy77** [hneemann/Digital#166]
After opening a .tru file the names of inputs and outputs can not changed. A workaround is to reorder the inputs or outputs. After reordering it is possible to change the names.

**Comment by hneemann** [comment]
Can you explain in more detail what you did?
It works as expected on my machine.

**Comment by roy77** [comment]
I am currently working with 0.16 and 0.19 and have confused the versions. The error occurred in version 0.16 and is fixed in 0.19. Sorry for that. A other small problem occurred. To load a 0.16 .tru file with 0.19 I have to remove the <pins> and <pinsWithoutNumber> attribute in xml file. But it won't be worth fixing.
