### ISSUE TITLE
Custom components port orientation

### ISSUE THREAD

**Issue by josepll** [hneemann/Digital#169]
Custom and external components have all inputs on left and all outputs on right. On some ocassions that leads to weird and complex layouts. I propose to be able to select port orientation, so that the user can select if a port is facing: left, right, top or bottom. Maybe that implies that not only component width is selectable, but also its heighth.

**Comment by hneemann** [comment]
I do not want to implement that. I plan to implement custom shapes that are much more flexible.
At the moment, custom shapes are already implemented, but the ability to import an SVG shape is missing. Therefore, you must manually edit the XML file to create a custom shape. Possible but very difficult to use. 
See also #39
