### ISSUE TITLE
Grey out save button if all changes saved

### ISSUE THREAD

**Issue by guiweber** [hneemann/Digital#17]
It would be nice to have a hint when our work is saved, such as greying out the save buttons.

**Comment by hneemann** [comment]
There is a asterisk in front of the file name in the window header.

**Comment by guiweber** [comment]
Greying out the button would, in my opinion, better communicate this to the user. If this is something you do not like, I suggest making the hint more visible as it is currently very subtle.

**Comment by hneemann** [comment]
Hmm.. I will think about it.

**Comment by hneemann** [comment]
added in v0.13
