### ISSUE TITLE
Chronogram displays contents of multiwire 

### ISSUE THREAD

**Issue by josepll** [hneemann/Digital#170]
Right now the measurement graph shows the level of multiwire signals. That is ok if only a handful of levels are possible. However for big buses (e.g. 32 bits) its much better to show contents and content changes. See example below.

![scope](https://user-images.githubusercontent.com/40889524/42378330-3996f67e-8127-11e8-8b29-d077da4daf2c.gif)

**Comment by hneemann** [comment]
@josepll 
Please try the latest [pre release build](https://infdigital.dhbw-mosbach.de/)

**Comment by josepll** [comment]
Better, but it still is a bit confusing with high values.
See for instance what happens when increasing a 8 bits register (PC) by 4 every clock cycle
![image](https://user-images.githubusercontent.com/40889524/42422948-fe241592-82f0-11e8-949c-46b11801960a.png)
Changes are only shown every 2 cycles because levels don't change (visually) even though they are increased by 4.
For higher values (32 bit register) it's even worse.
![image](https://user-images.githubusercontent.com/40889524/42422977-efe818e2-82f1-11e8-84ee-fb0276094c0d.png)
In last pic register was still increasing by 4 every clock cycle.
Notice that levels are not very useful here.

**Comment by hneemann** [comment]
@josepll 
Please try again!

**Comment by josepll** [comment]
Now works great for small values (up to 8/12 bit)

However there are still issues when displaying big values (16/32 bit). See what happens when increasing register by 512.
![image](https://user-images.githubusercontent.com/40889524/42435346-7e418de4-8356-11e8-9b09-ad7636769f13.png)
0x400 gets displaced and 0x600 is missing
The issue appears because the visualization window gets clogged with big values that require extra space. I think the issue just requires extra zoom-in.
See what happens with a bit of zoom-out
![image](https://user-images.githubusercontent.com/40889524/42435439-da0ea2ce-8356-11e8-9782-6416c9967a13.png)
I think will be enough to allow extra zoom so that the user can visualize what he needs.

**Comment by hneemann** [comment]
@josepll
Now it's possible to zoom into the measurement graph.

**Comment by josepll** [comment]
Excellent. Now 32 bit values are shown with no issue. Probably 64 bit values fit too.
Thanks a lot.

**Comment by hneemann** [comment]
@josepll 
It was annoying to me that the names of the signals were not always visible. :-)
So I decided to reimplement the scaling and moving behavior of the data in the measurement graph.
If you have some time, please try the latest pre-release and let me know what you think about it.

**Comment by josepll** [comment]
Only problem is that once you zoom-in the window remains in a fixed possition instead of advancing with the simulation. However if you remain at the default zoom the sliding window advances with the simulation as expectes, showing latest changes.

With default zoom (notice slider on the right)
![imagen](https://user-images.githubusercontent.com/40889524/42496310-dfd5567e-8425-11e8-81d3-8bffe3fbe854.png)

With a bit of zoom at start (notice slider remains where it was before zooming in)
![imagen](https://user-images.githubusercontent.com/40889524/42496409-394fcd7e-8426-11e8-8c5e-0f194bb44916.png)

Same thing happens if you zoom out.

**Comment by josepll** [comment]
So far works well. Hoever for complex designs/chronogrmas it gets a bit confussing. A proper chronogram is more intuitive.
[chronogram.pdf](https://github.com/hneemann/Digital/files/2183994/chronogram.pdf)

**Comment by josepll** [comment]
That values don't jump up and down, that is very confusing and difficult to follow for big chronograms. Maybe the solution is to have the OPTION to show multiwire signals as levels or as bus contents
See the difference below:
Digital:
![image](https://user-images.githubusercontent.com/40889524/42681472-1819b1c4-8688-11e8-8677-a0de08f53a2c.png)
tkgate:
![image](https://user-images.githubusercontent.com/40889524/42378330-3996f67e-8127-11e8-8b29-d077da4daf2c.gif)
gtkwave:
![image](https://user-images.githubusercontent.com/40889524/42681714-c3d31ece-8688-11e8-96b6-4ec23eb4acff.png)

For debugging complex circuits I prefer the later ones.
