### ISSUE TITLE
Please implement assembler API interface for EEROM and RAM and a load data option for RAM.

### ISSUE THREAD

**Issue by sgparry** [hneemann/Digital#174]
The LMC CPU architecture I am recreating in digital has no ROM - I am implementing an assembler I would like to be able to load programs and debug them. Please add the assembler API that is available for ROM to EEROM and RAM and the ability to load programs to RAM. Yes, I know having a RAM load option is not very realistic but LMC is too primitive to even implement its own bootloader.

**Comment by hneemann** [comment]
Why not putting a ROM and a RAM together to a shared address space? This would allow to use the existing interface.

**Comment by hneemann** [comment]
See also #167.

**Comment by sgparry** [comment]
Not sure how would I arbitrate between the two chips?

On 21 July 2018 16:59:43 BST, Helmut Neemann <notifications@github.com> wrote:
>Why not putting a ROM and a RAM together to a shared address space?
>This would allow to use the existing interface.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hneemann/Digital/issues/174#issuecomment-406806034

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hneemann** [comment]
With the latest commit you can also access a RAM from the assembler API and write code to it.

And [here](https://github.com/hneemann/Digital/blob/master/src/main/dig/processor/core/Memory.dig) you can find a combined memory. The Von Neumann processor example uses it. 

![splitmemory](https://user-images.githubusercontent.com/7190563/43048389-2a7cdce0-8de7-11e8-8496-09fc0ac77eee.png)

**Comment by sgparry** [comment]
Thank you again as always Helmut  Having the RAM assembler accessible and loadable I think will solve this requirement. I can add calls to the assembler api into my LMC assembler allowing my students to create, load and debug programs.
I cannot use the shared address space approach - The Binary LMC only has a 5 bit address space and no assembler directives for setting an address! However I could create a hardware bootloader to load from a ROM. It opens useful discussions with the class on loaders and bootloaders.
Another possibility would be if EEROM was assembler accessible, but I have the feeling that might prove more difficult than RAM?

On 22 July 2018 18:43:34 BST, Helmut Neemann <notifications@github.com> wrote:
>With the latest commit you can also access a RAM from the assembler API
>and write code to it.
>
>And
>[here](https://github.com/hneemann/Digital/blob/master/src/main/dig/processor/core/Memory.dig)
>you can find a combined memory. The Von Neumann processor example uses
>it. 
>
>![splitmemory](https://user-images.githubusercontent.com/7190563/43048389-2a7cdce0-8de7-11e8-8496-09fc0ac77eee.png)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hneemann/Digital/issues/174#issuecomment-406884183

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hneemann** [comment]
> Another possibility would be if EEROM was assembler accessible, but I have the feeling that might prove more difficult than RAM?

EEPROM is already accessible by a assembly IDE.

**Comment by sgparry** [comment]
Thanks Helmut. You move this project so fast I just can't keep up! :-)
