### ISSUE TITLE
Allow Register File to be displayed in measurement table

### ISSUE THREAD

**Issue by elijahlorden** [hneemann/Digital#176]
When debugging a processor design, it is important to be able to check the state of registers at the time of a breakpoint.  If the register file is used, it is not possible to examine the contents of individual registers if the file itself is in a subcircuit.  This could be fixed by adding an option to show the contents of the Register File in the measurement table.

**Comment by hneemann** [comment]
The register file is treated like normal memory. 
In the measurement table you can open it in the "Memory" menu.
