### ISSUE TITLE
Suggestion: New/Different GraphicsRAM Palette 

### ISSUE THREAD

**Issue by IForgotMyUN** [hneemann/Digital#182]
The current palette is weird and kind of inconsistent. It doesn't fit in 6 bits yet is to small for 7 bits and is somewhat of mess. It might be possible to just make it an RGB or RGBI colours pace, where you can choose the amount of bits you want to spend on each colour. I don't think it would be to hard to implement, but would probably make the GRAM much more usefull

**Comment by hneemann** [comment]
The palette used is simple: the first ten colors are some basic color values for ease of use, then there are 32 gray values, and after that, starting with index 42, there are 64 colors with two bits per RGB value. So there are 106 colors which index fits into 7 bits.

It is possible to extend the palette to 32786 + 42 colors, which is equivalent to 5 bits per RGB value, which is similar to the old VGA 15-bit HiColor modes. However, this would require a 16-bit data bus.

But what is your use case? What do you want to do with the GRAM?
