### ISSUE TITLE
RGB LED Addition Request

### ISSUE THREAD

**Issue by mgriebling** [hneemann/Digital#191]
I think it would be useful to have an RGB LED in the components where it has three connections, each of which could vary from one to eight bits.  This would allow use as an ordinary RGB LED with three leads or a full-colour LED with 2^24 colours.  I'm using such LEDs in several places in my designs so it would be helpful to be able to show them in the simulations as well.  I would volunteer to do this implementation myself but might need a few hints on how to best do this.

**Comment by hneemann** [comment]
@mgriebling 
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/) build.

**Comment by mgriebling** [comment]
Very nice! Thanks.
