### ISSUE TITLE
Error while simulating circuit

### ISSUE THREAD

**Issue by mgriebling** [hneemann/Digital#195]
I'm in the process of transferring some of my Logisim circuits to Digital and encountered the following error during simulation:

<img width="464" alt="error" src="https://user-images.githubusercontent.com/2421348/46467460-c8f29700-c79b-11e8-8c93-b401d059e513.png">

Here's the file that caused the problem.  Set all the inputs high, enable the alarm, and set one of the inputs low to reproduce the error.  I don't believe there are multiple outputs feeding one wire.

[NandAlarm.dig.zip](https://github.com/hneemann/Digital/files/2445895/NandAlarm.dig.zip)

**Comment by hneemann** [comment]
Try to remove the NAnd which is directly connected to the output.

**Comment by mgriebling** [comment]
That's nasty, how did you find that?  I wonder if there is a way to identify where the problem is located to help in debugging this sort of issue.  It certainly isn't visually obvious.
