### ISSUE TITLE
Selektieren von "Verbindungslinien" mit Klick

### ISSUE THREAD

**Issue by M-Reimer** [hneemann/Digital#2]
Der einzige Weg, den ich gefunden habe, um "Leitungen" zu löschen ist, diese über Aufziehen eines Fensters zu selektieren. Dies ist nicht immer möglich. Bei einer Leitung von der links und rechts weitere abgehen selektiert man automatisch auch die angrenzenden.
Es wäre vorteilhaft, wenn man durch einfachen Klick in eine Leitung diese selektieren könnte. Bisher erzeugt dies einen Abzweig von dieser Leitung.
Eventuell wäre es dann in dem Zuge sinnvoll separate "Auswählen" und "Verbindungsleitung zeichnen"-Werkzeuge anzubieten.

**Comment by hneemann** [comment]
Fixed in v0.10
