### ISSUE TITLE
Multiplier but where is the divisor ?

### ISSUE THREAD

**Issue by FlorianF74** [hneemann/Digital#201]
Hello,
I have a problem, I wanted to create an ALU with the division and the modulo but I saw that there was a multiplier in the arithmetic components but no divisor !!

Can you add one?
Thank you
Florian

**Comment by hneemann** [comment]
@FlorianF74 
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/).

**Comment by FlorianF74** [comment]
Yes I know, thank you very much
