### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by kendfrey** [hneemann/Digital#204]
It would be nice if there was a dark colour scheme option. This would make Digital more comfortable to use for long periods of time.

Example created with an image editor:

![image](https://user-images.githubusercontent.com/1657228/47537267-c4009f00-d892-11e8-8404-a15cca33f7fc.png)

**Comment by hneemann** [comment]
It looks very bad when the circuit is dark, but not the rest of the UI.
And it costs a lot of work to create a dark theme for swing. Although you can find something out there, all my UI adjustments would have to be revised.
In my eys a lot of work for little benefit.
