### ISSUE TITLE
How to represent a memory with mask ability

### ISSUE THREAD

**Issue by itviewer** [hneemann/Digital#209]
I want to represent a byte-addressable memory, but can support reading (or writing) bytes, halfwords, words. Is it possible?

**Comment by itviewer** [comment]
I think yes,I am learning how to implement a single-cycle 32bit RISC-V CPU core, I am having trouble implementing LB(load byte), LH(load halfword) instructions.
How hard is it to implement such a function?
Thanks.

**Comment by hneemann** [comment]
If you want to support misaligned memory addresses, this is complicated.
If you don't want to support misaligned memory addresses, this is easy.

**Comment by itviewer** [comment]
I don't think there is a need for misaligned memory addresses. 
Can you give some advice about it?

**Comment by hneemann** [comment]
Ignore the lowest two bits of the address while creating the address of the 32 bit memory.
LB: Use the lowest two bits to select the correct byte from the 32 bit data output.
LW Use the second lowest address bit to select the word, and ignore the lowest address bit.

**Comment by itviewer** [comment]
how about write operations? such as SB (store byte) instruction?

**Comment by hneemann** [comment]
If you want so support also SB and SH instructions, you have to use four seperate 8 bit memory components. Than you are able to select the byte which you want to overwrite.
