### ISSUE TITLE
graphic RAM color map?

### ISSUE THREAD

**Issue by mitolegy** [hneemann/Digital#224]
is there any documentation on what hex values correspond to the different colors in the graphic RAM component?

**Comment by hneemann** [comment]
The values 0 up to 10 represent the colors WHITE, BLACK, RED, GREEN, BLUE, YELLOW, CYAN, MAGENTA, ORANGE and PINK.
The values 32 up to 63 represent gray colors and the values 64 up to 127 represent a color palette with two bits per color channel. This simple color palette can be accessed with a 7 bit or 8 bit index.
If a 16 bit index is available in your design, you can use a 15-bit high color palette starting at index 0x8000 up to 0xFFFF which uses 5 bits per color channel to represent 32768 colors.
