### ISSUE TITLE
Is it possible to enter a boolean expression in the text component?

### ISSUE THREAD

**Issue by itviewer** [hneemann/Digital#235]
for example, I want `Y = !A & !B & C` , but when enter `Y = ~A~BC ` I get this,

![2019-01-30 09-42-05](https://user-images.githubusercontent.com/1397840/51952412-5fe20e00-2473-11e9-9d0d-0157afe14e6b.png)

**Comment by nevercast** [comment]
Presumably this is so you can enter something like `~CLK`

**Comment by itviewer** [comment]
> Presumably this is so you can enter something like `~CLK`

I just want to annotate the function of the circuit in the schematic.

**Comment by hneemann** [comment]
Try `Y = ~A~{B}C` or `Y = ~A ~B C`.

**Comment by itviewer** [comment]
thanks,`{}` works well
