### ISSUE TITLE
generic embedded circuits.

### ISSUE THREAD

**Issue by TheRealOrangus** [hneemann/Digital#238]
The idea is to specify a list of custom attributes with numerical ranges of a circuit that could then (optionally) replace actual attribute values of components inside that circuit.

That way a user can create an embedded circuit with attributes like "data bits", "address bits", and so on..
Each instance/inclusion of that embedded circuit would have its own actual attributes.

It would remove
* the need to create a bunch of circuits that have the same schematic but only differ in attributes of their internal components.
* the need to edit embedded circuits if only a change to its components' attributes are needed.

**Comment by hneemann** [comment]
I have already tried to implement such a feature because it would be very handy.
But unfortunately I ran into bigger problems during the implementation.
I think I need to think a little bit more about the problem before I can come up with a good solution.
