### ISSUE TITLE
Resize der Baumansicht der Bauteile klappt nicht immer

### ISSUE THREAD

**Issue by carstenhag** [hneemann/Digital#24]
Version: `v0.12.1`, commit `93a576c2e193caa54b9e29ae8341af42919f9cca`
OS: macOS Sierra, 10.12.4 - MacBook Pro, Retina 15'

Die Baumansicht der Bauteile wird angezeigt wenn man unter Ansicht diese Option aktiviert. Sie öffnet sich aber zu klein und man kann die Größe nicht immer verändern.

Die Veränderung dieser "Vertical Bar" funktioniert nur bei jedem ca. fünften Versuch (beim verschieben nach rechts). Wenn man die Bar nach links verschiebt klappt es meistens, aber auch nicht immer.

Auch werden die Icons der Bauelemente nicht korrekt skaliert - man kann die Elemente der Baumansicht nicht voneinander unterscheiden.

Screenshot:
![Screenshot Bug](http://i.imgur.com/C0T6yKh.png)

**Comment by hneemann** [comment]
Können Sie Digital einmal auf der Komandozeie mit folgender Anweisung starten:

`java -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel -jar Digital.jar`

Wie sieht es dann aus?

**Comment by carstenhag** [comment]
Scheint sich nur Optisch geändert zu haben, Bug bleibt.
![Screenshot Bug 2](http://i.imgur.com/rwbyILZ.png)

**Comment by hneemann** [comment]
Die Icons in der Baumansicht scheinen aber jetzt unterscheidbar zu sein?

**Comment by carstenhag** [comment]
Ah ja, das habe ich total vergessen. Die Icons sieht man jetzt gut.

2017-06-08 20:22 GMT+02:00 Helmut Neemann <notifications@github.com>:

**Comment by hneemann** [comment]
Können Sie einmal [diesen](https://drive.google.com/open?id=0B1nBRhIo-nQucTZiOUs3aENvMHc) Zwischenstand starten und schauen, was im Settings Dialog bei "Schriftgröße im Menü" angezeigt wird?

**Comment by carstenhag** [comment]
Momentan steht dort 114%.

Am 8. Juni 2017 um 20:46 schrieb Helmut Neemann <notifications@github.com>:

**Comment by hneemann** [comment]
Und der Rest (Icons, Schriftgröße) ist so weit ok?
Sind die Icons in der Baumansicht auch noch sichtbar, wenn Sie Digital per Doppelklick starten (also ohne das `java -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel -jar Digital.jar`)?

**Comment by carstenhag** [comment]
Icons und Schriftgröße sehen gut aus.

Mit beiden Startmethoden (mit dem -Dswing... flag und ohne) sind die Icons sichtbar.

Bei der Startmethode ohne dem Flag wird mit dieser neuen Version allerdings der Haken bei dem Menüeintrag angezeigt, auch wenn die Ansicht deaktiviert ist:

![Screenshot](https://i.imgur.com/aP4zG99.png)

**Comment by hneemann** [comment]
Wird der Haken konsistent, wenn Sie ihn klicken? Passen also Haken und "Vorhandensein der Baumansicht" nach dem ersten Klick zusammen?

**Comment by carstenhag** [comment]
Nein, dieser bleibt immer "aktiv". Hatte ich vergessen zu schreiben.

2017-06-08 21:29 GMT+02:00 Helmut Neemann <notifications@github.com>:

**Comment by hneemann** [comment]
Wenn Sie noch Lust haben, können Sie einmal die Schriftgröße auf 100% setzen und nach dem Neustart noch einmal das Häkchen ausprobieren.

**Comment by carstenhag** [comment]
Digital wir mit `java -jar Digital.jar` gestartet. Neue version (die hier verlinkte).

Wenn die Schriftgröße auf 100% gestellt ist, hat Digital das gleiche "Skin" wie mit `-Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel`, komischerweise. Dort ist die Checkbox/der Haken korrekt.

Mit 114% wird das "normale" Skin angezeigt und es tritt der Bug mit dem Haken auf.

**Comment by hneemann** [comment]
Danke für die Info! Können Sie mit der neuen Version Einfluss auf die Schriftgröße nehmen? Ändert sich überhaupt etwas an der Schriftgröße, wenn Sie z.B. 200% einstellen?

**Comment by carstenhag** [comment]
Ja, die UI wird riesig.

![Screenshot](http://i.imgur.com/27vKOSJ.png)

**Comment by carstenhag** [comment]
Mit der neuen Version und mit 114% Schriftgröße funktioniert der Haken.

![Screenshot](http://i.imgur.com/P2nkSlQ.png)

Der originale Bug des verschiebens der Vertical Bar existiert noch.

**Comment by hneemann** [comment]
Da bei der JSplitPane die Java-Swing-API ohne irgend welche Anpassungen verwendet wird, vermute ich, dass das Problem nicht in Digital zu suchen ist ([Siehe hier](https://www.heise.de/mac-and-i/meldung/Java-Aerger-mit-macOS-Sierra-3567822.html)). Daher werde ich hier zunächst nichts weiter unternehmen. 
Vielen Dank für Ihre Hilfe.
