### ISSUE TITLE
Bit count of splitter is not matching

### ISSUE THREAD

**Issue by copart** [hneemann/Digital#241]
Hi,

This app is a huge improvement to logisim!
Two issues:
1) Would be nice is the HEX input would allow the DP input to be optional
2) I cannot get the splitter to work, attaching example dig file. When I try to "simulate" I get an error "Bit count of splitter is not matching"

[test.dig.zip](https://github.com/hneemann/Digital/files/2849163/test.dig.zip)
![test](https://user-images.githubusercontent.com/4510261/52536950-f98ca380-2d2e-11e9-8678-36d9dc503fd3.png)

**Comment by hneemann** [comment]
> This app is a huge improvement to logisim!

Thank you very much!

> Would be nice is the HEX input would allow the DP input to be optional

You can use the ground connection. See discussion here: #215, #36

![test](https://user-images.githubusercontent.com/7190563/52537875-e0561800-2d6b-11e9-8354-d83e2a55a8f1.png)


> I cannot get the splitter to work, attaching example dig file. When I try to "simulate" I get an error "Bit count of splitter is not matching"

Input A outputs 4 bits instead of 1 bit.

**Comment by copart** [comment]
Thank you!
