### ISSUE TITLE
Brazilian Portuguese Translation update (v1)

### ISSUE THREAD

**Issue by crcpucmg** [hneemann/Digital#242]
Brazilian Portuguese Translation updated,
some minor edition and new keys added.

[lang_pt_update_v1.zip](https://github.com/hneemann/Digital/files/2849342/lang_pt_update_v1.zip)

**Comment by hneemann** [comment]
@crcpucmg 
You can find the complete translation in the latest [pre release build](https://infdigital.dhbw-mosbach.de/).

You may have noticed that the PDF documentation is automatically generated from the lang_xx.xml files. In this step, a static text part is added to the documentation. So far this part is missing in the Portuguese documentation. This static part can be found in the file [src/test/resources/docu/static_en.xml](https://github.com/hneemann/Digital/blob/master/src/test/resources/docu/static_en.xml). 
Are you interested in translating the chapters "First Steps" and "Hierarchical Design" to Portuguese as well? In this case I would create the necessary screenshots.

**Comment by crcpucmg** [comment]
I'll take a look, and if there's any free time, you can count on me.


Em dom, 10 de fev de 2019 às 19:42, Helmut Neemann <notifications@github.com>
escreveu:

**Comment by crcpucmg** [comment]
The translated file static_pt.xml was uploaded as a new issue.


Em dom, 10 de fev de 2019 às 19:42, Helmut Neemann <notifications@github.com>
escreveu:
