### ISSUE TITLE
Test result reporting is numbered differently than the test editor

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#248]
Test number 0 in the Test results is line 2 in the editor.  Which is annoying when fixing errors.  I realize it's probably completely out of sync when repeats are used but maybe another column with the source line number would be enough (and easy to implement).

**Comment by hneemann** [comment]
The tests results are simply numbered. The number has nothing to do with the line number in the test case editor. But maybe it should.

**Comment by hneemann** [comment]
see 05578f9481d8847f5642318aca705fcc5612f900 and b820fcfdfa20af207f3926cfe427e20fc15b6834
