### ISSUE TITLE
Icons in den Menü-Elementen werden auf Retina-Bildschirmen nicht korrekt skaliert

### ISSUE THREAD

**Issue by carstenhag** [hneemann/Digital#25]
Version: `v0.12.1`, commit `93a576c2e193caa54b9e29ae8341af42919f9cca`
OS: macOS Sierra, 10.12.4 - MacBook Pro, Retina 15'

Die Icons in den Menü-Elementen (Im dropdown) werden nicht korrekt skaliert und machen das manche Menü-Einträge viel höher sind als solche ohne Icon.

![Screenshot bug](http://i.imgur.com/Z3Fyifm.png)

**Comment by hneemann** [comment]
Das ist tatsächlich Absicht und ist auch unter Windows oder Linux so.
Dennoch mein Dank für den Hinweis.
