### ISSUE TITLE
Restoring optimisation in double-throw switches

### ISSUE THREAD

**Issue by DmitryVyal** [hneemann/Digital#256]
Turning off optimization for double-throw switches solved problems with simulation errors in some schemes. However, when developing models of early electronic calculators, i found that replacing real switches with unidirectional ones can greatly increase the simulation speed.
After analyzing and debugging the double-throw switches code, I found the source of modeling errors in certain circuits. When both switches is UniDirectionalSwitch and outputs of both switches are connected to the same output switches must work in a special double-throw mode (don't set output to highZ when opening). Simplest way to this is first create switches operating in the normal mode, and then check this condition and, if necessary, change the switches modes to double-throw mode.
![switch_c_v_v](https://user-images.githubusercontent.com/45413280/53683852-ffb2e600-3d16-11e9-992a-e51fe9616699.png)
![switch_v_c_c](https://user-images.githubusercontent.com/45413280/53683853-004b7c80-3d17-11e9-9eca-9b2d4183806b.png)
![switch_c_v_r](https://user-images.githubusercontent.com/45413280/53683851-ffb2e600-3d16-11e9-9e8c-ab017fbf52db.png)
[Switch_C_V_R.dig.txt](https://github.com/hneemann/Digital/files/2922218/Switch_C_V_R.dig.txt)
[Switch_C_V_V.dig.txt](https://github.com/hneemann/Digital/files/2922219/Switch_C_V_V.dig.txt)
[Switch_V_C_C.dig.txt](https://github.com/hneemann/Digital/files/2922220/Switch_V_C_C.dig.txt)
Possible implementation of switch model optimization for constant values
[PlainSwitch.diff.txt](https://github.com/hneemann/Digital/files/2922226/PlainSwitch.diff.txt)
[PlainSwitchDT.diff.txt](https://github.com/hneemann/Digital/files/2922227/PlainSwitchDT.diff.txt)

.

**Comment by hneemann** [comment]
A really nice piece of work! Thank you very much!
