### ISSUE TITLE
two instance problems

### ISSUE THREAD

**Issue by ArmBeck16** [hneemann/Digital#26]
If you open two instances, create a faulty circuit in one instance, you can't start the simulation in the other instance anymore.

**Comment by hneemann** [comment]
I'm not able to reproduce such a bug.
Can you explain in more detail what happened?
And keep in mind: If a circuit imports an other circuit, and the imported circuit doesn't work, both circuits don't start anymore.

**Comment by ArmBeck16** [comment]
>  If a circuit imports an other circuit, and the imported circuit doesn't work, both circuits don't start anymore.
Sorry, that's exactly what I did and forgot to keep in mind.

Have a nice weekend!
