### ISSUE TITLE
creating a Polygon objects from java.awt.Shape and successor

### ISSUE THREAD

**Issue by DmitryVyal** [hneemann/Digital#261]
When developing custom components, I found a convenient way to create complex-shaped polygons. One simple function allows you to convert an arbitrary graphic object java.awt.Shape to Polygon.
It becomes possible to use something like this.
**Polygon polygon = PolygonBuilder.fromShape(new RoundRectangle2F.Float(x0, y0, w, h, rx, ry));**
This feature is not critical, but it may be useful to someone else.
[PolygonBuilder.java.txt](https://github.com/hneemann/Digital/files/2975403/PolygonBuilder.java.txt)
You may find it possible to add this feature to your program.

**Comment by hneemann** [comment]
This is a nice piece of code, but adding it to Digitals sources means adding unused dead code.
