### ISSUE TITLE
Strange behavior of the Button object

### ISSUE THREAD

**Issue by DmitryVyal** [hneemann/Digital#262]
In the process of developing components for modeling the keyboard of early calculators, I discovered a strange object button behavior.
If after clicking the button to move the mouse cursor outside the button, then after releasing the mouse button the button remains pressed. This is not a serious problem, but somewhat confusing.
Most likely this is due to the lack of handling mouseExited event.

**Comment by IvyBit** [comment]
I really miss this "bug" :-(

**Comment by hneemann** [comment]
@IvyBit 
Why not using an input? A input behaves like the old buggy button.
