### ISSUE TITLE
Bidirectional pins.

### ISSUE THREAD

**Issue by Akari1982** [hneemann/Digital#27]
Is it possible to create bidirectional pins that can be used an IN pint and as OUT pins simultaneously? This is usual for data buses.

**Comment by hneemann** [comment]
By default every pin is bidirectional.
There are inputs and outputs, but this almost only effects the shape of the pin.
If you include a circuit as a subcircuit all pins are bidirectional.

**Comment by Akari1982** [comment]
Hmm. This is working in top cirquit, but if i test it in subsircuit I still get an error because input pin emits some value. Maybe posibility to set it to "not connected" state help to fix this.

**Comment by hneemann** [comment]
Enable tristate values at the input pin. Then you can set it to the tristate value, which means "not connected".

**Comment by Akari1982** [comment]
Is it possible to set pin in "not connected" state by default?

**Comment by hneemann** [comment]
This is not possible. 
But I will add that feature.

**Comment by hneemann** [comment]
@Akari1982 
I added this feature. You can checkout HEAD and try it if you like.

**Comment by Akari1982** [comment]
Thanks! You are very fast =)

**Comment by hneemann** [comment]
Only at issues that are very easy to implement. ;-)
