### ISSUE TITLE
Overlapping input and output should behave as connected

### ISSUE THREAD

**Issue by smay4finger** [hneemann/Digital#274]
When I draw an input and output overlapping, they are not connected. You explicitly need to draw a wire from input to output, which is sometimes inconvenient. Is there a possibility to implement this behaviour? In the attached screenshot the lower circuit is broken, because not connected.

![Screenshot from 2019-05-02 10-57-52](https://user-images.githubusercontent.com/1842054/57065309-51e99680-6cc9-11e9-90e6-98532a04ba37.png)

**Comment by hneemann** [comment]
I looked at it: This enhancement is surprisingly complicated to implement and adds a lot of complexity. 
I don't think it's worth the effort.

**Comment by hneemann** [comment]
I have added a simple auto wire function which creates the necessary wire automatically if a new component is inserted. Maybe this is also helpful.
Please try the latest [pre release version](https://infdigital.dhbw-mosbach.de/).

**Comment by smay4finger** [comment]
Hmm, doesn't work as expected. Tried version v0.22-59-g7bb0b24.

**Comment by smay4finger** [comment]
And something worse happened. The auto-wire functionality is breaking components with nearby pins beside each other. I inserted e.g. a seven segment LED and the two inputs got somehow connected to each other.

**Comment by hneemann** [comment]
I have fixed the "seven segment bug". Please try v0.22-64-g67bdce0.
But a wire is still required. But this wire is created automatically when two pins are spaced from each other by one grid width.

![z](https://user-images.githubusercontent.com/7190563/57316372-f1f25600-70f5-11e9-8c55-ea3f24a91094.png)

If you place two components like this, the wire is created automatically.

**Comment by smay4finger** [comment]
Ok, this auto-wire works. Still it's not possible without a wire, but if that's to complicated, so be it.
