### ISSUE TITLE
Digital is not saving settings

### ISSUE THREAD

**Issue by YulienPohl** [hneemann/Digital#275]
Hi, every time when I reopen Digital the checkboxes in the properties window are reseted 
but not the other settings like language or the library paths.
Furthermore it be would good if the window size is saved after closing.

**Comment by hneemann** [comment]
All other settings are saved, but the checkboxes in the same dialog are not?

**Comment by YulienPohl** [comment]
Yes, for example Component tree view.
This problem occurs also on my other windows machine.

**Comment by hneemann** [comment]
In your home folder is a file ".digital.cfg" stored.
Does this file change if you modify the check boxes?
Do the made changes affect this file?
The file should be saved if the settings dialog is closed.

**Comment by YulienPohl** [comment]
I have found the problem.
I had an older .digital.cfg file version in the folder which I deleted, now it saves the settings.
But the windows size is not saved as fullscreen.
