### ISSUE TITLE
can't change true table output Y name

### ISSUE THREAD

**Issue by foxzzu** [hneemann/Digital#277]
<img width="1022" alt="屏幕快照 2019-05-20 下午8 40 04" src="https://user-images.githubusercontent.com/25359389/58022693-92a63400-7b40-11e9-8d91-a5d8f0d38b71.png">
with mouse right click the output Y, no respond. The system is macOS 10.14.5

**Comment by hneemann** [comment]
Please try the pre-release built v0.22-75-g23ff923 which you can find [here](https://infdigital.dhbw-mosbach.de/).
It should be able to detect the MAC secondary click (CTRL+Left).

**Comment by foxzzu** [comment]
pre-release built v0.22-75-g23ff923, the output name can change. And, when mouse click the menu, there is no responding.
<img width="1024" alt="屏幕快照 2019-05-21 上午3 45 16" src="https://user-images.githubusercontent.com/25359389/58047520-f2b9cc00-7b7a-11e9-9c27-74d9ed4e2b84.png">

**Comment by hneemann** [comment]
Your screenshot looks really weird!
I suspect that there are files in your home folder with names similar to "Digital_2019-05-12_15-42-04.log".
If there are such files, can you please zip them and attach them to this ticket?

**Comment by hneemann** [comment]
@foxzzu 
Please try the latest pre release build v0.22-113-g25c3001. 
I've fixed some issues that could be the cause of your problems.

**Comment by hneemann** [comment]
@foxzzu 
Do not hesitate to reopen the issue if new problems arise.
