### ISSUE TITLE
Request: Counter component with asynchronous Clear

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#285]
The real counter ICs I use have async clear.  It would be useful to have the generic counter behave the same way so I can quickly add one with an arbitrary number of bits for diagnostic reasons.

I have circuits that count things and don't have a clock.

Either of a checkbox in the settings or a new component variant would work.

**Comment by hneemann** [comment]
Digital now supports custom generic circuits.
Put the attached.dig file somewhere below examples/lib to use a generic counter with async clear.

[asynCounter.dig.zip](https://github.com/hneemann/Digital/files/3409556/asynCounter.dig.zip)

**Comment by dfbg** [comment]
Nice!

thanks
