### ISSUE TITLE
+/- shortcut keys don't work in 0.22+

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#287]
The ability to increase and decrease the number of inputs via the keyboard on the basic logic components doesn't work in 0.22 or later.

Works correctly in 0.21.

**Comment by hneemann** [comment]
Are you sure! It works fine on my machine, and there is a test case for this feature, so I don't expect it not to work in an earlier version.

**Comment by dfbg** [comment]
I just tested each of them again.

It works in 0.21 and 0.22 (I don't know why it didn't earlier).
It doesn't work in 0.22-240.

**Comment by hneemann** [comment]
0.22-240 is the head of the new finishStep branch and also there it works fine on my machine.
Are you sure the canvas has the keyboard focus?

**Comment by dfbg** [comment]
It definitely has focus as I just clicked on the component to select it.  I also confirmed it with "R" and "L".

I just open a new circuit window.  select an AND gate from the menu and place it.  Click on it and press the keys.  Nothing happens.

**Comment by hneemann** [comment]
That's funny! The [+], [-] hotkeys only work, if the component is not selected.
