### ISSUE TITLE
Request: Common Anode mode for the 7-segment display

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#298]
The 7-segment display can't currently be used with a 7447 (the up-to-date swapped version).  But that's the one I'm using (actually 74247 because of 6 and 9) in real circuits because of it's voltage and current capabilities.

An active-low input mode may also be useful for the hex and alpha displays.

**Comment by hneemann** [comment]
closed in 6f8fafd0b1dd0591e40bfb424e3dd5f2e76a4f37
