### ISSUE TITLE
Sub-circuit label rendering

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#301]
The 74682 has active low outputs that are labeled "~P>Q" and "~P=Q".  These render with the overline only over the "P".  This is incorrect as a logic statement.

I've tried many variants and can't get an overline over the symbols.  "~P~=~Q" draws the overline over the P and Q but not the equals.  Closer but also not correct logically.

If there's a reason to not have ~ draw the overline over everything then perhaps something like "~[P=Q]".  Or make ~ into a toggle so "~P~=Q" would produce the current result.

**Comment by hneemann** [comment]
Try "~{P=Q}"

**Comment by dfbg** [comment]
Yeah, that works.  And now that you mention it I feel like I discovered that once before and forgot (and didn't even think to try it).  Is it in the documentation?
