### ISSUE TITLE
Simple Shape outline vs labels

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#303]
When a label in the top row has an overline it gets drawn over the outline box.  This isn't too bad on screen because it's grey over black and can be reasonably seen if not zoomed too small.  But the overline isn't visible in laser prints.

Likewise descenders and subscripts (e.g. "Q_7") on the lowest labels are drawn over the bottom line and outside the box.

**Comment by hneemann** [comment]
closed in 9e0ca16a471fe12ceda900242345599eb94a3c6d
