### ISSUE TITLE
Submitting two 74xx parts

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#305]
The 74247 and 74248.  Circuits copied from the TI datasheet.

On the real part the /RBO output pin is also the /BI input pin.  Is it possible to have a bidirectional pin like this?

[74247+74248.zip](https://github.com/hneemann/Digital/files/3491082/74247%2B74248.zip)

**Comment by hneemann** [comment]
Every pin in Digital is bidirectional. It is not possible to define a unidirectional pin.
But you have to use a NFET to create some open collector logic.

**Comment by dfbg** [comment]
Is there an example somewhere?

**Comment by hneemann** [comment]
There are some NMOS examples. But the simulated NFET works very simple. Even the body diode is missing.
