### ISSUE TITLE
Too hard to select small components

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#307]
Small components like the diodes and "Constant value" are almost impossible to select.  Even at high zoom levels there's only a few pixels that will select the component instead of starting a new wire.

**Comment by hneemann** [comment]
You are able to select small components by using CTRL+Click.

**Comment by dfbg** [comment]
OK.

When I ctrl+click on a Constant I have to click right on the wire dot.  But when I right-click I can also click on the value.  Can ctrl+click also support the expanded area?

What happens on a Mac when it has a single button?  ctrl+click is usually the right-click replacement.

**Comment by hneemann** [comment]
Digital uses two clicks, and a modifier for each click.

Windows: 

| Type         | Action |
|-------------|------------- |
| Primary click  | Left  |
| Primary click modified  | Left+CTRL |
| Secondary click  | Right  |
| Secondary click modified  | Right+CTRL |

Mac:

| Type         | Action |
|-------------|------------- |
| Primary click  | Left  |
| Primary click modified  | Left+SHIFT |
| Secondary click  | Left+CTRL  |
| Secondary click modified  | Left+CTRL+SHIFT |

To select a small component you have to use the "Primary click modified".

**Comment by dfbg** [comment]
That makes sense.  I don't think I've ever had to use/contemplate the ctrl-click model.  I possibly had a two button mouse before the context menu was a system feature.

**Comment by hneemann** [comment]
It is possible to enable the Windows mouse mode on a Mac, if a two button Mouse is available.
Maybe that is an option.

**Comment by dfbg** [comment]
Yes, I've had that enabled ever since it became an option.  I was just wondering about the one button mouse model - not suffering from it ;-)
