### ISSUE TITLE
Undo sometimes undoes multiple steps

### ISSUE THREAD

**Issue by keller91711** [hneemann/Digital#314]
I'm not sure of the exact circumstances, but I think it has to do with editing text, such as labels. Sometimes after an UnDo, I find that multiple recent actions have been undone and I have to go reconstruct several steps. I'll try to identify the context more clearly.

**Comment by hneemann** [comment]
Please look at your home folder: There may be files named "Digital_[time stamp].log".
Please zip these files and attach them to this issue.

**Comment by keller91711** [comment]
[Archive.zip](https://github.com/hneemann/Digital/files/3526934/Archive.zip)
Per your request.

**Comment by hneemann** [comment]
closed in 989b47aba54e9ec3572cd0b03b17b3c2d600534d
