### ISSUE TITLE
Suggestion: Drag on empty background when editing should move the whole circuit, just as it does during simulation.

### ISSUE THREAD

**Issue by keller91711** [hneemann/Digital#316]

**Comment by keller91711** [comment]
In other words, one should not have to control-drag in one situation but not the other. Since drag on an empty background currently has no effect during editing, it should be simple to make the behavior uniform for both modes.

**Comment by hneemann** [comment]
Up to now a simple drag shows the select rectangle. Because the select makes no sense during simulation, a simple drag acts like control-drag in this case. 
The intended way is to use control-drag to move the circuit, which works in both, simulation and editing mode.

**Comment by keller91711** [comment]
Yes, I see. I was thinking of drag when not around a component, but I agree that it doesn't make sense. 

So I withdraw this.
