### ISSUE TITLE
Digital.jar file is missing

### ISSUE THREAD

**Issue by sunriax** [hneemann/Digital#321]
After i cloned the repository, there is no Digital.jar file in the distribution directory? I really don´t know if this is an issue, i tried Digital for the first time. Greets G.Raf

**Comment by hneemann** [comment]
When you clone the repo, you get the source code. 
You have to build it with maven to get the jar file.
It is much easier to download the [distribution](https://github.com/hneemann/Digital/releases/latest) directly. Simply unzip the file Digital.zip

**Comment by hneemann** [comment]
See also #137
