### ISSUE TITLE
Larger marking of errors in drawing

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#323]
I by accident created a short orphan wire segment on the schematics and of course got an error when I tried to run the simulation.  The wire was hidden in a text field and took me a really long time to find even if it was highlighted in red.

Maybe  it could be possible to draw a larger red circle around the highlighted offending item  so it can be found easier?

<img width="1477" alt="Screen Shot 2019-09-05 at 10 04 01 PM" src="https://user-images.githubusercontent.com/325326/64376965-c3e03c80-d029-11e9-8fda-fc851024663b.png">

**Comment by SmallRoomLabs** [comment]
Cool!  It works just fine - it's now so much easier to find the problem in a larger schematics.

**Comment by SmallRoomLabs** [comment]
Seems like I spoke too soon ;-(

**Comment by SmallRoomLabs** [comment]
Hehe...  Going back to the "real" released version is apparently not an option ^__^. Not as long as I have newer stuff in the .dig file.

Will try with the previous pre-release - I guess that should work.

<img width="629" alt="Screen Shot 2019-09-06 at 7 50 08 PM" src="https://user-images.githubusercontent.com/325326/64449356-f5b3da80-d0df-11e9-9adc-07ac8b706ef0.png">

**Comment by hneemann** [comment]
Yes, I am very worried about not breaking an old *.dig file when using a new Digital version.
But of course opening a new file with an older Digital version usually doesn't work.
