### ISSUE TITLE
Unnecessary circling of objects while editing

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#325]
Commit e01e100ae618d8d772d785a1f24855133eb54153 for #323 that circles small error objects unfortunately also applies when selecting items or drawing new wires while zoomed out. This makes it look quite messy.

Selecting:
<img width="316" alt="Screen Shot 2019-09-06 at 7 25 34 PM" src="https://user-images.githubusercontent.com/325326/64447792-7670d780-d0dc-11e9-9c07-9428d1bf7007.png">

Drawing new wire:
<img width="493" alt="Screen Shot 2019-09-06 at 7 24 28 PM" src="https://user-images.githubusercontent.com/325326/64447793-7670d780-d0dc-11e9-9a6f-aa3dc684bb41.png">

**Comment by hneemann** [comment]
That looks really terrible! :-(

**Comment by SmallRoomLabs** [comment]
This is still happening in v0.23-52-g26459e1

<img width="193" alt="Screen Shot 2019-09-06 at 9 15 57 PM" src="https://user-images.githubusercontent.com/325326/64454715-f2265080-d0eb-11e9-8d98-47911371ed6c.png">

**Comment by hneemann** [comment]
I have created the CTRL branch before i fixed this issue. So v0.23-52-g26459e1 does not contain the fix.
