### ISSUE TITLE
Attaching a wire "from behind"

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#326]
If I have a circuit like the first AND below and want to add an LED to the output like in the second then it seems like the NOT gate gets disconnected  from the AND and the wire goes straight from the LED to the NOT.

To work around that issue I can connect the wire from the LED from the top or bottom into the output of the AND.

Is this "disconnect from output"-behavior intended or is it a bug?

(To be 100% clear - in the second example I first wire up the NOT to the AND, then I wire up the LED to the AND in a separate step. I don't just make one wire that just passes by the AND output)

<img width="663" alt="Screen Shot 2019-09-07 at 3 17 18 PM" src="https://user-images.githubusercontent.com/325326/64475397-ad99c400-d182-11e9-9995-90648a8e64ea.png">

**Comment by hneemann** [comment]
This behavior is intended. A connection is only established to an end of a wire.
But it's possible to connect multiple components to the same wire endpoint.

![z](https://user-images.githubusercontent.com/7190563/64477308-353efd00-d19a-11e9-8521-94ab456ea586.png)

**Comment by SmallRoomLabs** [comment]
Ah, that makes sense.  So two horizontal wire segments that are joined becomes *one* segment, and thus loses its middle endpoint.

Having the LED directly at the endpoint as in your example definitely looks better than my crooked wire.  I'll change my design to do it that way.
