### ISSUE TITLE
Bookmarks for screen position

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#335]
You know what would save (at least) me a ton of time while debugging my design?

Bookmarks.  Being able to press like shift-control-1 to capture the current scrollbar-locations and the zoom level into the first bookmark-slot.  And then just press control-1 to instantly recall that position.  Maybe up to 9 slots.

That would be an awesome timesaver for me. As is it now I feel I'm spending more time scrolling and zooming into 2-3 different places than doing anything else while debugging. Lookin at my front panel, heading over to the main datapaths for the cpu, and then up to the controller logic to see current microcode step and exactly which control signals begin asserted now and what will happen in the next step - and then back down to the datapaths again to verify.

**Comment by hneemann** [comment]
That might be a good idea. To be honest, I never work with circuits that big. I tend to break them down into smaller partial circuits, which keeps the circuits small.
I will think about it.

**Comment by hneemann** [comment]
Now its possible to store a view position with CTRL+[n] (COMMAND+[n] on MacOS) and to restore the position with [n].

**Comment by SmallRoomLabs** [comment]
Holy cr*p!  You are fast!  I'll try it out straight away...

**Comment by SmallRoomLabs** [comment]
The setting and recalling of the bookmarked positions works fine.  But they seem to not be saved in the .dig file so they need to be setup for each load.

**Comment by SmallRoomLabs** [comment]
Ollrighty!  Now it is perfect...  A definite time-saver!   Thanks.

**Comment by SmallRoomLabs** [comment]
Hmm... It seems like I spoke too soon again. ;-)

Zooming affects the current recalled favorite and gets auto-stored in it.

**Comment by SmallRoomLabs** [comment]
Okkidokie, I'll give it a spin and see!

BTW, a link in the main README.md to the pre-release download server would be nice. It takes me a while to find it every time I want to download from there.,,,,

**Comment by SmallRoomLabs** [comment]
After a few evenings of using Digital I can confirm that this  bookmark/favorite function actuallys saves me a ton of time.  In the design I'm doing now I have 5 different bookmarks that I flip around to both while debugging/running and (to some extent) while drawing.
