### ISSUE TITLE
Octal RAM/ROM/EEPROM views?

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#336]
I know that is a very niche request that only a few will ever have use for, but I would have great use for an octal memory view instead of the standard hex views on the memories. (For both the addresses and the data)

Admittedly it gives me a lot of practice converting address 0x0B9 into octal 0271 and then the data there 0x236 into octal 01066 - in a few weeks I might be able to do it in my head without using a converting calculator ;-)

**Comment by hneemann** [comment]
When you think about it, it's not such a niche application. In my lectures, for example, a binary display would sometimes be helpful.

Closed in 8e7239234be821a59285fdca5495723b2557e9a2
