### ISSUE TITLE
Wire splitter issue

### ISSUE THREAD

**Issue by kierangilliam** [hneemann/Digital#337]
I am finding that I am running into this same issue across Digital. 

"Error creating the circuit. No output connected to wire... The state of the wire is undefined."

The wire splitter output is connected directly to the a circuit's inputs but that does not register.

<img width="802" alt="Screen Shot 2019-09-19 at 5 58 43 PM" src="https://user-images.githubusercontent.com/18583882/65291241-44616b80-db07-11e9-9182-b19e984de005.png">
<img width="813" alt="Screen Shot 2019-09-19 at 5 59 11 PM" src="https://user-images.githubusercontent.com/18583882/65291242-44fa0200-db07-11e9-9961-9623c5e0aefc.png">
<img width="759" alt="Screen Shot 2019-09-19 at 5 59 22 PM" src="https://user-images.githubusercontent.com/18583882/65291243-44fa0200-db07-11e9-9f52-b1ca2ebffca6.png">

**Comment by kierangilliam** [comment]
Adding another example.

<img width="743" alt="Screen Shot 2019-09-19 at 6 17 58 PM" src="https://user-images.githubusercontent.com/18583882/65291823-d9656400-db09-11e9-88c3-03c5e813bdbe.png">

**Comment by Usama148-hub** [comment]
same error I am facing

**Comment by hneemann** [comment]
@Usama148-hub 
Digital splitters are directional. It could be that you are using the splitter in the wrong direction.

**Comment by prlaba** [comment]
Splitters are cool!  But they could probably use better explanations in your User Guide.

Explaining more fully how the Fanout attribute works, with examples, would also be helpful.  When set up correctly, you only have to expose the signals you want, without having a bunch of unconnected leads coming out of or into a splitter.
