### ISSUE TITLE
Unnamed tunnels

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#338]
I'm not sure if I consider this a bug, annoyance or a good thing....   But it seems like all unnamed tunnels indeed are connected to each other just as if they had a proper name.

This might be good for discovering if one missed applying a name to a tunnel by mistake. But on the other hand I like to to like this...

<img width="303" alt="Screen Shot 2019-09-20 at 9 38 27 AM" src="https://user-images.githubusercontent.com/325326/65308666-d9597880-db8a-11e9-9a8b-a20f8c114621.png">
 
... when I know that I'll soon use all (or most) of the outputs anyways.  

For that it'd be better to just have the software silently ignore unnamed tunnels - as it is now the simulation halts as soon as one of the  tunnels have a state different from the others.

BTW - I really like that an underscore in a name, like IOT_CAF above, makes the CAF-part subscripted.

**Comment by hneemann** [comment]
To be honest, I never thought about what to do with unnamed tunnels. At the moment they simply have the name "" (empty string)

> For that it'd be better to just have the software silently ignore unnamed tunnels - as it is now the simulation halts as soon as one of the tunnels have a state different from the others.

I like the idea of silently ignoring unnamed tunnels. Hmm!
