### ISSUE TITLE
How do i load data into a ROM from a .bin file

### ISSUE THREAD

**Issue by mitolegy** [hneemann/Digital#339]
how do I get data from a .bin file into the ROM component? its 8k of data so im not super keen on transferring it by hand. ive tried to just copy-paste it but it won't let me just paste over multiple address spaces in the data editor. (which seems like a major oversight)

**Comment by SmallRoomLabs** [comment]
In the hexdump you get when pressing the Edit-button you have a (that's actually hard to find) File-menu at the top. Like this:

<img width="560" alt="Screen Shot 2019-09-20 at 4 49 14 PM" src="https://user-images.githubusercontent.com/325326/65336555-df6d4a80-dbc6-11e9-99af-9bc3fbffd772.png">
