### ISSUE TITLE
How to change the width of a DIP?

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#340]
The pre-made 74x-series DIPs are wide and nice so the labels are clearly visible inside.  But when I tried to make a 74393 chip it resulted in a narrow DIP with unreadable pin designators.

<img width="494" alt="Screen Shot 2019-09-20 at 4 44 36 PM" src="https://user-images.githubusercontent.com/325326/65336829-59053880-dbc7-11e9-8d19-eef1859d02e0.png">

**Comment by hneemann** [comment]
In the settings of the circuit there is a field "Width".
You can set this to "5".

**Comment by SmallRoomLabs** [comment]
Ohh... That was easy.  And actually rather logical when thinking about it. "Circuit specific settings" 

Thanks.
