### ISSUE TITLE
Logging of measurements values?

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#346]
I seem to recall that I've read about that it is possible to get a log or export the measurements to a file. But I can't find it.  Did I just dream that it was possible?

**Comment by hneemann** [comment]
The window that displays the data has a "File" menu that allows you to save the data in a CSV file.

**Comment by SmallRoomLabs** [comment]
Yes, that was what I hoped for, but I have a "memory" as the menu entry there that leads to the contents of my eeprom.

<img width="604" alt="Screen Shot 2019-09-26 at 5 39 19 PM" src="https://user-images.githubusercontent.com/325326/65703192-a2043380-e084-11e9-9db5-f48603fd7eb6.png">

**Comment by hneemann** [comment]
This screenshot shows the measurement table. The table shows only the current state of the model. Only the measurement graph is able to record the values over time.
But this may be a misunderstanding: Do you want to save the current state or the evolution over time?

**Comment by SmallRoomLabs** [comment]
Oh, I see...   I though the graph was only a graph and nothing more. And the table here was data in tabular format (where I'd expect a CVS export to be).

What I'm looking for is to be able to log the state of multiple counters and wires at every tick of the clock component.  Some of the original (1960's) diagnostics tests fails after 10 minutes of run time in my simulation. And it would be great to be able to go back the last few hundred steps in the log and see exactly what the cause was.   

In my current bug it's happening at about 1.4 million executed instructions, where each instruction have several internal steps (hardcoded microcode).  So I probably need to store 15-20 million rows of data before saving.  
 
The diagnostics have source code available, but are self-modifying and relocates itself around during runtime and and quite hard to try to pinpoint the cause, especially if one have to wait 10 minutes for the simulation to reach the same point again.

**Comment by hneemann** [comment]
Open the measurement graph while the simulation is running (second menu entry in the simulation menu). This graph stores the history of the last 500 clock cycles to avoid a memory overflow if the simulation runs a long time. This means if the simulation stops, 1000 values in the past are available.
Unfortunately, this value is hard coded.
If this number is not enough, the code must be modified. But you can easily do it yourself: In the class `de/neemann/digital/gui/components/data/GraphDialog.java` you can adjust the constant `MAX_SAMPLE_SIZE`.

**Comment by SmallRoomLabs** [comment]
Ok, then I'll jack that number up a bit and try.  I'll also have to utilize the Break-component to stop the clock from ticking after the simulation encounters a HLT instruction, as it is now I just clear my run/stop flip-flop and let the clock tick away.

I might also disable the scrolling graphics in the measurement window - there's no need to waste cpu cycles on that for me.

Great!  I'll play around with it a bit and see how it turns out.   Thanks.

**Comment by hneemann** [comment]
> I might also disable the scrolling graphics in the measurement window - there's no need to waste cpu cycles on that for me.

The GUI is handled in a different thread, so I don't expect that disabling the GUI update will improve the speed much unless you are using a single core cpu.

**Comment by SmallRoomLabs** [comment]
Nice, Then I'll leave the GUI there. I mainly develop on an old MacbookPro from 2013. It's good enough for me as it is.  So I got two cores there...

So that is why I didn't get any noticeable change in speed when I deleted all eye-candy (hundreds of LEDs and 50 seven seg displays) from my simulation.

**Comment by SmallRoomLabs** [comment]
Oh, it seems like I can't use the Break-component. It inhibits any usage of buttons while running. And it also can't have any Clock-components running.  And it have this "auto-kill" feature permanently activated.

I had hoped that it would just simply stop any Clocks when triggered - and everything else would work as usual.

**Comment by hneemann** [comment]
This is an open issue. See #83 
Up to now you can't interact with the model during the run-to-break phase.

**Comment by hneemann** [comment]
When I think about it, I can give advice on how to overcome this problem: You can create a shortcut in the circuit, triggered by a specific signal. This will stop the simulation, but the recorded data will be preserved, allowing you to save the data:

![z](https://user-images.githubusercontent.com/7190563/65744289-35c31780-e0f8-11e9-9314-5d4c6d4779f2.png)

It's more of a dirty hack, but it maybe helpfull.

**Comment by SmallRoomLabs** [comment]
That is a good enough solution for me.  Kick the simulations were it really hurts so it stops running ;-)

Good thing that it preserves the logs at a event like that....

**Comment by SmallRoomLabs** [comment]
I've tested this and it works just fine.  Thanks for the tip.
