### ISSUE TITLE
JAR File

### ISSUE THREAD

**Issue by vcokltfre** [hneemann/Digital#347]
This may be me being stupid but I can't find the JAR file to start (Linux) , and when I downloaded it on Windows the EXE couldn't find it either.

**Comment by SmallRoomLabs** [comment]
Download the Digital.zip from the "Releases page".  There you have the proper exe's, jars and scripts in the root folder of the zip.

<img width="580" alt="Screen Shot 2019-09-26 at 6 59 22 PM" src="https://user-images.githubusercontent.com/325326/65709004-1db7ad80-e090-11e9-9897-e3515e43a7b4.png">

**Comment by SmallRoomLabs** [comment]
https://github.com/hneemann/Digital/releases

**Comment by hneemann** [comment]
@vcokltfre 
The git repository does not contain the JAR file. It only contains the source code.
To get a executeable jar file you have to download a [release](https://github.com/hneemann/Digital/releases/latest) as pointed out by SmallRoomLabs or you have to build the binary yourself from the sources.

**Comment by hneemann** [comment]
See also #321
