### ISSUE TITLE
Just an observation on the GUI

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#350]
While running a long diagnostics run on my cpu-design the screen goes low-res. Moving around to different locations in the design (while still running) doesn't make it hi-res and pretty again. 

Not until I stop the sim (and I think I have to scroll as well) does the screen go hi-res again.

This is not a problem at all, but it is a kinda funny effect.

**How it normally looks / hi-res:**

<img width="328" alt="Screen Shot 2019-09-28 at 9 26 02 AM" src="https://user-images.githubusercontent.com/325326/65813245-f289a700-e1d2-11e9-9812-7c31b46c9b7d.png">

**How it looks after 10 minutes running / lo-res:**

<img width="324" alt="Screen Shot 2019-09-28 at 9 22 00 AM" src="https://user-images.githubusercontent.com/325326/65813246-f289a700-e1d2-11e9-80f0-efe92ea50891.png">

**Comment by hneemann** [comment]
This behaviour is intended. If the screen refresh takes too long (longer than 500ms) "anti alias" will be switched off to keep the surface reactive. If the first time the screen refresh time is less than 50ms, "anti alias" will be turned on again.

**Comment by SmallRoomLabs** [comment]
Good to know it's not some strange artifact caused by bad video drivers or something like that...
