### ISSUE TITLE
Auto-generate test data from current design?

### ISSUE THREAD

**Issue by SmallRoomLabs** [hneemann/Digital#351]
A part of my design is a big mess of combinatorial logic with a lot of gates with inverted logic and so. As I sat down to try to clean it up a bit and make it more "actually buildable" it occurred to me that it might be good to learn how to use your little green test-box.

After copying my messy part into a separate drawing and attaching proper input- and output-boxes to the relevant points I could use F9 to get a truth-table and a bunch of equations but it seems like I can't copy or save the truth table into a format that the test-box can accept.  Nor can the test-box autogenerate the tests from the current design.

Would it not be incredibly convenient to have the Analyze and Test compatible with eachother so I don't have to write a 10-input 4-output testcase data file by hand?  ^__^

**Comment by hneemann** [comment]
I'm not sure!
The genereted test would not be a test case, because it would always be green.
It wouldn't test if the circuit works the way it should, but just that it is the way it is.
And if you want to create an elegant circuit, you can simply auto create a clean circuit from the truth table.

**Comment by SmallRoomLabs** [comment]
That is true. It would be more of a reference-case.  Still, it could be useful to be able to export the truth-table in a cvs and/or textual format.

But I'm not sure I would call the autogenerated circuit elegnt. ;-)  From an aestetics point of view the autogenerated are beautiful in a mechanical and strict way.

But compare these two.  One conveys the workings of the design more than the other.  That is beautiful to me...

<img width="926" alt="Screen Shot 2019-09-28 at 3 00 28 PM" src="https://user-images.githubusercontent.com/325326/65816829-ed435100-e200-11e9-9440-e0df4f8777a1.png">
<img width="315" alt="Screen Shot 2019-09-28 at 2 55 26 PM" src="https://user-images.githubusercontent.com/325326/65816830-ed435100-e200-11e9-8f48-ff7796cf4fc1.png">

**Comment by hneemann** [comment]
It was so easy. No reason not to implement it.

**Comment by SmallRoomLabs** [comment]
Heh....  I like when the enhancements are easy to implement ;-)

**Comment by SmallRoomLabs** [comment]
I found a small problem.  

When Analyzing a circuit with multi-bit inputs or outputs the truth table appends a _0 , _1 and so on onto the name of the input/output.  But the Tester is not happy with those names.  I guess multibitters should be entered as the base-name with a value varying from 0 to 2^n in the Tester.

It's easy enough to just split up the multibitters to singlets manually and then analyze, so it's not really a big deal.

**Comment by kEviN1H** [comment]
> That is true. It would be more of a reference-case. Still, it could be useful to be able to export the truth-table in a cvs and/or textual format.
> 
> But I'm not sure I would call the autogenerated circuit elegnt. ;-) From an aestetics point of view the autogenerated are beautiful in a mechanical and strict way.
> 
> But compare these two. One conveys the workings of the design more than the other. That is beautiful to me...
> 
> <img alt="Screen Shot 2019-09-28 at 3 00 28 PM" width="926" src="https://user-images.githubusercontent.com/325326/65816829-ed435100-e200-11e9-9440-e0df4f8777a1.png">
> 
> <img alt="Screen Shot 2019-09-28 at 2 55 26 PM" width="315" src="https://user-images.githubusercontent.com/325326/65816830-ed435100-e200-11e9-8f48-ff7796cf4fc1.png">

howto export  the truth-table to a cvs and/or textual format

**Comment by hneemann** [comment]
@kEviN1H 
Use the latest [pre release](https://infdigital.dhbw-mosbach.de/). In the table window, use _File->Export Test Case_ or _File->Export LaTeX_ to copy a textual representation to the clipboard.
_File->Export to Hex_ exports the result columns to a simple hex file representation which can be imported into a ROM to create a look-up-table in a circuit.

**Comment by kEviN1H** [comment]
OK, Thanks a lot!!!!
