### ISSUE TITLE
Running on Mac OS X

### ISSUE THREAD

**Issue by John-Lluch** [hneemann/Digital#352]
Hi.

Is there a way to run Digital in Mac OS X ?.

I downloaded the entire repository, but I can't figure out a way that works for me. Any help would be appreciated.

Thanks.

John

**Comment by John-Lluch** [comment]
Oh, I figured it out. I had to download it from the "Download" link on the ReadMe file, instead of downloading the repo. It now works fine!

**Comment by hneemann** [comment]
See also #347
