### ISSUE TITLE
Add Flip as an attribute alongside Rotate.

### ISSUE THREAD

**Issue by exfinium** [hneemann/Digital#365]
I would like the option to flip/mirror components that lack a line of symmetry (e.g. FETs and Splitters).  I see that this has already been done for Drivers as a special case.

Instead of modifying specific asymmetric components, maybe it would be easier and better to duplicate/extend the rotate attribute and have flip be an option wherever rotate is.

**Comment by hneemann** [comment]
See also #187, and https://github.com/hneemann/Digital/issues/172#issuecomment-405820540

Maybe I should think about it again.
