### ISSUE TITLE
Feature request: start tutorial from menu

### ISSUE THREAD

**Issue by jsegarraf** [hneemann/Digital#366]
As far as I know, the tutorial cannot be started again if it has been completed. For students working on the same computer at different times, this means that only the first one will see the tutorial.

It would be perfect if the tutorial could be started again from the gui, for instance from the View menu.

Currently, the only option I see to restart the tutorial is to remove the configuration file .digital.cfg in Linux (I don't know the file names and locations in other systems), but it is not a good approach.

**Comment by hneemann** [comment]
Please try the latest [pre release build](https://infdigital.dhbw-mosbach.de/).

**Comment by jsegarraf** [comment]
Works perfectly.
Thank you very much
