### ISSUE TITLE
Logic pin labels or floating text

### ISSUE THREAD

**Issue by abondis** [hneemann/Digital#367]
Is there a way to make the text floating without snapping to the grid ?
Or is there a way to put label on simple logic gates such as AND, OR ... ?
Thanks.

**Comment by hneemann** [comment]
Neither is currently possible.

**Comment by hneemann** [comment]
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/) which allows to disable "snap to grid" in the text component and in the rectangle component.

**Comment by abondis** [comment]
that was fast ! thanks a lot, I'm going to try it today.
