### ISSUE TITLE
Why does the input of the combinatorial circuit affect the clock shape in measurement tool?

### ISSUE THREAD

**Issue by itviewer** [hneemann/Digital#368]
Here is a simple circuit, I want to take a look at the timing diagram for signal a and b under clock c.
The clock is set as real time clock with 1Hz.
![test](https://user-images.githubusercontent.com/1397840/67839772-651dd780-fb2f-11e9-9937-0fbf0b59f479.png)

after start the simulation, then "Show measurement graph", then set a or b signal at some time point,  However, the clock signal shape also changed automatically.
![test2](https://user-images.githubusercontent.com/1397840/67840948-f42bef00-fb31-11e9-88ee-435475dfb246.png)

Is it possible to add a separate clock signal that is unaffected by the input? After all, this is more realistic

[test.zip](https://github.com/hneemann/Digital/files/3787647/test.zip)

**Comment by hneemann** [comment]
Please see #359.
The x-axis does not show the time. It shows a kind of modification counter.
