### ISSUE TITLE
Can the Text element display none English font?

### ISSUE THREAD

**Issue by itviewer** [hneemann/Digital#369]
I want to add some comments to the circuit, but the Text element does not support displaying Chinese fonts.

**Comment by hneemann** [comment]
Yes it can. But Java supports by default only code points below U+FFFF. 
Here are some CJK Unified Ideographs above U+4E00 on my machine:

![ScreenShot](https://user-images.githubusercontent.com/7190563/67896131-0753b480-fb5c-11e9-86ac-353a55d4ecad.png)

**Comment by itviewer** [comment]
Does the application will  set the appropriate font automatically? I tried  some methods, but my font still shows as a box.
![深度截图_选择区域_20191031113350](https://user-images.githubusercontent.com/1397840/67916942-589e8b00-fbd2-11e9-90fd-19e5d083be2b.png)
Then I tried to hard code the font setting  in file src/main/java/de/neemann/digital/draw/graphics/Style.java line 170 from
`        font = new Font("Arial", fontStyle, fontSize);
`
to
`        font = new Font("SimSun", fontStyle, fontSize);
`
"SimSun"  is the font I need for Chinese language. After that, the font can be displayed normally.

![深度截图_选择区域_20191031114601](https://user-images.githubusercontent.com/1397840/67917453-08c0c380-fbd4-11e9-9664-3f2f640e16f7.png)

Can it be achieved without hard coding?

**Comment by hneemann** [comment]
I have not changed any code at all to create the screenshot above.
But maybe it is OS or JRE/JDK dependent. I have used Debian with OpenJDK 11 installed.
To me it seems like a Java/JRE/JDK configuration problem, and not a bug in Digitals source code.
There are several web sites out there that deal with this problem. 
But i can not figure out myself what the problem is, because on my system it works out of the box without any problems.
Could you please attach the circuit above containing the Chinese text? That would enable me to do a few more experiments.

**Comment by hneemann** [comment]
Also a more complex text is working on my machine out of the box (created with the google translator):
![ScreenShot2](https://user-images.githubusercontent.com/7190563/67931555-6815d800-fbc2-11e9-80ff-b8647e524f9e.png)

**Comment by itviewer** [comment]
I think the problem should be Java's own support for CJK fonts. I use Ubuntu with openjdk-8.  
My Google solution is to put the font in the `jre/lib/fonts/fallback` directory, but it doesn't work 
 for me.
Maybe JDK 11 should be friendly to CJK fonts. I will to try it later, thanks.

**Comment by hneemann** [comment]
Today I played around a little on a Windows computer. The CJK fonts didn't work there either. 
I coulf fix the problem by replacing the line you mentioned above from
```
font = new Font("Arial", fontStyle, fontSize);
```
to
```
font = new Font(null, fontStyle, fontSize);
```
Could you please try if that works for you?
