### ISSUE TITLE
Multiplexer has only one select input even if you select 2,3 or more

### ISSUE THREAD

**Issue by frankeggink** [hneemann/Digital#371]
version: v0.23

**Comment by hneemann** [comment]
The multiplexer has a multi-bit bus input if more than one selection bit is chosen.
If you want to use multiple one bit connections instead, you have to add a splitter like this:

![z](https://user-images.githubusercontent.com/7190563/68090171-e7c8ce80-fe70-11e9-9e90-e51e13530829.png)

**Comment by frankeggink** [comment]
Thanks, that fixes my problem.
