### ISSUE TITLE
Generic Examples not included in v0.23 release

### ISSUE THREAD

**Issue by AntiBlueQuirk** [hneemann/Digital#376]
The generic examples listed in the v0.23 documentation, which should be located at `examples/generic`, are not actually present in the v0.23 release zip.

 - These files appear in the source tree at `src/main/dig/examples/generic`, but don't seem to have made it into the release zip.
 - Conversely, there is a folder in the release zip `examples/fsm`, which does not appear in the source tree.

It wasn't hard to obtain the files once I figured out where to find them, it just seems odd to me that they were not included in the release zip. The presence of the `fsm` folder is also odd; it seems that the `examples` folder does not actually have a 1:1 representation in the source tree.

**Comment by hneemann** [comment]
You are right: The examples folder is generated by an assembly file. 
There is no representation of the examples folder in the source tree.
The latest [pre-release](https://infdigital.dhbw-mosbach.de/) build contains the correct folders and files.
