### ISSUE TITLE
Changing numeration of cells in Karnaugh Maps 3 vars and 4 var

### ISSUE THREAD

**Issue by helderdaniel** [hneemann/Digital#382]
Hi,

I used Logisim for some time and found Digital sometime ago.
Great work on Digital and it is getting better every day :)

However, I miss the numbering of kmaps cells as Logisim does:

![image](https://user-images.githubusercontent.com/31565045/69037088-1604ed00-09df-11ea-9b90-8b4dfce9772b.png)

![image](https://user-images.githubusercontent.com/31565045/69037174-477db880-09df-11ea-933c-977818414e35.png)

I am used to numbering kmaps cells like this.
I found that Digital uses another order (tried with last version: Nov 16, 2019, ce4ed8f):

![image](https://user-images.githubusercontent.com/31565045/69037401-bce98900-09df-11ea-80ed-cceeee62a627.png)

![image](https://user-images.githubusercontent.com/31565045/69037438-cd016880-09df-11ea-9625-1aca800fc14a.png)

So I cloned the repo, changed the code in the file: KarnaughMap.java to number as I like (complete changed file attached, had to change the extension to *.txt to upload).

I just changed the order of the inverted variables as shown below and compiled with: `mvn install`

```
//(...)
case 3:
                for (int row = 0; row < 2; row++)
                    for (int col = 0; col < 4; col++)
                        cells.add(new Cell(row, col));
                addToRow(0, 4, 0, true);
                addToRow(1, 4, 0, false);
                addToCol(0, 2, 1, true);
                addToCol(1, 2, 1, true);
                addToCol(2, 2, 1, false);
                addToCol(3, 2, 1, false);
                /*
                addToCol(0, 2, 2, false);
                addToCol(1, 2, 2, true);
                addToCol(2, 2, 2, true);
                addToCol(3, 2, 2, false);
                */
                addToCol(0, 2, 2, true);
                addToCol(1, 2, 2, false);
                addToCol(2, 2, 2, false);
                addToCol(3, 2, 2, true);

                headerLeft = new Header(0, true, false);
                headerTop = new Header(1, true, true, false, false);
                //headerBottom = new Header(2, false, true, true, false);
                headerBottom = new Header(2, true, false, false, true);
                headerRight = null;
                break;
            case 4:
                for (int row = 0; row < 4; row++)
                    for (int col = 0; col < 4; col++)
                        cells.add(new Cell(row, col));

                addToRow(0, 4, 0, true);
                addToRow(1, 4, 0, true);
                addToRow(2, 4, 0, false);
                addToRow(3, 4, 0, false);
                /*
                addToRow(0, 4, 1, false);
                addToRow(1, 4, 1, true);
                addToRow(2, 4, 1, true);
                addToRow(3, 4, 1, false);
                */
                addToRow(0, 4, 1, true);
                addToRow(1, 4, 1, false);
                addToRow(2, 4, 1, false);
                addToRow(3, 4, 1, true);

                addToCol(0, 4, 2, true);
                addToCol(1, 4, 2, true);
                addToCol(2, 4, 2, false);
                addToCol(3, 4, 2, false);
                /*
                addToCol(0, 4, 3, false);
                addToCol(1, 4, 3, true);
                addToCol(2, 4, 3, true);
                addToCol(3, 4, 3, false);
                */
                addToCol(0, 4, 3, true);
                addToCol(1, 4, 3, false);
                addToCol(2, 4, 3, false);
                addToCol(3, 4, 3, true);

                headerLeft = new Header(0, true, true, false, false);
                //headerRight = new Header(1, false, true, true, false);
                headerRight = new Header(1, true, false, false, true);
                headerTop = new Header(2, true, true, false, false);
                //headerBottom = new Header(3, false, true, true, false);
                headerBottom = new Header(3, true, false, false, true);
                break;
//(...)
```

However I had to disable one of the tests in the file: KarnaughMapTest.java (full changed file attached),

`public void testBUG_1()`

so that it passes all tests. (Changing just the code to reorder vars in 3 vars kmaps does not trigger this testBUG_1 error).

```
//(...)
   // in 4x4 map a 8 cell block is drawn in wrong orientation
    public void testBUG_1() throws IOException, ParseException, KarnaughException {
/*    Expression exp = new Variable("D");
        KarnaughMap c = new KarnaughMap(Variable.vars(4), exp);

        assertEquals(1, c.size());

        KarnaughMap.Cover co = c.iterator().next();
        assertTrue(co.isDisconnected());
        assertFalse(co.onlyEdges());
        assertTrue(co.isVerticalDivided());

        exp = new Variable("B");
        c = new KarnaughMap(Variable.vars(4), exp);

        assertEquals(1, c.size());

        co = c.iterator().next();
        assertTrue(co.isDisconnected());
        assertFalse(co.onlyEdges());
        assertFalse(co.isVerticalDivided());
*/

//(...)
```

I am running the 2 versions, and as far as I test them the changed version seems to work as the original.
It creates the 3 and 4 vars kmaps with the reordered variables and simplifies the expression as expected.

However, I am concerned with that disabled unit test.
I did not get what the comment on that test means:

>    // in 4x4 map a 8 cell block is drawn in wrong orientation

Can you tell me if the original order of variables in Digital kmaps is really needed for proper operation?

thanks,

Helder

[KarnaughMap.java.txt](https://github.com/hneemann/Digital/files/3857649/KarnaughMap.java.txt)
[KarnaughMapTest.java.txt](https://github.com/hneemann/Digital/files/3857660/KarnaughMapTest.java.txt)

**Comment by helderdaniel** [comment]
Hi,

I used Logisim for some time and found Digital sometime ago.
Great work on Digital and it is getting better every day :)

However, I miss the numbering of kmaps cells as Logisim does:

![image](https://user-images.githubusercontent.com/31565045/69037088-1604ed00-09df-11ea-9b90-8b4dfce9772b.png)

![image](https://user-images.githubusercontent.com/31565045/69037174-477db880-09df-11ea-933c-977818414e35.png)

I am used to numbering kmaps cells like this.
I found that Digital uses another order (tried with last version: Nov 16, 2019, ce4ed8f):

![image](https://user-images.githubusercontent.com/31565045/69037401-bce98900-09df-11ea-80ed-cceeee62a627.png)

![image](https://user-images.githubusercontent.com/31565045/69037438-cd016880-09df-11ea-9625-1aca800fc14a.png)


So I cloned the repo, changed the code in the file: KarnaughMap.java to number as I like (complete changed file attached, had to change the extension to *.txt to upload).

I just changed the order of the inverted variables as shown below and compiled with: `mvn install`

```
//(...)
case 3:
                for (int row = 0; row < 2; row++)
                    for (int col = 0; col < 4; col++)
                        cells.add(new Cell(row, col));
                addToRow(0, 4, 0, true);
                addToRow(1, 4, 0, false);
                addToCol(0, 2, 1, true);
                addToCol(1, 2, 1, true);
                addToCol(2, 2, 1, false);
                addToCol(3, 2, 1, false);
                /*
                addToCol(0, 2, 2, false);
                addToCol(1, 2, 2, true);
                addToCol(2, 2, 2, true);
                addToCol(3, 2, 2, false);
                */
                addToCol(0, 2, 2, true);
                addToCol(1, 2, 2, false);
                addToCol(2, 2, 2, false);
                addToCol(3, 2, 2, true);

                headerLeft = new Header(0, true, false);
                headerTop = new Header(1, true, true, false, false);
                //headerBottom = new Header(2, false, true, true, false);
                headerBottom = new Header(2, true, false, false, true);
                headerRight = null;
                break;
            case 4:
                for (int row = 0; row < 4; row++)
                    for (int col = 0; col < 4; col++)
                        cells.add(new Cell(row, col));

                addToRow(0, 4, 0, true);
                addToRow(1, 4, 0, true);
                addToRow(2, 4, 0, false);
                addToRow(3, 4, 0, false);
                /*
                addToRow(0, 4, 1, false);
                addToRow(1, 4, 1, true);
                addToRow(2, 4, 1, true);
                addToRow(3, 4, 1, false);
                */
                addToRow(0, 4, 1, true);
                addToRow(1, 4, 1, false);
                addToRow(2, 4, 1, false);
                addToRow(3, 4, 1, true);

                addToCol(0, 4, 2, true);
                addToCol(1, 4, 2, true);
                addToCol(2, 4, 2, false);
                addToCol(3, 4, 2, false);
                /*
                addToCol(0, 4, 3, false);
                addToCol(1, 4, 3, true);
                addToCol(2, 4, 3, true);
                addToCol(3, 4, 3, false);
                */
                addToCol(0, 4, 3, true);
                addToCol(1, 4, 3, false);
                addToCol(2, 4, 3, false);
                addToCol(3, 4, 3, true);

                headerLeft = new Header(0, true, true, false, false);
                //headerRight = new Header(1, false, true, true, false);
                headerRight = new Header(1, true, false, false, true);
                headerTop = new Header(2, true, true, false, false);
                //headerBottom = new Header(3, false, true, true, false);
                headerBottom = new Header(3, true, false, false, true);
                break;
//(...)
```

However I had to disable one of the tests in the file: KarnaughMapTest.java (full changed file attached),

`public void testBUG_1()`

so that it passes all tests. (Changing just the code to reorder vars in 3 vars kmaps does not trigger this testBUG_1 error).


```
//(...)
   // in 4x4 map a 8 cell block is drawn in wrong orientation
    public void testBUG_1() throws IOException, ParseException, KarnaughException {
/*    Expression exp = new Variable("D");
        KarnaughMap c = new KarnaughMap(Variable.vars(4), exp);

        assertEquals(1, c.size());

        KarnaughMap.Cover co = c.iterator().next();
        assertTrue(co.isDisconnected());
        assertFalse(co.onlyEdges());
        assertTrue(co.isVerticalDivided());

        exp = new Variable("B");
        c = new KarnaughMap(Variable.vars(4), exp);

        assertEquals(1, c.size());

        co = c.iterator().next();
        assertTrue(co.isDisconnected());
        assertFalse(co.onlyEdges());
        assertFalse(co.isVerticalDivided());
*/

//(...)
```

I am running the 2 versions, and as far as I test them the changed version seems to work as the original.
It creates the 3 and 4 vars kmaps with the reordered variables and simplifies the expression as expected.

However, I am concerned with that disabled unit test.
I did not get what the comment on that test means:

>    // in 4x4 map a 8 cell block is drawn in wrong orientation

Can you tell me if the original order of variables in Digital kmaps is really needed for proper operation?


thanks,

Helder

[KarnaughMap.java.txt](https://github.com/hneemann/Digital/files/3857649/KarnaughMap.java.txt)
[KarnaughMapTest.java.txt](https://github.com/hneemann/Digital/files/3857660/KarnaughMapTest.java.txt)

**Comment by hneemann** [comment]
There are more than 1000 different ways to draw a 4x4 K-map.
Why do you care which one is used? They all lead to the same result.

**Comment by hneemann** [comment]
The k-map is not used to calculate the minimized equation. The minimization is done with the method of Quine & McCluskey.
The k-map is only drawn for illustrative purposes using the already minimized equation.
Even if the k-map is drawn completely wrong, the result of the minimization is not affected.

**Comment by helderdaniel** [comment]
> There are more than 1000 different ways to draw a 4x4 K-map.
> Why do you care which one is used? They all lead to the same result.

Yeah,
I was thinking in counters.
For a gray counter numbering like this seems easier to follow.
For a binary counter it is not that easy but it still seems easier. Of course that is for me ...
For other projects another numbering might be best or it does not even matter.

![image](https://user-images.githubusercontent.com/31565045/69043740-86197000-09eb-11ea-9e10-c11e7f56e9ad.png)

```

The k-map is not used to calculate the minimized equation. The minimization is done with the method of Quine & McCluskey.
The k-map is only drawn for illustrative purposes using the already minimized equation.
Even if the k-map is drawn completely wrong, the result of the minimization is not affected.
```

ok,

thanks

**Comment by jsegarraf** [comment]
Hi,

I would like this issue to be reopened as a feature request, in order to change the ordering of the cells as @helderdaniel proposes.

Although any ordering may be valid, as far as I know most books use the proposed ordering. Thus, from a student perspective, it would be helpful seeing a representation that visually matches what they expect.

Thanks

**Comment by hneemann** [comment]
@jsegarraf 
Maybe you are right!

**Comment by helderdaniel** [comment]
Hi, 

At the time I did a fork and implemented the changes proposed in the original post. 
As far as I can tell it seems to be working fine since then. 

However as also mentioned in the post I had to disable one of the tests from file KarnaughMapTest.java:

public void testBUG_1()

so that it passes all tests. 

I also found that changing just the code to reorder vars in 3 vars kmaps does not trigger this testBUG_1() unit test. It is a issue just when changing the code for 4 var maps. 

That was my main concern at the time, since I didn't figure out what this unit test is for.

**Comment by hneemann** [comment]
@helderdaniel 
As far as I  can see, your fork contains the original cell order. 

The test case is not a problem: If a variable is inverted in the k-map, you have to invert the variable also in the test cases, which depend on the ordiring in the k-map.

**Comment by hneemann** [comment]
@helderdaniel, @jsegarraf 
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/).

**Comment by helderdaniel** [comment]
74804 (NAND), 74805 (NOR), 74808 (AND),…

On Wed, 11 Mar 2020 at 10:36, Helmut Neemann <notifications@github.com>
wrote:

> @helderdaniel <https://github.com/helderdaniel>, @jsegarraf
> <https://github.com/jsegarraf>
> Please try the latest pre release <https://infdigital.dhbw-mosbach.de/>.
>
Looks ok, thanks

As far as I can see, your fork contains the original cell order.


Right!
I didn't push the proposed code in my original post since the issue was
closed.

What I pushed was just the addition of the hex 2-input gate chips.
Sorry, it was some time ago ...

**Comment by hneemann** [comment]
> Sorry, it was some time ago ...

Never mind! :smiley:

**Comment by jsegarraf** [comment]
Pre-release works perfectly, thanks
