### ISSUE TITLE
Non modal help window

### ISSUE THREAD

**Issue by Tobias004** [hneemann/Digital#392]
Unfortunately the help window which appears when clicking on "help" of a element is modal to the main window. For beginners it would be useful to get a non modal window which stays open while continue work.

**Comment by hneemann** [comment]
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/) build.

**Comment by hneemann** [comment]
closed in 6910b71dffadbb571afddb83e0ac53b99251e0f2
