### ISSUE TITLE
Error with tunnel?

### ISSUE THREAD

**Issue by obiwanjacobi** [hneemann/Digital#395]
I am not sure what I am doing wrong here. A circuit with an input, splitter and tunnels. I complains that the tunnel is not connected.

![image](https://user-images.githubusercontent.com/3882444/70826544-7bce7400-1de7-11ea-98be-eac992cd6649.png)

**Comment by hneemann** [comment]
A splitter works different in Digital compared to a splitter in Logisim.
In Digital a splitter has a direction which means inputs at one side and outputs at the other.
The net "IO" has no output connected to it, which means the state of the net is undefined.
See also #197

**Comment by obiwanjacobi** [comment]
Ah, but then the default configuration of the splitter is set to 'merger' - that is what threw me off.

**Comment by hneemann** [comment]
That's right! I hadn't even noticed that yet! :smile:
