### ISSUE TITLE
about inout pin and cap

### ISSUE THREAD

**Issue by kEviN1H** [hneemann/Digital#396]
There is **inout** type pin in FPGA, can we add it?

Also, I have a design that may need to reconstruct DRAM. Can I increase the cap?

![39](https://user-images.githubusercontent.com/4837382/71070690-44c8db80-21b6-11ea-992e-ce137b466f8a.png)

**Comment by hneemann** [comment]
I recently implemented support for HDL inout ports. See #394 

It is not possible to simulate a DRAM cell with the simulator because there are no capacitors and I do not plan to add a capacitor as a component.

**Comment by kEviN1H** [comment]
OK, I see. Thank you!

**Comment by kEviN1H** [comment]
OK, I see. Thank you!
