### ISSUE TITLE
Library sub circuits not being imported if Digital folder renamed with some characters

### ISSUE THREAD

**Issue by guiweber** [hneemann/Digital#40]
Adding spaces or certain special characters (e.g. è, ç, %) to the Digital folder name prevent the Library sub circuits from being imported. This was tested under Windows 10.

Steps to reproduce:
1. Download Digital V 0.13
2. Extract the zip archive
3. Start Digital
4. Notice that the Library sub circuits are imported correctly
5. Exit Digital
6. Rename the folder to "Digital 0.13"
7. Start Digital again
8. Notice that the Library sub circuits are not available

**Comment by hneemann** [comment]
fixed in v0.14
