### ISSUE TITLE
stimulus

### ISSUE THREAD

**Issue by amryounis** [hneemann/Digital#400]
how one can provide tailored stimulus to inputs. 

the stimulus will be a series of ones and zeros.

**Comment by hneemann** [comment]
The easiest way to do that, is to add a test case to the circuit.
The most example circuits contain test cases wich can be used as an example for a test case.

**Comment by amryounis** [comment]
a test case is ok but the point is that (as far as I am aware of the app) it will run and issue a success/failure message. So I believe the benefit of a stimulus input is clear here. 

 the other work around would be to have a memory+counter(for address)+clock

**Comment by hneemann** [comment]
> the other work around would be to have a memory+counter(for address)+clock

This is also a solution. But using a counter and a ROM you have to check yourself if the circuit works as expected or not.
With the help of a test case this check is also performed automatically and reliably.

**Comment by amryounis** [comment]
the Deeds project provide a simple solution:

![image](https://user-images.githubusercontent.com/3895133/71469593-5ae82480-27d2-11ea-9e2e-338c825c091d.png)
