### ISSUE TITLE
clock output is not at 50% duty

### ISSUE THREAD

**Issue by amryounis** [hneemann/Digital#409]
I found that clock output is not at 50% duty for certain frequencies, especially the ones I put by hand like 3, 7, ... Hz. Is this normal behavior? 

How to adjust duty cycles?

![image](https://user-images.githubusercontent.com/3895133/71971559-87a92c80-3213-11ea-991c-d4d12afe07da.png)

**Comment by hneemann** [comment]
The diagram is maybe a bit confusing because the x-axis does not show the time. 
It shows a kind of a modification number. See #359 for a more detailed discussion.
