### ISSUE TITLE
Batch simulation

### ISSUE THREAD

**Issue by mguthaus** [hneemann/Digital#412]
Have you thought about adding a batch simulation capability? Something simple that you can apply inputs and read outputs and state. One very useful feature for large classes is to do batch simulation for grading.

I ask, because this is a nice replacement for MML (MultiMedia Logic) that many introductory courses use. However, MML is not maintained.

**Comment by hneemann** [comment]
Please look at issue #353
Does this solution work for you?

**Comment by mguthaus** [comment]
Oh, yes, that is exactly what we would need. Is there more documentation or examples on how to use that? I did not see in the help, but maybe I'm not looking in the right place.

**Comment by hneemann** [comment]
There is actually nothing else to document except the command line. But you are right: It should be described in the documentation.
The test cases are normal Digita" test cases. There is nothing special about them.

**Comment by mguthaus** [comment]
Yes, I found the description of the test cases down in the context menu.
Perhaps that should be in the manual in addition to the command line
options. Thanks for your hard work!

**Comment by jyuan2pace** [comment]
Is this feature currently in the current release/master branch? I saw it is in the release notes of 0.24. Wonder if it has been included in current release as the pre-release feature has expired in #353 Thank you.

**Comment by hneemann** [comment]
@jyuan2pace 
It is available in the current master branch and will be included in the next, soon to be released version. In the meantime, you can try the latest pre-release build available [here](https://infdigital.dhbw-mosbach.de/).

**Comment by jyuan2pace** [comment]
Thanks. Not sure if it's only me but the pre release link doesn't work for me. I can build from master anyway. Thanks!

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________
