### ISSUE TITLE
Suggestion: Allow opening the full documentation from the help menu

### ISSUE THREAD

**Issue by guiweber** [hneemann/Digital#43]
Having a link to the full documentation pdf within Digital would allow users to quickly open the documentation instead of having to browse their file system. Also, people may not know the documentation exists unless they look into the Digital folder. Having a link would make it easier to discover.

The link could be added in the help menu, right under Components
![capture](https://user-images.githubusercontent.com/7825368/29476634-f37dab20-8432-11e7-90e9-662b10fcf913.PNG)

**Comment by hneemann** [comment]
added in v0.14
