### ISSUE TITLE
Send single bit signal to a circuit's multibit input.

### ISSUE THREAD

**Issue by bcrew1375** [hneemann/Digital#437]
I want to take a single bit and send that bit as all 16 bits to a circuit that takes those 16 bits on a single input. I'm aware I can use a splitter to input the bit as 16 different signals, and I could output those 16-bits into the circuit, but this seems pretty inefficient and takes up a lot of space. Is there a simpler way?

**Comment by hneemann** [comment]
Yes it is. Think of the one bit as a signed 1-bit value (0,-1) and use the sign extender to convert it to a signed 16-bit value (0,-1). This means that a 0 becomes 0x0000, and a 1 becomes 0xffff.
