### ISSUE TITLE
naming power and gnd

### ISSUE THREAD

**Issue by hugocoolens** [hneemann/Digital#439]
It would be a nice feature if we could also give (and display) a name for power e.g. VDD en for ground,
e.g. GND or VSS

kind regards,
Hugo

**Comment by hneemann** [comment]
Kind of like this?

![z](https://user-images.githubusercontent.com/7190563/78971446-e086aa80-7b0b-11ea-8ad2-bcdb11978b1c.png)

**Comment by hugocoolens** [comment]
Yes, that would be really nice.

kind regards,
Hugo

Op vr 10 apr. 2020 om 09:16 schreef Helmut Neemann <notifications@github.com

**Comment by hneemann** [comment]
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/).

**Comment by hugocoolens** [comment]
Great, thanks!

Op vr 10 apr. 2020 om 10:24 schreef Helmut Neemann <notifications@github.com
