### ISSUE TITLE
why RS-Latch output 1 when R and S both are 1?

### ISSUE THREAD

**Issue by itviewer** [hneemann/Digital#440]
Although this state is meaningless, in all the books I have seen, most RS-Latch consists of two cross-coupled NOR gates, when the input is all 1, the output is all 0, while the buildin RS-Latch output 1 when R and S both are 1.

![深度截图_选择区域_20200410162946](https://user-images.githubusercontent.com/1397840/78976328-8526dd80-7b48-11ea-89fd-1d53c567fb12.png)

**Comment by hneemann** [comment]
Thanks for pointing that out!
It's incredible that this could go undetected for so long. 
There's even a test case that checks this wrong output.
