### ISSUE TITLE
there are some docs about source code?

### ISSUE THREAD

**Issue by dbwodlf3** [hneemann/Digital#447]
hello.

i am interesting in this project.

i used Logisim and i found this project.

i would like to contribute this project. then, if there are some docs for architecture about codes could i get docs?

i don't know where are docs about codes.

just i have to analysis from source codes?

**Comment by hneemann** [comment]
Currently there is no detailed documentation of the source code. However, all packages contain a java-doc file (package-info.java), which describes what the package does and how it does it. But even this description is not as detailed as it should be.
If the documentation is extended, I will extend this kind of documentation. I am not a friend of documentation outside of the source code, like Word files, wikis or similar.

**Comment by dbwodlf3** [comment]
thank you.

i try to read java-doc files and more study.. and get some information.

and come back!
