### ISSUE TITLE
Can you add arduino components to digital?

### ISSUE THREAD

**Issue by liukenny961** [hneemann/Digital#452]
I am a digital user from China. I want to use digital to build a large circuit, but arduino neno is needed. Can you add arduino components such as arduino neno to digital? In this way, l can use arduino neno to write programs to EEPROM. In addition, l hope arduino neno's programming interface can use C++ code instead of modular programming like scratch. Or both can be added at the same time. Thank you!

In addition: my English is not very good, and there may be some grammatical mistakes. I hope you can understand my words! If there is something I have not say clear, you can ask me question and I will answer it as soon as possible.
![批注 2020-05-18 113404](https://user-images.githubusercontent.com/65520199/82172211-251c1780-98fc-11ea-9c61-cb5cb7858b2c.png)
![批注 2020-05-18 113711](https://user-images.githubusercontent.com/65520199/82172215-264d4480-98fc-11ea-841e-d23afc098e44.png)

**Comment by liukenny961** [comment]
So what is the way to do this in digital? I'm afraid not.

**Comment by hneemann** [comment]
That's right! There is currently no AVR core that can be used as a digital component, and I don't think there will be one anytime soon.

**Comment by liukenny961** [comment]
Will digital add this feature in the future?

**Comment by liukenny961** [comment]
l think it's a difficult work.

**Comment by liukenny961** [comment]
OK.
