### ISSUE TITLE
Is 74154 symbol wrong?

### ISSUE THREAD

**Issue by eliask05** [hneemann/Digital#454]
According to the datasheet, the outputs (Y0 - Y15) and control inputs (G1 & G2) should all be active low. In the symbol they are labelled active high.

Thanks!

**Comment by liukenny961** [comment]
Is it? I also want to check it out.

**Comment by eliask05** [comment]
Clarification: the device works as intended, i.e. outputs and control inputs are active low but the symbol does not reflect this.

**Comment by hneemann** [comment]
It seems to me that the naming of the inputs and outputs depends on the manufacturer. The available data sheets do not seem to be consistent in this respect.

**Comment by eliask05** [comment]
Understood and agreed. I am OCD and I like active low pin names to have an overbar but no big deal. I just modified the SVG to my liking and I am using it. Closing the issue.

**Comment by hneemann** [comment]
@eliask05 
It is not necessary to create a custom SVG shape. 
Simply rename the inputs and outputs like this: "~G0" or "~Y0"

**Comment by eliask05** [comment]
Doh! Thanks.
