### ISSUE TITLE
Add 74HC4017

### ISSUE THREAD

**Issue by gnarz** [hneemann/Digital#461]
Hi,

for a thing I'm fiddling with I needed a 74HC4017. So I made one, trying to make it look like the 74... chips from the library, and as others may find it useful I attach it here for your consideration.

It was built from the functional diagram in the datasheet, and comes with a test.

[744017.dig.gz](https://github.com/hneemann/Digital/files/4682871/744017.dig.gz)

Regards,
Gunnar

**Comment by hneemann** [comment]
Looks good to me!
