### ISSUE TITLE
Feature request: seven segment hex display

### ISSUE THREAD

**Issue by eliask05** [hneemann/Digital#465]
I like to use the seven segment hex display to show the values on a bus. Unfortunately, when the bus is in high impedance the display shows 0. Is it possible to change it to show something non-numeric, say like the attached image? Granted, I can use a probe that does show Z but the display is way cooler :smiley:
![7segZ](https://user-images.githubusercontent.com/41453704/83064066-cb67cb80-a026-11ea-9ad7-9b3e794ee3dc.png)

**Comment by hneemann** [comment]
I like the idea but i don't like your example. 
What about turning off the display in case of a high-z input?

**Comment by eliask05** [comment]
Yes! That will work.
