### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by guidogratzke1** [hneemann/Digital#470]
version: v0.24 

-- Fehler beim erzeugen der Schaltung - verwendete Bauteile aus dem Programm ;
-- Fehler beim simulieren - Schaltung scheint zu oszillieren . Habe dann die Schaltung auf eine Steckplatine aufgebaut und vermessen bis 7 Mhz keine Oszillation obwohl die gewünschte Frequenz nur 1 Mhz sein soll. Auch ein Design der Schaltung in einem FPGA zeigte keine Oszillation in der Timinganalyse. Mein verwendetes OS ist Windows 10 Pro 64bit Version 1909.
![CPU](https://user-images.githubusercontent.com/66130636/83280051-5d620680-a1d6-11ea-9d37-a6849cd17452.png) 
![opdec](https://user-images.githubusercontent.com/66130636/83280187-91d5c280-a1d6-11ea-97fa-09e40a260050.png)

**Comment by hneemann** [comment]
Können Sie die Schaltung als ZIP an dieses Ticket anhängen?

**Comment by guidogratzke1** [comment]
Ja, hier ist nun die gewünschte zip Datei mit den Schaltungen.
[Schaltungen.zip](https://github.com/hneemann/Digital/files/4705123/Schaltungen.zip)

**Comment by hneemann** [comment]
Die Oszillation konnte ich nicht reproduzieren! Haben Sie evtl. noch eine Schaltung, welche die Reproduktion der Oszillation vereinfacht?

Eine Version mit dem behobenem Nullpointer-Fehler finden Sie [hier](https://infdigital.dhbw-mosbach.de/).

**Comment by guidogratzke1** [comment]
Anbei sende ich eine Zip Datei mit einem Screenshot und zwei Dateien piposrg4.dig und mul8.dig.
Die Datei piposrg4.dig bildet die Grundlage für die Datei mul8.dig. Der Screenshot zeigt den Fehler.Wenn man mehrere Durchläufe der Simulation laufen lässt so tritt der Fehler auf.
[Fehler.zip](https://github.com/hneemann/Digital/files/4705557/Fehler.zip)

**Comment by hneemann** [comment]
Kann es sein, dass die ZIP Datei keine Dateien enthält?

**Comment by guidogratzke1** [comment]
Anbei nun aber die richtige zip Datei hatte mich vertan und bitte daher um Entschuldigung .
[Anmerkung 2020-05-30 130533.zip](https://github.com/hneemann/Digital/files/4705688/Anmerkung.2020-05-30.130533.zip)

**Comment by hneemann** [comment]
Wenn SIe die Schaltung im Gatterschrittmodus starten, sehen Sie, dass die Oszillation durch die asynchronen Set und Clear Eingänge der FlipFlops verursacht wird.
Es handelt sich meines Erachtens um eine Schwäche der Schaltung und nicht um einen Fehler im Simulator.

**Comment by guidogratzke1** [comment]
Ich konnte nun den Fehler beheben in dem ich das JK-FF asynchron mit dem D-FF asynchron ausgetauscht habe.Was ich zum erstellen eines Registers gelernt habe ist die Tatsche das man darauf achten soll nur eine Gatter Art zu verwenden (idealer Weise Nand) so wird die Simulation einfacher.
Das lassen sich Latenzen besser erkennen. Danke für die Mühe und Geduld von ihnen mir bei meinem Problem zu helfen.

**Comment by hneemann** [comment]
Nichts zu danken! :smile:
