### ISSUE TITLE
Running Statistics from command line

### ISSUE THREAD

**Issue by moita** [hneemann/Digital#472]
Like Running Test case from command line, i think getting statistics from command line can improve the automatic batch evaluation  for student tests.
Is that possible?

**Comment by hneemann** [comment]
What kind of statistics are you thinking of?
And what should the output look like?

**Comment by moita** [comment]
The same table (text format) as in Simulation> Circuit statistics.
For example:
In an exercise, I propose to students to change FF-JK to FF-D.
They can send the same circuit and the results will be good. With the statistics, I can verify that they are really using D.

**Comment by hneemann** [comment]
But you have to write a simple parser to analyze the output generated by Digital.
And in this case it might not be much more complex to analyze the dig file directly.

**Comment by moita** [comment]
In addition, I am running the circuit check inside Moodle.

**Comment by hneemann** [comment]
> It's true but it gets simpler in a small table, and that job is already done. 

I don't know what programming language you use, but I'm sure there is a XPath library available. And that makes it a one-liner. :smile:

**Comment by moita** [comment]
You're right. You are doing an excellent job. Thanks

**Comment by hneemann** [comment]
@moita 
in the latest [pre-release](https://infdigital.dhbw-mosbach.de/) i have implemented a new command line interface.
This new command line interface also allows to optain the circuit stats.
