### ISSUE TITLE
Analysis tool only partially supports format setting

### ISSUE THREAD

**Issue by xotmatrix** [hneemann/Digital#475]
The analysis tool only partially supports the format setting. It uses the desired operators but appears to always use overbar for complement. Overbar is not one of the format settings so it is not entirely clear what the intention is.

![javaw_2020-06-08_20-32-50](https://user-images.githubusercontent.com/14209329/84093202-90bb4700-a9c7-11ea-8871-7fb9b8d83469.png)

It would be very helpful if this (1) could be formatted according to the setting and (2) could be saved or copied to the clipboard.

Affects v0.24, Windows 10

**Comment by hneemann** [comment]
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/).

**Comment by xotmatrix** [comment]
It took me a moment to figure out the change was in the File menu. It seems to work perfectly. Thank you very much for making this tool an even greater pleasure to use.
