### ISSUE TITLE
Bus size on wires

### ISSUE THREAD

**Issue by nortont** [hneemann/Digital#477]
For illustrative purposes, it would be nice to be able to have a tick box on an interconnecting wire that shows the number of bits in the form shown below. 

This could either be sourced from the connected component or manually typed in.
![image](https://user-images.githubusercontent.com/4540401/84561953-b2357d80-ad8f-11ea-957b-8caef1007d5a.png)

**Comment by hneemann** [comment]
In the settings you can enable that with the option "Shows the number of wires on a bus".
But the display only appears if the simulation has been started at least once, and it disappears again if the circuit is modified.
