### ISSUE TITLE
Suggestion: support a "measure" command in the TCP connection on 41114

### ISSUE THREAD

**Issue by tcr** [hneemann/Digital#478]
Hi! Thanks so much for the Digital project, it's helped me so much to bridge the gap between circuit design and circuit manufacturing.

I investigated the TCP connection provided in Digital and used the [Assembler](https://github.com/hneemann/Assembler) project as a guide and was able to set up automated tests (from the command line) from Python to run code on a virtual CPU. This went great!

I needed one more component, a way for a TCP connection to request the current value of all signals measured by the circuit during the debug/run cycle. This would allow me to create unit tests that validate values. I implemented this already for my needs and my latest commit here implements such a feature: https://github.com/hneemann/Assembler

The basic proposal is a "measure" command which returns a JSON-encoded map of `signal_name => signal_value_as_int`. I've been able to use such a command to create interactive tests such as this: 

```
debug()
step_until(pc=0x8)
validate(dr=0x3)
step_until(pc=0x12)
validate(dr=0x0)
```

The `validate` step requests the latest "measure" state and then checks if the values in keyword args are correct, otherwise it throws. This makes it easy to write unit tests over TCP and ensure my CPU changes don't regress.

**Comment by hneemann** [comment]
First of all: This is an interesting idea.  One of my students suggested it before, but I forgot about it.

But when it comes to testing circuits, the TCP interface is not the best choice in my opinion. There are two easier ways to create tests:

1. With the implementation of issue #474 the possibilities of the built-in test cases have increased significantly. Maybe you should give them a new chance.
2. There is a class UnitTester that can be used for testing. See [here](https://github.com/hneemann/DigitalTesting/blob/master/src/main/java/de/neemann/digital/test/TestCircuit.java). This class allows a very easy access to all information, but you have to use Java for implementing the test cases.
