### ISSUE TITLE
test signal not found

### ISSUE THREAD

**Issue by moita** [hneemann/Digital#479]
When you use don't care, you can get alternative solutions for the same problem.
In some cases your simplified solutions has different variables.
If you ask students do design the simplified circuit and use the same test case for command line evaluation it don't work because you get 
    Error running tests: because one input or more isn't there.
There are any chance to  automatically consider  as don´t care  the not used variables ?

**Comment by hneemann** [comment]
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/). There is a new command line option.

**Comment by moita** [comment]
I tried with command:
java -cp Digital.jar CLI test -circ NAND.dig -tests teste1.dig
Teste1.dig has a W X Y Z test table.
NAND.dig is a simplifies function that has only W X Z inputs.
I got the following error message. (Y not found!)
Use default settings!tv: Sinal de teste Y não encontrado no circuito!Tests have failed.

**Comment by moita** [comment]
You said that there are a new command line option. Where can I find it?

**Comment by hneemann** [comment]
if you type 
```
java -cp Digital.jar CLI
```
a help text is shown. The documentation also mentions the new option `-allowMissingInputs`.

**Comment by moita** [comment]
Working well, thank you!
I have two other suggestions:
1- I think that selecting a wire with the right mouse button would be very practical.
2-I'm colorblind. There are many students who are too. It may be strange for you, but the HIGH, LOW colors you use are very confusing to me. Is there any chance of being able to specify these colors or simply print 0/1 inside the input / output circles?

**Comment by hneemann** [comment]
> I think that selecting a wire with the right mouse button would be very practical.

It is already possible to select a wire with CTRL down.

> I'm colorblind. [...] It may be strange for you, but the HIGH, LOW colors you use are very confusing to me.

I have always resisted implementing different color schemes because they do not fit well into the architecture and it seemed unnecessary. 
However, supporting color-blind users is a really strong argument. I'll work something out.

**Comment by hneemann** [comment]
@moita 
I am thinking about adding support of different color schemes. But I find it very difficult to select colors that are suitable for color blind people.
Would you help me with that? If you can handle building the simulator, you could directly change the colors in the code. I would like to save myself the trouble of making the colors selectable via the user interface.

**Comment by moita** [comment]
There are different types of color-blind people. I hardly distinguish between the two levels of green (I had to ask for the colors :-)) that you use. For me it's better if you chose a darker green and a bright yellow. 
Let me know were to change in the code, ill try.

**Comment by hneemann** [comment]
There is a new branch  "colorSchemes" 
The color-blind scheme is defined [here](https://github.com/hneemann/Digital/blob/colorSchemes/src/main/java/de/neemann/digital/draw/graphics/ColorMap.java).

**Comment by xotmatrix** [comment]
>  I would like to save myself the trouble of making the colors selectable via the user interface.

Perhaps allowing a user to load a color scheme from a file would be a good overall enhancement.

**Comment by hneemann** [comment]
@xotmatrix 
> Perhaps allowing a user to load a color scheme from a file would be a good overall enhancement.

Maybe you're right! But I think most users are happy if they don't have to worry about individual colors because suitable color schemes are available.

**Comment by hneemann** [comment]
@moita 
The latest [pre-release](https://infdigital.dhbw-mosbach.de/) build supports color schemes, and one of them is aimed for color-blind people.
Please let me know if this will help you better identify the wire states.

**Comment by moita** [comment]
Really better, thanks!

Atentamente,
Fernando Moita
————————————————
Departamento de Engenharia Eletrotécnica / Electrical Engineering Department
Instituto Superior de Engenharia de Coimbra / Coimbra Institute of
Engineering
Rua Pedro Nunes, 3030-199 Coimbra, Portugal


Helmut Neemann <notifications@github.com> escreveu no dia quinta,
25/06/2020 à(s) 13:33:

**Comment by hneemann** [comment]
@xotmatrix 
Now there is also a user definable color scheme available.

@moita 
If you feel that the scheme for colour-blind users needs to be improved, you have the opportunity to do so now. If you are satisfied, you can simply send me the ".digital.cfg" file which contains the custom scheme.

Here you can find the latest [pre-release](https://infdigital.dhbw-mosbach.de/).

**Comment by moita** [comment]
Dear Hneemann,
There are different types of color blindness, and I think I have a severe
type of protanopia. For me, the colors in the configuration file work well,
but may not be the rule for others. Thanks for your consideration.
I have another suggestion.
Although you can choose the format in which you can edit a multi-bit Input
element, the value shown is always HEX. Any possibility of displaying the
input value with the same configuration defined for editing?
[image: x.png]
Atentamente,
Fernando Moita
————————————————
Departamento de Engenharia Eletrotécnica / Electrical Engineering Department
Instituto Superior de Engenharia de Coimbra / Coimbra Institute of
Engineering
Rua Pedro Nunes, 3030-199 Coimbra, Portugal


Helmut Neemann <notifications@github.com> escreveu no dia terça, 30/06/2020
à(s) 16:26:

**Comment by moita** [comment]
Consider the new cfg file with changes in the Highlighted color
Atentamente,
Fernando Moita
————————————————
Departamento de Engenharia Eletrotécnica / Electrical Engineering Department
Instituto Superior de Engenharia de Coimbra / Coimbra Institute of
Engineering
Rua Pedro Nunes, 3030-199 Coimbra, Portugal


---------- Forwarded message ---------
De: Fernando Moita <moita@isec.pt>
Date: quarta, 1/07/2020 à(s) 12:26
Subject: Re: [hneemann/Digital] test signal not found (#479)
To: hneemann/Digital <
reply@reply.github.com>


Dear Hneemann,
There are different types of color blindness, and I think I have a severe
type of protanopia. For me, the colors in the configuration file work well,
but may not be the rule for others. Thanks for your consideration.
I have another suggestion.
Although you can choose the format in which you can edit a multi-bit Input
element, the value shown is always HEX. Any possibility of displaying the
input value with the same configuration defined for editing?
[image: x.png]
Atentamente,
Fernando Moita
————————————————
Departamento de Engenharia Eletrotécnica / Electrical Engineering Department
Instituto Superior de Engenharia de Coimbra / Coimbra Institute of
Engineering
Rua Pedro Nunes, 3030-199 Coimbra, Portugal


Helmut Neemann <notifications@github.com> escreveu no dia terça, 30/06/2020
à(s) 16:26:

**Comment by hneemann** [comment]
@moita 
I didn't get those two files. Neither the screenshot nor the cfg file.

> For me, the colors in the configuration file work well, but may not be the rule for others.

You're the only person I know with this problem.That's why I can choose the colors to suit you best.
If someone with a different kind of color blindness responds, I would simply add another color scheme.

**Comment by moita** [comment]
[digital.zip](https://github.com/hneemann/Digital/files/4859103/digital.zip)
![x](https://user-images.githubusercontent.com/7574826/86268104-9ae3f600-bbbf-11ea-831d-95a2c24eb65c.png)

**Comment by hneemann** [comment]
@moita
All the wire colors have changed. Is that intentional?

**Comment by moita** [comment]
yes

**Comment by moita** [comment]
for me the Normal color-scheme with  Wire, wire High, Wire Low, Output and Highlighted changed as in the file cfg works well

**Comment by hneemann** [comment]
The latest [pre-release](https://infdigital.dhbw-mosbach.de/) contains your color suggestions.

**Comment by xotmatrix** [comment]
Thanks for all you do, @hneemann.
