### ISSUE TITLE
Strange relay circuit behavior

### ISSUE THREAD

**Issue by DmitryVyal** [hneemann/Digital#480]
I discovered a strange behavior of a circuit containing a RelayDT group

[circuit.zip](https://github.com/hneemann/Digital/files/4808958/circuit.zip)
![state0](https://user-images.githubusercontent.com/45413280/85217474-45774000-b39a-11ea-9b7f-e8ccb1367b76.png)
when I switch the input marked * to 1 everything works correctly
![state1](https://user-images.githubusercontent.com/45413280/85217477-4c9e4e00-b39a-11ea-9fd9-371c8c95f12d.png)
when I switch the input marked * back to 0 circuit state is incorrect
![state2](https://user-images.githubusercontent.com/45413280/85217478-4f00a800-b39a-11ea-8b98-b822f2e0e30b.png)
I don’t understand the reason, however, under certain conditions, the order of operation of the “contacts” is important for the correct operation of the circuit model

[PlainSwitchDT.java.diff.txt](https://github.com/hneemann/Digital/files/4809020/PlainSwitchDT.java.diff.txt)

**Comment by hneemann** [comment]
This is an interesting one! I haven't looked at the code yet, but I think it makes a difference if there is a short moment when both switches are open or if there is a short moment when both switches are closed. There should always be a short moment where both switches are open, and there should not be the opposite.

**Comment by hneemann** [comment]
This one was really hard to track down! My first guess was completely wrong!
I should never have implemented those switches! :smile: 
Thanks for pointing this out.
