### ISSUE TITLE
Question about truth table file

### ISSUE THREAD

**Issue by Boolean1** [hneemann/Digital#482]
I'd like to create truth table files myself programmatically, but I'm not sure how the data is supposed to be stored.

Most of the XML stuff is self-explanatory, but this part isn't:

`<values class="BoolTable">
        <table>AAAAAAAAAAA=</table>
      </values>`

How is the data stored in the table? 

Also, is there a reason "synthesis" is spelled "synthesise" in the analysis drop-down menu, or is it a mistake?

**Comment by hneemann** [comment]
It is a Base64 encoded array of bytes, where only the output column is stored.
Your example represents a truth table with three inputs and all output values are zero.
