### ISSUE TITLE
LED matrix freezing

### ISSUE THREAD

**Issue by leonicolas** [hneemann/Digital#489]
The LED matrix component is not updating the led state properly. 
The attached video shows the LED working well after changing the LED state but only for a few clock cycles. After that, the LED matrix freeze and it only starts to update again for more a few cycles after changing the LED state.

https://youtu.be/Ki9_61JYZuc

**Comment by hneemann** [comment]
@leonicolas 
Could you please zip and attach the shown circuit?

**Comment by hneemann** [comment]
@leonicolas 
I was able to reproduce the problem myself.
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/).
