### ISSUE TITLE
Allow wire colours for simulation to be configurable

### ISSUE THREAD

**Issue by sudhashbahu** [hneemann/Digital#496]
Currently, a wire with an OFF signal is dark green and with ON signal is bright green, as carried over from Logisim. I recently noticed that some colour blind people have trouble distinguishing the two. For their convenience, it would be better to let the colours for ON/OFF/TriState to be configurable.

**Comment by hneemann** [comment]
This feature is already implemented but not yet released.
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/) build.

**Comment by sudhashbahu** [comment]
Thank you!
