### ISSUE TITLE
Analysis error in equation formulation

### ISSUE THREAD

**Issue by wmuece** [hneemann/Digital#499]
Using "Analysis" for this MUX circuit, and after looking at the resulting equation (see image) the equations for Y and W should be complementary.   They are not.  Truth tables seem to be fine however.
[MUXtest.zip](https://github.com/hneemann/Digital/files/5007404/MUXtest.zip)

**Comment by hneemann** [comment]
The two equations are complementary!

To prove this claim, a simpler example of the same structure is shown here:

!(A D0 + !A D1) 
= !(A D0) * !(!A D1)
= (!A + !D0) * (A + !D1)
= !A A + !A !D1 + !D0 A + !D0 !D1
= !A !D1 + !D0 A + !D0 !D1
= !A !D1 (D0 + !D0)  + A !D0 (D1 + !D1) + !D0 !D1 (A + !A)
= !A !D1 D0 + !A !D1 !D0  + A !D0 D1 + A !D0  !D1 + !D0 !D1 A + !D0 !D1 !A
= !A !D1 D0 + !A !D1 !D0  + A !D0 D1 + A !D0  !D1 + !D0 !D1 A 
= !A !D1 D0 + !A !D1 !D0  + A !D0 D1 + A !D0  !D1
= !A !D1 (D0 + !D0)  + A !D0 (D1 + !D1)
= !A !D1  + A !D0
= A !D0 + !A !D1
