### ISSUE TITLE
Backspace wie Entfernen-Taste behandeln - zum Löschen von Elementen

### ISSUE THREAD

**Issue by carstenhag** [hneemann/Digital#5]
Hallo,

das Problem betrifft hauptsächlich Macs, da man `fn + backspace` drücken muss um ein entfernen zu betätigen, aber auch auf Windows-Laptops würde dies die Usability verbessern.

**Comment by hneemann** [comment]
Ich habe gerade keinen Mac zur Hand. Würden Sie kurz testen, ob von HEAD auf dem Mac die Backspace-Taste erkannt wird?

**Comment by carstenhag** [comment]
@hneemann Mit dem Commit wird die Taste korrekt erkannt und die Elemente werden gelöscht, vielen Dank!

**Comment by hneemann** [comment]
added in v0.12

**Comment by hneemann** [comment]
@carstenhag: Konnten Sie inzwischen v0.11.1 und v0.12.1 bzgl. der Schriftgröße vergleichen? Ich habe die Befürchtung, dass auf dem Mac mit Retina-Display die Schrift im Menü in v0.12.1 zu groß sein könnte.
