### ISSUE TITLE
K-map feature suggestion

### ISSUE THREAD

**Issue by wmuece** [hneemann/Digital#500]
It would be great if your wonderful Kmap feature also could allow these much more common minterm orderings used in virtually all textbooks (for three variables):

0 2 6 4
1 3 7 5

0 1 3 2
4 5 7 6

**Comment by hneemann** [comment]
Could you please try the latest [pre release](https://infdigital.dhbw-mosbach.de/) build?

**Comment by hneemann** [comment]
Now the k-map layout is configurable using drag&drop.
