### ISSUE TITLE
'noModelSet' error when using 'SignEx' Component.

### ISSUE THREAD

**Issue by Aimini** [hneemann/Digital#508]
## Problem
I encountered a strange error when starting to simulate this simple circuit:
![image](https://user-images.githubusercontent.com/19285386/90972873-3f930c00-e54f-11ea-81cf-3d800303b2c3.png)

But after a little modification, it can be simulated. Although the function is not as I expected:
![image](https://user-images.githubusercontent.com/19285386/90972926-c0ea9e80-e54f-11ea-919e-94f8e26bf9fa.png)

Is it a bug, or am I missing somthing?
# version
![image](https://user-images.githubusercontent.com/19285386/90973047-0360ab00-e551-11ea-9f95-67fa46c09cfb.png)

**Comment by Aimini** [comment]
I’ve used another component to solve this problem, but you are really diligent that fix it in one day! And thanks to github I have not received any notification yet.

**Comment by hneemann** [comment]
This is also my experience: The github email notification is not very reliable.
