### ISSUE TITLE
Feature Request: Additional bit sizes for Data and Address of ROM

### ISSUE THREAD

**Issue by sudhashbahu** [hneemann/Digital#509]
Currently, the ROM component allows Data width and Address width of 1-16 and 32 bits. is it possible to allow all sizes from 1-32?

**Comment by hneemann** [comment]
Any bit width between 1 and 64 is allowed. 
The bit width can be simply typed in. 
The combo box shows only the most frequently used values so that it does not get too big.

**Comment by sudhashbahu** [comment]
Thank you for the clarification.
