### ISSUE TITLE
Simple ROM bit cell

### ISSUE THREAD

**Issue by erdemoncel** [hneemann/Digital#513]
I would like to implement a simple ROM bit cell.

![adder](https://user-images.githubusercontent.com/68565680/93065329-3e05c100-f681-11ea-9b75-69dcc33d0ab1.png)

When I try to simulate this basic circuit and when A  becomes high it gives an error message like this.

![error](https://user-images.githubusercontent.com/68565680/93065647-a785cf80-f681-11ea-9b25-905dbc2ba1ed.png)

Any ideas ? Thanks.

**Comment by hneemann** [comment]
The FET shorts out power and ground.
You have to add a pull up resistor.
See the `cmos/rom.dig` example.
