### ISSUE TITLE
Underneath component wiring allowed?

### ISSUE THREAD

**Issue by wmuece** [hneemann/Digital#514]
Not sure if underneath component wiring is allowed, or is this related to my earlier bus output issue?  Some wiring examples follow
[Archive.zip](https://github.com/hneemann/Digital/files/5257028/Archive.zip)

<img width="650" alt="Wiring1" src="https://user-images.githubusercontent.com/1489640/93799664-73745680-fc0d-11ea-9f8b-c05c48f7588c.png">
<img width="650" alt="Wiring2" src="https://user-images.githubusercontent.com/1489640/93799665-740ced00-fc0d-11ea-9d6e-164f1961f952.png">

**Comment by hneemann** [comment]
Underneath component wiring is allowed.
But a pin needs to be placed on a endpoint of a wire. If a pin is placed somewhere at the middle of the wire, the pin is not connected to that wire. If you select and move the two wire endpoints connected to the right subcircuit, you will notice, that they are not connected to the pins of the left subcircuit.

**Comment by wmuece** [comment]
Yes, but the issue is how to make a pin.  I couldn’t do it.

Therefore, I made the connections to w and x to each of the MUXes in wired1, which connected fine.  Then I MOVED the connected wires up to make the flat positions under the MUXes to look like Wired2, they suddenly became disconnected.

Not sure how to do this…

-Dean

On Sep 21, 2020, at 2:09 PM, Helmut Neemann <notifications@github.com<mailto:notifications@github.com>> wrote:



Underneath component wiring is allowed.
But a pin needs to be placed on a endpoint of a wire. If a pin is placed somewhere at the middle of the wire, the pin is not connected to that wire. If you select and move the two wire endpoints connected to the right subcircuit, you will notice, that they are not connected to the pins of the left subcircuit.

**Comment by xotmatrix** [comment]
See #486
