### ISSUE TITLE
3-state logic gates possible?

### ISSUE THREAD

**Issue by jwhsu01** [hneemann/Digital#515]
I'm relatively new at digital simulation. As a learning experience, I am trying to simulate the logic of a 74S281 ALU (logic diagram below):

![image](https://user-images.githubusercontent.com/71298176/93819416-adebec80-fc29-11ea-9f2b-c8a289f8619c.png)

My question centers on the AND gate connected to R/L, the OR gate connected to L/R, and the 4 XOR gates connected to F0-F3. All of these lines are both input and output lines. The problem arises when an input of the wrong parity is sent to the connected gate (gate is 0, input is 1, etc.) My understanding is this would require a 3-state logic gate to correct. Given there is no 3-state logic gate (except for buffers), is there any way to allow for input and output with the same line as shown in the diagram? Thanks.

**Comment by hneemann** [comment]
There is no AND or OR gate with a built-in 3-state output in Digital. 
You have to build them yourself by using the gate and a buffer like this:

![z](https://user-images.githubusercontent.com/7190563/93850495-8428d900-fcae-11ea-8e92-660e7b432529.png)
