### ISSUE TITLE
Help to use Digital Simulator

### ISSUE THREAD

**Issue by abnerbarros** [hneemann/Digital#518]

**Comment by abnerbarros** [comment]
I am encountering a problem when trying to use asynchronous JK FF in a simple counter. Each time I restart the simulation, the FF starts with a different value. This is the first time that I am using this simulator, it probably must be an error on my part, but I didn’t get anything telling me how to ensure that asynchronous FFs are correctly reset at the beginning of the simulation.

**Comment by hneemann** [comment]
If you have built your own JK-flopflop, you have to integrate a reset input to bring the circuit into a defined initial state after power-on. A completely symmetrically constructed JK flip-flop does not have a defined initial state.

And even then, a circuit with flipflops that start in a defined way can have an undefined initial state, because edges can appear during the power-on process that change the initial state of a flipflop.

**Comment by abnerbarros** [comment]
I realized that the problem only occurs when I invert the clock bit so that it is sensitive to downward transition. When I use the clock in the ascent transition it always works correctly.
In this way all is ok.
![image](https://user-images.githubusercontent.com/47617233/94265725-69a16a80-ff0f-11ea-9f07-d2e9e3df5cb7.png)
But in this way no.
![image](https://user-images.githubusercontent.com/47617233/94265867-a1101700-ff0f-11ea-822d-483156de8efd.png)

**Comment by abnerbarros** [comment]
In fact I have now verified that the problem occurs in both cases, only that it is more frequent when the clock is inverted. The circuit really does not seem to respond correctly reset proccess, each time I restart it is in a different state.

![image](https://user-images.githubusercontent.com/47617233/94267130-7030e180-ff11-11ea-8112-ac51b0e24657.png)
![image](https://user-images.githubusercontent.com/47617233/94267157-7a52e000-ff11-11ea-81b7-f95d82bb1803.png)
All FF is configured to star with 0.

**Comment by abnerbarros** [comment]
I identified the problem and found a palliative solution.
The problem occurs when starting the clock component in manual mode. Apparently it is generating glitches, which causes FF to change states.
The solution was to ensure that these pulses were not propagated. However, for me the best way would be to ensure that the FFs remain in the reset state waiting until the simulation is fully started

![image](https://user-images.githubusercontent.com/47617233/94268737-00702600-ff14-11ea-950d-f9a7fe4fc4a7.png)

**Comment by hneemann** [comment]
Your observations are correct, but it is not a bug. It behaves exactly as it should.
The JK flip-flops are completely independent of each other. There is no hidden logic that initializes the jk-flipflops with a synchronous reset pulse. To provide such a circuit with a stable initial state, a reset circuitry must be added.
Or you build a synchronous counter. That would certainly be the more elegant way.

**Comment by abnerbarros** [comment]
I work in my discipline with synchronous and asynchronous accountants, so I need to present both models to my students.
With regard to FF, it is expected that those that do not have asynchronous inputs will have some type of initialization logic, also because the component itself has the option of indicating an initial state. Anyway it seems to me that my problem was not due to the FFs, but to the clock component in manual mode.

**Comment by hneemann** [comment]
I would think that the clock component has nothing to do with it. 
If J and K are held at zero during startup, a glitch at the C input has no effect.
