### ISSUE TITLE
It's not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by lucaslopespj** [hneemann/Digital#519]
Everytime I try to run Digital I get this error:

Is Digital compatible to Ubuntu 20.04?

![image](https://user-images.githubusercontent.com/25344911/94181703-3fe83500-fe76-11ea-84bd-8fab918bb76d.png)

Thank you!

**Comment by hneemann** [comment]
Please read the `_ReadMeFirst.html` file contained in this folder.

**Comment by lucaslopespj** [comment]
Thank you very much! 
I've absolutely missed this file.
Everything is working fine right now!
