### ISSUE TITLE
Signed division

### ISSUE THREAD

**Issue by d-teif** [hneemann/Digital#525]
Hi,

Signed division component, for negative numbers ,calculate mathematic modulo, different from C or mips assembler signed division:

For exemple -5 /2 => -3 and 5 mod 2 = 1    => -3*2 + 1 = - 5

In C or mips   -5/2=_2  and -5 mod 2 = -1   => -2*2-1=-5

It will be great to have option in division component for exemple Mathematical (like now) / Programming (C,java) result ?

Thanks in advance

**Comment by hneemann** [comment]
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/).
