### ISSUE TITLE
Text size jumps around when zooming

### ISSUE THREAD

**Issue by maltaisn** [hneemann/Digital#539]
The text size jumps around depending on the zoom level. This can be annoying because sometimes the text doesn't overlap the circuit for certain zoom levels, and for others it does. Would it be possible to add this line in [`GraphicSwing.java`](https://github.com/hneemann/Digital/blob/master/src/main/java/de/neemann/digital/draw/graphics/GraphicSwing.java#L45) to make font size consistent across zoom levels?
```java
gr.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
```
I don't think this will affect performance too much. It also seems to slightly improve text rendering at small sizes.

**Comment by hneemann** [comment]
Which OS do you use? On my machine it makes no difference at all.

**Comment by maltaisn** [comment]
Ubuntu with OpenJDK 11. The same happens on Windows (still with OpenJDK 11). Here's what happens so you can compare:
- Current:
![bug](https://user-images.githubusercontent.com/33690959/97114777-e8352780-16c8-11eb-95a4-610ce200a934.gif)
- With fractional metrics:
![bug2](https://user-images.githubusercontent.com/33690959/97114783-f420e980-16c8-11eb-8263-c8bba0c80881.gif)

**Comment by hneemann** [comment]
Would you please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/) build?

**Comment by maltaisn** [comment]
It works correctly in the latest build.
