### ISSUE TITLE
Compatibility with Java 8 u271

### ISSUE THREAD

**Issue by jwhsu01** [hneemann/Digital#542]
Updated to Java 8 rev 271 today. Digital still works, however, I now cannot access the "Library" folder under the "Components" menu. I can still access all the other folders and the "Custom" folder. Was something changed in the latest version of Java which prevented access to the "Library" folder?

**Comment by hneemann** [comment]
Not that I'm aware of!
But i have moved the location of the library folder in v0.25. 
If this causes the problems you can go to Edit->Settings->Advanced and select your library location in the top most combo box.

**Comment by jwhsu01** [comment]
Got it to work by moving the "lib" folder to a different location. It is weird because on some directories, the dialogue box is completely blank, while in others, included folders show up for selection. (BTW, this is on OSX Mojave)

**Comment by hneemann** [comment]
This problem seems to be solved. If there are more problems, just open it again!
