### ISSUE TITLE
Generic Circuits Parameterization doesn't work

### ISSUE THREAD

**Issue by jay20162016** [hneemann/Digital#545]
<img width="448" alt="Screen Shot 2020-11-03 at 11 09 25 AM" src="https://user-images.githubusercontent.com/20290260/98010730-0a176400-1dc5-11eb-835e-19de27e0411b.png">
<img width="230" alt="Screen Shot 2020-11-03 at 11 10 13 AM" src="https://user-images.githubusercontent.com/20290260/98010802-26b39c00-1dc5-11eb-98da-71887cd6463b.png">
The semicolon is there, but the parameterization doesn't read it.

**Comment by hneemann** [comment]
The error message says that there is an error in a component "Out (Y)". 
However, the attribute window shows the attributes of a component "NOT_1.dig". 
What does the generic code of the component in the specified component "Out (Y)" look like?
There should be a component "Out (Y)" in the file "NOT_1.dig" which contains the bug.

**Comment by jay20162016** [comment]
oh, I seem to have forgotten a semicolon in NOT_1.dig. Thanks!
