### ISSUE TITLE
Quality of life features

### ISSUE THREAD

**Issue by mitolegy** [hneemann/Digital#548]
hi!
I've been using your program for a while now and i just though I'd suggest a few small quality of life features that would make using the program just that little bit easier. 

the first one is right click to toggle highlight a wire. i see that there's already a highlight system but its flaky and and using the drag select only works until you hit a turn. having the ability to right click to toggle highlight an entire wire from output component(s) to input components(s) would be really useful while debugging large circuits. especially unintegrated circuits.

the second feature is one straight out of Logisim. rotate component with arrow keys. the arrow keys aren't used when building a circuit anyway, and having to go into a menu and choose and angle is unintuitive and slow.  rotating them with the arrow keys while you're holding the component would be much more intuitive. 

food for though i guess. love the program. great work :)

**Comment by hneemann** [comment]
> i see that there's already a highlight system but its flaky

There was a bug in calculating the catch radius of the wire tool tips that I fixed just a few days ago. 
Please enable the Wire Tool Tips in the settings and try again with the latest [pre release](https://infdigital.dhbw-mosbach.de/).
And please let me know if it makes a difference for you.

> ... and having to go into a menu and choose and angle is unintuitive and slow.

It is possible to use the [R] key to rotate a component.
