### ISSUE TITLE
Recent colors palette broken, corrupts project.

### ISSUE THREAD

**Issue by xotmatrix** [hneemann/Digital#552]
Recent colors palette doesn't seem to be working correctly. It doesn't show recent colors between accesses and the colors it shows are invalid.
![javaw_2020-11-09_12-31-54](https://user-images.githubusercontent.com/14209329/98576037-f8800180-2287-11eb-923f-ea9f6da78437.png)
Selecting one the recent colors assigns the component an invalid color.
![javaw_2020-11-09_12-32-10](https://user-images.githubusercontent.com/14209329/98576043-fa49c500-2287-11eb-9cb4-bf1c344a2940.png)
At this point the component cannot be edited.
![javaw_2020-11-09_12-32-25](https://user-images.githubusercontent.com/14209329/98576049-fb7af200-2287-11eb-83e7-bf55c4772f2e.png)
If the project is saved, it becomes corrupt.
![javaw_2020-11-09_12-26-28](https://user-images.githubusercontent.com/14209329/98576200-3aa94300-2288-11eb-994c-64cda0d27c62.png)
This:
![notepad++_2020-11-09_12-30-08](https://user-images.githubusercontent.com/14209329/98576208-3da43380-2288-11eb-9468-d0587975a829.png)
... should be:
![notepad++_2020-11-09_12-38-39](https://user-images.githubusercontent.com/14209329/98576452-8c51cd80-2288-11eb-98f2-c175ca5a014f.png)

This appears to affect all components that can accept a color. It also affects the circuit specific background color setting and prevents that settings panel from working as well.

Build git-Revision: v0.25

**Comment by hneemann** [comment]
I have never tried to use the recent color palette! 
Thanks for pointing this out.
