### ISSUE TITLE
Finite State Machine Issue

### ISSUE THREAD

**Issue by mbmartin44** [hneemann/Digital#557]
Hello. On mac OSx, when i go to the finite state machines from the analysis menu, there is nothing that allows me to add a state. Specifically the right click does not create states as suggested from the help menu. I've tried a few different things but to no avail, including deleting and redownloading the application.

**Comment by hneemann** [comment]
On a Mac you have to use CTRL-Click instead of Right Click.
If you want to change that, it is possible to uncheck the "Use macOS mouse clicks" check box in the settings.
