### ISSUE TITLE
Is a High-Z constant possible and desirable?

### ISSUE THREAD

**Issue by xotmatrix** [hneemann/Digital#558]
I'm working on a bus-oriented design and sometimes I want to place some bus lines in a High-Z state through a Splitter/Merger. I've seen some similar questions and suggestions posted here. I don't understand some of the simulation difficulties in addressing their issues but I did find some workarounds that allow my embedded circuits to communicate High-Z bit states through their bussed inputs and outputs.

The first workaround I tried was using a disabled Driver. This works OK and is nice for outputting multiple bits but its meaning in the schematic is confusing.

The second workaround I tried was using an open Switch. This works as well and is a little more clear but it takes up a lot of space, especially for multiple bits.

Then I landed on using a floating Fuse. It is as compact as a Constant Value but can't address more than one bit. I'm pretty happy with this solution although using a floating Fuse this way seems more like a bug than feature.
![javaw_2020-11-15_15-21-41](https://user-images.githubusercontent.com/14209329/99196019-9deb1780-2757-11eb-8094-85e0d67fad33.png)

I found what I really wanted was for the Constant Value component to be able to express a High-Z state. 
Or perhaps an X symbol explicitly indicating something is disconnected as can found in software like KiCAD.

**Comment by hneemann** [comment]
Although it is very easy to implement, it somehow feels wrong:

![zz](https://user-images.githubusercontent.com/7190563/99250671-583c5680-280c-11eb-829f-0ed0a5e16a42.png)

But your workaround also feels wrong and should be fixed somehow.

**Comment by hneemann** [comment]
@xotmatrix 
Please try the latest pre release [v0.25-114-g6acf491](https://infdigital.dhbw-mosbach.de/).
It allows to flag a wire as "Not Connected". Please let me know how it works.

**Comment by xotmatrix** [comment]
Seems good although I've noticed things are behaving a little differently with multiplexers. 

In v0.25 the multiplexer is turning Z into 0.
![javaw_2020-11-19_06-09-23](https://user-images.githubusercontent.com/14209329/99658968-2b678980-2a2e-11eb-9fab-8ee8a57df87f.png) ![javaw_2020-11-19_06-15-50](https://user-images.githubusercontent.com/14209329/99659328-b779b100-2a2e-11eb-9fae-70aa2f9e0e07.png)

In 114-g6acf491 the multiplexer is turning Z into seemingly random values that change each iteration.
![javaw_2020-11-19_06-06-33](https://user-images.githubusercontent.com/14209329/99659226-8bf6c680-2a2e-11eb-9249-4ea4301281cd.png)

I can't really say that either is wrong, it's just an observation. I do not believe a real multiplexer is capable of passing a Z input to its output.

**Comment by hneemann** [comment]
That's the main reason why I don't like to allow open inputs in the first place:In my lab exercises, students sometimes rely on open inputs behaving as if they were connected to ground because that's what happens in the simulator. They are then very surprised that this is not the case in a real circuit.  In a real circuit, an open input behaves in a way that is difficult for students to understand: Sometimes the input seems to be read as high, and a moment later it seems to be low. And sometimes this changes when you move your hand over the circuit.
So I thought that if I make open inputs more easily available, they have to behave more like a real open input: one cannot rely on a value.

**Comment by hneemann** [comment]
closed in 57deba5465be35c9c22a9475a2ade297784014aa
