### ISSUE TITLE
Two-connector LED has a broken resistor?

### ISSUE THREAD

**Issue by xotmatrix** [hneemann/Digital#559]
The two-connector LED looks like it has a resistor on its cathode but doesn't act quite like it when connected to ground. I was trying to use the LED as a bus status display as well as a pull-down resistor but it does not function that way. At first I thought its appearance was merely misleading. However, a pull-down resistor connected to the LED's cathode end does not function as expected. Seems like a bug but I also recognize the simulator's handling of passives is very limited.
![2020-11-15_15-57-34](https://user-images.githubusercontent.com/14209329/99196630-a5142480-275b-11eb-80b4-8056f42298e1.png)
![2020-11-15_15-57-48](https://user-images.githubusercontent.com/14209329/99196633-a6dde800-275b-11eb-8feb-029e9e71340c.png)
![2020-11-15_16-10-53](https://user-images.githubusercontent.com/14209329/99196911-2cae6300-275d-11eb-877f-1347f8039d42.png)

**Comment by hneemann** [comment]
Digital is not a simulator for analog circuits. 
If you want to simulate real resistors you have to use something like Spice.
In Digital, a pull-down resistor is just a flag to indicate that the network it is connected to has to be set to low when all other connections to the network are in the high-Z state. That's it.
The LED with series resistor is simply an indicator that has no other function. You can't use this LED e.g. to build a "wired or" or something like that either.

**Comment by xotmatrix** [comment]
I understand. I can see its utility though its suggestive shape is confusing.

**Comment by hneemann** [comment]
The shape was chosen that way because a real diode, if it is operated without a series resistor limiting the current, would be destroyed immediately.
