### ISSUE TITLE
Issue Exporting NOR Gate to HDL

### ISSUE THREAD

**Issue by ryancor** [hneemann/Digital#563]
I made a simple NOR gate out of PMOS and NMOS transistors, wanted to test out the HDL generator for this but I got this error, even after labeling the inputs and outputs. I'm using Digital through my MacOS Mojave.
<img width="1276" alt="Screen Shot 2020-11-20 at 1 39 00 PM" src="https://user-images.githubusercontent.com/15078524/99852563-19710e00-2b36-11eb-986c-1ab147ae24dd.png">

**Comment by hneemann** [comment]
Digitals HDL export does not support FET's. That would also make little sense.
Furthermore, no circuits are supported that require bidirectional ports in the HDL code.
Bidirectional ports are only supported on the top level of a circuit, and then only if the corresponding component (Pin Control) is used.
