### ISSUE TITLE
Visual glitches after usage of dropdown menu of component context menu

### ISSUE THREAD

**Issue by BenUnderscore** [hneemann/Digital#568]
There is a visual glitch that happens when I use a dropdown menu in a context menu. This would be acceptable, but after I close the menu, hoverying over any button (in the ribbon bar at the top) draws the component grid with it at the top left.
![image](https://user-images.githubusercontent.com/20223407/100540872-cccdb700-3248-11eb-9444-d5c3828920a4.png)
![image](https://user-images.githubusercontent.com/20223407/100540918-20d89b80-3249-11eb-9f6e-aef97456db1e.png)

I'm running Windows 10 10.1.19041 with Digital v0.25 and JRE v8u271, but I have confirmed the bug to exist on earlier versions of Digital as well, as far back as 0.16. Running the noD3D version seems to behave the same.
I can confirm that the register, counter and adder have this problem, but for whatever reason not the ROM.

**Comment by hneemann** [comment]
seems similar to #227

**Comment by hneemann** [comment]
The problem is that these dialogs are implemented using the unmodified Java Swing components. 
Nothing special is done with them. So I don't think that the problem can be solved that easily.
Does the problem always appear or only from time to time?

**Comment by BenUnderscore** [comment]
It appears reproducibly every time, which makes the program basically unusable unless it can be fixed. If it's a Swing issue maybe using a different version of Java might help?

**Comment by hneemann** [comment]
That would have been my next advice. JDK 14 and 15 I have tested both successfully. I personally still use JDK 11.

**Comment by hneemann** [comment]
See #227
