### ISSUE TITLE
Blank window on dwm

### ISSUE THREAD

**Issue by HassanZahin** [hneemann/Digital#570]
Digital is working fine on kde plasma. But when I try to open it in dwm, it just shows a blank window.

**Comment by hneemann** [comment]
Please read this [thread](https://bbs.archlinux.org/viewtopic.php?id=251721) and let me know if it solves the problem.

**Comment by hneemann** [comment]
This is maybe the same issue as #547

**Comment by HassanZahin** [comment]
> Please read this [thread](https://bbs.archlinux.org/viewtopic.php?id=251721) and let me know if it solves the problem.

Thanks, it solved it.



> This is maybe the same issue as #547

I don't think so as he is using gnome and gnome is re-parenting. I'm not sure about the wayland part though.

**Comment by HassanZahin** [comment]
@hneemann Just checked in plasma wayland. Seems to work fine

**Comment by hneemann** [comment]
> I don't think so as he is using gnome and gnome is re-parenting.

I have already thought the same. But the immediate closing of the menus would fit perfectly.
