### ISSUE TITLE
Feature request: autogenerated timing diagrams from truth tables

### ISSUE THREAD

**Issue by eliask05** [hneemann/Digital#572]
Digital automatically generates truth tables for combinational circuits. Is it possible to add a feature that presents the same information in the form of a timing diagram upon request?

**Comment by hneemann** [comment]
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/).

**Comment by hneemann** [comment]
At the moment, I tend not to merge this feature, as this diagram can be very confusing when the table describes a state machine.
The complete timing diagram may contain the states in a different order than they occur in the state machine, and may also contain states that do not occur in the state machine at all.

**Comment by eliask05** [comment]
Understood and agreed. I was talking about combinational circuits, only.
