### ISSUE TITLE
Aesthetic Improvement for wires switching faster then screen refresh rate

### ISSUE THREAD

**Issue by mitolegy** [hneemann/Digital#578]
just a small thing really. but I was just wondering if it would be possible to visualize wires switching states faster then the visual refresh rate as a sort of intermediate color. maybe just a combination of the HIGH and LOW wire color. or the HIGH and LOW color switching every frame regardless of the actual state of the wire. just to visualize that this wire is switching real fast. rather then the intermittent semi random look they'll take on now where they'll just kind of jump between HIGH and LOW depending on whatever state the wire was in the last time Digital decided to update the screen.

this is purely an aesthetic feature. I just think it would make the simulator look a bit better :)

**Comment by hneemann** [comment]
This is an interesting idea. However, it is not so easy to implement. The actual simulation runs in a separate thread and the graphical representation in another. Whenever the graphic is to be updated, the simulation is stopped for a short period of time and the current state of the visual components is read out, which is very fast. Then the simulation continues while the graphic is being drawn, which takes a comparatively long time. When the graphic is finally finished, and at least 100ms have passed, the simulation is stopped again to read the next state, and so it goes on and on.
This means that the graphics thread doesn't even notice if the state of a wire has changed in the meantime. If I want to detect this, I would have to monitor the state of a wire permanently, like the gates do, and that would cost runtime. After a first test in the example processor about 6%. That seems too much for a visual effect.
But I will think about whether it can be done faster. 
However, there is hardly any difference in how the example processor looks when it is running.
