### ISSUE TITLE
Subcircuit Symbol Too Small

### ISSUE THREAD

**Issue by SteveMillman** [hneemann/Digital#579]
I've got a simple sub circuit with two inputs and two outputs. I instantiate it in its parent module and the box is so small that the input and output names overlap despite being only three characters. Is there an easy way to get Digital to make the box bigger? The bottom input is INC and the bottom output is CRY. You can see that the Cs are on top of each other.

<img width="117" alt="too_small" src="https://user-images.githubusercontent.com/74130819/102584681-2ac12200-40c4-11eb-8a60-c3d743cd6676.png">

It really isn't an option to have students editing the SVG files, so I'm hoping I've missed something important. In the sub circuit, the inputs and outputs are spaced apart vertically, so I don't think it's because they are too close together. Zooming in  doesn't help either - the letters grow with the box. Any suggestions would be helpful.

Thank you,

Steve

version: v0.25

**Comment by hneemann** [comment]
Open the sub circuit and adjust the width in the circuit specific settings (Edit->Circuit specific settings)

**Comment by SteveMillman** [comment]
Perfect! Thank you!
