### ISSUE TITLE
I can haz Flip?

### ISSUE THREAD

**Issue by gbizzotto** [hneemann/Digital#587]
There's Edit > Rotate.
Flip would come handy.
Even if only for wires.
Just one flip. No need for vertical AND horizontal. One is a rotation of the other, and we already have rotate.

**Comment by xotmatrix** [comment]
This would be nice. It would also be nice if it could flip components that have the option to, such as drivers and plexers.

**Comment by hneemann** [comment]
Some components already have a "mirror" option. Only the components that already had another option to achieve the same appearance do not have it, because that would not make sense. 
And for compatibility reasons I can't remove the older "Flip Selector Position" option.

**Comment by gbizzotto** [comment]
I was thinking about the wires. Sometimes I have a bunch of, say, horizontal wires that all start on the left at the same X, and stop on the right at incrementing Xs, so I can redirect all of them up (or down) in a parallel fashion. That takes time to draw, even with copy/paste.
Sometimes I want to flip them all, so, if they're set up so i can redirect them up, i'd like to now redirect them down. Without flip, the only way I can do that afaik is by deleting  and redrawing everything.

The picture below illustrates this.

![Screen Shot 2020-12-22 at 08 56 02](https://user-images.githubusercontent.com/5064376/102886383-c095dd80-4433-11eb-9a1b-e6bb524c69e3.png)

While I was drawing this example, I realized I can't even copy, rotate and paste those wires to redirect them up. I already need to flip them.

![Screen Shot 2020-12-22 at 08 57 19](https://user-images.githubusercontent.com/5064376/102886393-c68bbe80-4433-11eb-9c73-e9cd7b7ca9a2.png)

**Comment by hneemann** [comment]
There are components like Text, Rectangle and others where a flip makes no sense. 
If such a component is in the selection, there is no elegant way to deal with this.
