### ISSUE TITLE
Delay embedded

### ISSUE THREAD

**Issue by edson-acordi** [hneemann/Digital#595]
Suggestion for enhancement:
It would be good to have an option to adjust the delay directly in attributes of each logic gate or integrated circuit.

**Comment by hneemann** [comment]
If I were to implement this, it would also need to be clarified what should happen if the inputs change before the propagation time has expired. This also depends on the specific signal and also on the technology used. 
It would make the simulator slower and I myself don't need it for my lectures. If I want to demonstrate something with a delay, I add it as a visible element. I think this is easier for the students to understand.
