### ISSUE TITLE
Add Zero extender to complement Sign extender

### ISSUE THREAD

**Issue by gixslayer** [hneemann/Digital#597]
While working on a project I've found myself needing to zero extend an input signal to a greater bit count several times. This can easily be done with the combination of a Splitter/Merger and Constant value set to zero for the added upper bits, which can even be captured in a generic circuit to allow variability of the number of input/output bits, but I felt a dedicated component for this was missing. I think it would be a nice addition to the standard components, and form a logical counterpart to the already existing Sign extender. 

As said it is easy to come up with working alternatives, but it would be nice if such a basic (and somewhat common?) operation was readily available in a concise component that doesn't needlessly clutter the circuit, and had nice GUI integration (not requiring modifying the generic instantiation code). 

In terms of code I presume it would look something like the following (modified `BitExtender` code).

```.java
/**
 * Zero extension component.
 * Is not a node because it is just a special kind of wiring.
 */
public class ZeroExtender implements Element {

    /**
     * Description of the zero extend component.
     */
    public static final ElementTypeDescription DESCRIPTION
            = new ElementTypeDescription(ZeroExtender.class, input("in"))
            .addAttribute(Keys.ROTATE)
            .addAttribute(Keys.LABEL)
            .addAttribute(Keys.INPUT_BITS)
            .addAttribute(Keys.OUTPUT_BITS);

    private final ObservableValue out;
    private final int outBits;
    private final int inBits;

    /**
     * creates a new instance
     *
     * @param attr the components attributes
     */
    public ZeroExtender(ElementAttributes attr) {
        outBits = attr.get(Keys.OUTPUT_BITS);
        out = new ObservableValue("out", outBits).setPinDescription(DESCRIPTION);
        inBits = attr.get(Keys.INPUT_BITS);
    }

    @Override
    public void setInputs(ObservableValues inputs) throws NodeException {
        final ObservableValue in = inputs.get(0).checkBits(inBits, null);
        if (inBits >= outBits)
            throw new NodeException(Lang.get("err_notMoreOutBitsThanInBits"));

        in.addObserver(new NodeWithoutDelay(out) {
            @Override
            public void hasChanged() {
                out.setValue(in.getValue());
            }
        }).hasChanged();
    }

    @Override
    public ObservableValues getOutputs() {
        return out.asList();
    }

    @Override
    public void registerNodes(Model model) {
        // has no nodes! Is just wiring
    }

}
```

Perhaps the `BitExtender` component could even be made a bit more generic instead, offering an attribute to extend with the sign bit, constant 1, or constant 0. I'm not sure how many actual use cases there would be for that outside the zero/sign extend cases, so perhaps two dedicated components is a better alternative anyway.

**Comment by hneemann** [comment]
To be honest, the variant with the splitter/merger seems much more readable to me than hiding this function in a component (see #206).
This is quite different with a sign-preserving extension. This becomes very confusing by using a splitter/merger.
