### ISSUE TITLE
Updating French translation

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#613]
@maltaisn 
in the near future I would like to publish a new release. Therefore the request for updating the translation.

There is a complicated change, because the test cases have been extended significantly. Unfortunately this is a long text and the changes are not obvious.

At the beginning a heading with `<h3>General</h3>` was added and at the end an explanation of the new `declare` statement was added. After that you will find the heading `<h3>Processors</h3>` with a new short chapter.

It would be nice if you could complete the translation.

[lang_diff_fr.xml.zip](https://github.com/hneemann/Digital/files/5813124/lang_diff_fr.xml.zip)

It is easiest if you send the translated file back to me by email or as a reply to this ticket.

**Comment by maltaisn** [comment]
Sure, I'll have some time later today.

**Comment by maltaisn** [comment]
[lang_diff_fr.zip](https://github.com/hneemann/Digital/files/5816665/lang_diff_fr.zip)
