### ISSUE TITLE
A big thanks, and some thoughts

### ISSUE THREAD

**Issue by ruabmbua** [hneemann/Digital#62]
Dear developers,

as a fellow developer I can not say anything else, but thanks for your great work!
I really appreciate this new and greatly improved "spinoff" of the original logisim digital circuit simulator.

Today I stumbled over your project, and it caught my attention instantly, by listing other forks of the logisim simulator on the main page.
After trying it out for a little bit, I am convinced, that I will get back into developing my custom CPU I designed in logisim a couple of years ago.

If this simulator can really avoid some of the simulation problems, that logisim has, then this is almost perfect. Also I am really excited about the "Debugger Interface" feature. When I finish poring my old logisim CPU to this simulator, then supporting hardware break points will be my priority Nr 1. Even if I have to extend the current *break* feature a little bit.

Here some things, which I think could be improved:

- The UI is good, and usable, but in some parts not particularly intuitive
- Prominence of the project: Why did I not hear about this before? I know the first release is from 2016, but I can remember searching for a logisim replacement a couple of times, but never finding this (or it simply went under my radar somehow). Maybe ping @cburch, if he wants to consider adding a list of related projects, which are still maintained. I am sure Digital will stand out 👍 .

**Comment by hneemann** [comment]
See #83
