### ISSUE TITLE
Ability to copy and paste from "All possible solutions" window.

### ISSUE THREAD

**Issue by i4cy** [hneemann/Digital#621]
Excellent Software.
It would be useful to be able to copy and paste from "All possible solutions" window. Or better still offer an Export facility in much the same way the "Table" view is implemented.
Thanks.

**Comment by hneemann** [comment]
Try "File->Export Plain Text" in the table dialog.

**Comment by i4cy** [comment]
I just found that out myself while playing. But thanks, for coming back so quickly to confirm.
