### ISSUE TITLE
feature request: Importing (and maybe exporting) truth table from Logic Friday format

### ISSUE THREAD

**Issue by Ryder17z** [hneemann/Digital#631]
Example file:
```
A,B,C,D,E,G,F,,F0,F1,F2,F3
0,0,0,0,X,1,0,,1,0,0,0
0,0,0,0,0,1,1,,1,0,1,0
0,0,0,X,1,1,0,,0,0,1,0
1,1,1,X,0,1,1,,0,0,1,0
0,0,X,1,1,0,1,,0,0,1,0
1,0,0,1,0,X,0,,0,0,1,0
0,1,0,0,0,1,X,,0,0,1,0
X,0,0,1,1,1,0,,0,0,1,0
0,0,1,1,1,X,1,,0,0,1,0
0,X,0,0,1,0,0,,0,0,1,0
1,0,1,0,1,X,0,,0,0,1,0
1,1,1,1,1,X,X,,0,0,1,0
1,X,1,0,X,0,0,,0,0,1,0
1,1,1,0,0,X,X,,0,0,1,0
1,X,1,0,0,X,1,,0,0,1,0
X,X,X,X,1,X,1,,0,1,0,1
0,X,X,X,X,X,X,,0,1,0,0
X,X,0,X,X,X,X,,0,0,0,1
```

A-F denotes Inputs
F0-F3 denotes Outputs

,, double commas is just a separator used to determine what's inputs and what's outputs

The states 0/1/X are what you would expect.

**Comment by hneemann** [comment]
Your example is not a truth table. 
It is a description of prime implicants and a list of expressions in which they are to be used.

**Comment by Ryder17z** [comment]
It's not represented as one in plain-text, no. But this is still a "truth
table" if you load it into Logic Friday.

**Comment by hneemann** [comment]
LogicFriday 1.1.4 is not able to import your example.
It says: "Import Error: Conflict assigning an output value at line 4. A different value was assigned previously."

**Comment by Ryder17z** [comment]
Hmm. Odd. It was exported from it.
