### ISSUE TITLE
Option for hiding library circuits

### ISSUE THREAD

**Issue by YulienPohl** [hneemann/Digital#638]
When creating circuits in the library folder you often create subcircuits 
which are not used elsewhere and are cluttering the component tree.

One could use the custom tree to hide them from the library
which could be set in the circuit specific settings.

**Comment by hneemann** [comment]
The query of the circuit specific settings would be very slow, because the file would have to be loaded.
Therefore this must be controlled by the file name.
If the file name ends with "-inc.dig", it will not be displayed in the menu.
