### ISSUE TITLE
Two wires with opposite charges can meet without short circuiting

### ISSUE THREAD

**Issue by jay20162016** [hneemann/Digital#640]
<img width="267" alt="Screen Shot 2021-02-08 at 4 01 13 PM" src="https://user-images.githubusercontent.com/20290260/107281272-71c5f680-6a27-11eb-854f-36b67380f952.png">
Previously this caused a short circuit. Now it acts as "wired or".

**Comment by hneemann** [comment]
introduced while fixing #551
