### ISSUE TITLE
Timing diagrams in asynchronous mode don't report oscillations until it stabilizes

### ISSUE THREAD

**Issue by jay20162016** [hneemann/Digital#641]
<img width="821" alt="Screen Shot 2021-02-08 at 5 30 59 PM" src="https://user-images.githubusercontent.com/20290260/107289700-6d9fd600-6a33-11eb-948d-44c12127d74a.png">
The timing diagram doesn't continue to scroll. Only stopping the oscillation (A -> 0) will make the timing diagram continue scrolling.

**Comment by hneemann** [comment]
If you want to use the timing diagram in Async mode, you have to activate the option "Show single gate steps".
In Async mode the circuit often does not stabilize and without this option the diagram shows only stabilized states.
