### ISSUE TITLE
Floating Point format not accepting inf & nan

### ISSUE THREAD

**Issue by YulienPohl** [hneemann/Digital#647]
pre-release version v0.26-62-gcb28135

When inputing an exponent of -1 (0x7f800000) in the binary field the input sets to zero.
The current workaround is when inputting hex 0x7f800000 directly.

**Comment by hneemann** [comment]
In IEEE 754, the exponent is encoded in offset binary representation, where the zero offset at 32 bits is 127.
Thus all exponent bits set do not mean -1, but 128. :smile: 

But this behavior is nevertheless an bug.
