### ISSUE TITLE
Oscillation error in counter

### ISSUE THREAD

**Issue by YulienPohl** [hneemann/Digital#649]
pre-release version v0.26-64-g59a1577

When the counter value is max the overflow flag oscillates if you have a circuit like this one.
Affected are both counters.

![bug](https://user-images.githubusercontent.com/37116826/107884820-48a9d800-6ef7-11eb-9eac-57c8b658f9aa.png)

**Comment by hneemann** [comment]
This behavior is exactly what you would expect. This is what such a counter looks like:

![counter](https://user-images.githubusercontent.com/7190563/107886021-b78a2f80-6efd-11eb-8a1b-ea4f06465669.png)

**Comment by YulienPohl** [comment]
Okay, this means the only way to stop the counter before overflowing is to use a comparator with 2^n -1.

**Comment by hneemann** [comment]
You could also use the ovf output to trigger a FF that stops the counter. This depends on your requirements.
