### ISSUE TITLE
Selection rectangle remains visible after releasing mouse button

### ISSUE THREAD

**Issue by JarrettBillingsley** [hneemann/Digital#65]
version: v0.14-75-g63b144b-dirty

It's a little weird, after letting go of the mouse, the rectangle is still there. I don't know any other program that does this.

**Comment by hneemann** [comment]
This behavior is intended. It has its origin back in the days when there was no undo function. 
At that time (prior to v0.12), you had to check your selection carefully before making any changes. ;-)

**Comment by JarrettBillingsley** [comment]
Hahaha
