### ISSUE TITLE
Option for default setting of wide shape

### ISSUE THREAD

**Issue by YulienPohl** [hneemann/Digital#658]
This could be set in Settings -> Basic

**Comment by hneemann** [comment]
In the past there was such an option, which I removed. 
This option is only required to open a circuit that was created with a different shape type than the one that is currently selected. And this basically means that a circuit created in Germany can also be opened e.g. in the US and vice versa.
In such a case, the shapes do not really match the standard, but at least the circuit works.

See also #469

**Comment by YulienPohl** [comment]
OK, too bad.
So time go back and copy the circuits.😄
