### ISSUE TITLE
Better way of inputting values on multi-bit inputs

### ISSUE THREAD

**Issue by JarrettBillingsley** [hneemann/Digital#66]
It's very nice that I'm able to type in values for inputs (unlike poking 0s and 1s in Logisim), but it's clunky and slow. Right click, type in value, click apply, type in different value, click apply...

It would be great to be able to type the values right into the input, or even have up and down buttons for it, like a typical GUI spinner control, like this:

![image](https://user-images.githubusercontent.com/452240/31980564-61d5010a-b91b-11e7-97c7-e30cd6b4e006.png)

**Comment by hneemann** [comment]
@JarrettBillingsley 
What do you think about the usage of cursor keys in the single value dialog?

**Comment by JarrettBillingsley** [comment]
That helps!

**Comment by JarrettBillingsley** [comment]
I also wanted to ask, is there a faster way to build than `mvn install`?

**Comment by JarrettBillingsley** [comment]
Double-thanks!

**Comment by hneemann** [comment]
I forgot to mention: The pdf documentation is created during the test execution. So if you skip the tests you also skip the creation of the pdf's. Thus your distribution zip will contain an outdated or no pdf documentation.

**Comment by JarrettBillingsley** [comment]
Ohh, okay. Well that shouldn't be a problem for testing changes then :D

**Comment by hneemann** [comment]
If you want to play around with the code to test something, it is much easier to import the pom.xml to you IDE and to build from the IDE. In this case you don't have to use maven at all.
