### ISSUE TITLE
High Z processing: Latest update

### ISSUE THREAD

**Issue by HighEagle777** [hneemann/Digital#665]
Hi,
Again, thank you for this great software and the attention and support that you give to it.

After installing the latest update, my 8-bit computer project no longer functions. It turns out it is because of the new functionality of how gates handle the High Z state. For example, if I had an AND gate with a driver as one input and the clock as the second input, the output of the AND gate randomly oscillates between high (1) and low (0). 

It seems the only solution I have come up with is to connect a pull down resistor to the driver output to force it to low (0). However, the entire project has over 50 drivers. To connect pull down resistors everywhere is going to take a LOT of time and a LOT of clutter. Is there perhaps a better solution that I have not considered?

I can understand that from an electronic simulation point of view, this feature may be necessary.  However, I have always used Digital as a Logic Circuit simulator where a Z-State would be considered a "low (0)" until it is actively changed to high (1). For example, from a purely logic point of view, if the driver selector is "off" then the output should be considered "off" or a logic (0). Maybe if you could help me with some insight as to why the handling of the Z State has been changed to what it is now.

**Comment by hneemann** [comment]
How to deal with it when a high-Z value is applied to a gate is an open issue for a long time. In one of the first versions an exception was thrown and the simulation stopped. This seemed too strict to me. So I removed the exception, and added a comment with a ToDo. This is how it stayed for years.

Then I observed the following during my lab exercises: Students simulate a circuit and implicitly assume that High-Z is read as 0. The circuit works perfectly. Then they build the circuit with real gates, and observe an inexplicable behavior. The inputs seem to change randomly. Sometimes this causes amusement, when the circuit reacts to the moving of a hand above the circuit.

Then I thought that I could simply solve the long open issue by making the simulation behave exactly like a real circuit:
When an open input is read, the result is random and not determined.
I implemented this and am quite happy with it.
I don't think I will change it again.
