### ISSUE TITLE
Inconsistent behavior of short circuit?

### ISSUE THREAD

**Issue by avaccari** [hneemann/Digital#666]
version: v0.26

I found what it appears to be an inconsistent behavior in the short circuit detection.

In some cases connecting supply voltage to ground works, in some other cases it causes a short.

Is there something I'm missing?

I'm attaching two examples.

[Archive.zip](https://github.com/hneemann/Digital/files/6047077/Archive.zip)

**Comment by hneemann** [comment]
There is actually a bug that prevents a short from being detected when no component is involved.
This bug has already been fixed. Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/).

See also #640
