### ISSUE TITLE
Lists do not work with embedded circuits

### ISSUE THREAD

**Issue by YulienPohl** [hneemann/Digital#677]
Creating a list with newList in initialization does not work with embedded circuits.

**Comment by hneemann** [comment]
Hmm! Seems to work as expected. Please attach an example.

**Comment by YulienPohl** [comment]
It happens only if you create the circuit from the init/code and then simulate it.

**Comment by hneemann** [comment]
Reworking lists and maps i decided to remove the `newList()` function.
To create a new list the code now looks like this:
```
a:=[1,2,3];
```
