### ISSUE TITLE
Add an enable pin to Plexers

### ISSUE THREAD

**Issue by josephH00** [hneemann/Digital#681]
Hey, while doing several assignments for my digital electronics class I've needed to design several circuits that use decoders and other plexers that use an enable pin, this would help speed up those assignments where I could use Digital to help map and test them out.

**Comment by hneemann** [comment]
But it is very easy to add an enable input.

![zz](https://user-images.githubusercontent.com/7190563/111287577-a559f900-8643-11eb-8a03-81ee52a66afa.png)
