### ISSUE TITLE
It would be better for external component to automatically extract port information from the code

### ISSUE THREAD

**Issue by itviewer** [hneemann/Digital#687]
The [ensureConsistency](https://github.com/hneemann/Digital/blob/367ca703ed76ad513a697938a2422c1869fa8b45/src/main/java/de/neemann/digital/core/extern/ApplicationVerilogStdIO.java#L84) method has been able to extract port information from the code. The current logic only extracts port information when the user clicks the Test button. Maybe the user does not know this function. Before I discovered it, I would manually enter the port information every time.
It should be automated and the user is prohibited from entering port information.

Another feature suggestion is to read the code from an external file and automatically set the port information before the simulation starts. This avoids copying to Digital every time the code is modified in the external editor.

**Comment by hneemann** [comment]
The parser is very simple, and I'm not sure it could parse any correct code. And this is also difficult to test.
So I want to give the user the possibility to do the input manually if the parser fails.
