### ISSUE TITLE
Digital Translation, French

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#689]
@maltaisn 
in the near future I would like to publish a new release. Therefore the request for updating the translation.
It would be nice if you could complete the translation.

[lang_diff_fr.xml.zip](https://github.com/hneemann/Digital/files/6203836/lang_diff_fr.xml.zip)

**Comment by maltaisn** [comment]
[lang_diff_fr.zip](https://github.com/hneemann/Digital/files/6205896/lang_diff_fr.zip)
