### ISSUE TITLE
Digital Translation, Chinese

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#690]
@itviewer 
in the near future I would like to publish a new release. Therefore the request for updating the translation.
It would be nice if you could complete the translation.

[lang_diff_zh.xml.zip](https://github.com/hneemann/Digital/files/6203852/lang_diff_zh.xml.zip)

**Comment by itviewer** [comment]
[lang_diff_zh.zip](https://github.com/hneemann/Digital/files/6217469/lang_diff_zh.zip)

**Comment by hneemann** [comment]
@itviewer 
Thank you very much for your effort!

There is a problem with one entry:

en: "Expected {0} but found {1} values in line {2}!"
zh: "行 {2} 期待 {0} 个值"

The {1} parameter is missing, which causes a syntax error.

**Comment by itviewer** [comment]
update
[lang_diff_zh.zip](https://github.com/hneemann/Digital/files/6217544/lang_diff_zh.zip)

**Comment by hneemann** [comment]
@itviewer 
Thanks again!
