### ISSUE TITLE
Why is the output of Demultiplexer  changing all the time

### ISSUE THREAD

**Issue by kEviN1H** [hneemann/Digital#694]
A ROM is followed by a Demultiplexer. When the SEL of ROM is low, the output should be Ｚ(high Z state). Why is the output of Demultiplexer changing all the time?
What's the situation? Or what's the problem?

![ggg](https://user-images.githubusercontent.com/4837382/113736793-01d6a280-9730-11eb-880b-eb82fbaa587c.gif)

[ggg.dig.rename.zip](https://github.com/hneemann/Digital/files/6265795/ggg.dig.rename.zip)

**Comment by hneemann** [comment]
see #665
