### ISSUE TITLE
Menus break visuals of the simulator

### ISSUE THREAD

**Issue by aXYZGaming** [hneemann/Digital#699]
Quite inconsistently, drop-down menus or text boxes completely break the visual aspect of the simulation, making it hard to do anything.

![image](https://user-images.githubusercontent.com/79474483/114079404-73d2f700-98aa-11eb-8b1f-4973924cbe21.png)

**Comment by hneemann** [comment]
Are you using Windows 10? In this case this seems to be a duplicate of #227.

**Comment by aXYZGaming** [comment]
oh it does now that i look at it...
