### ISSUE TITLE
Slight mouse movements cause unintended behaviors, especially on HiDPI screens

### ISSUE THREAD

**Issue by guiweber** [hneemann/Digital#7]
- Drawing wires and deselecting the wire tool can be hard on a HiDPI screen. Clicking while the mouse is moving will trigger the selection box instead of the wire tool. Right clicking while the mouse is moving will move the schematic instead of triggering the deselect action. If you consider that 1px is the smallest mouse movement that is possible, then a much smaller physical movement is needed on a HiDPI monitor to move the mouse by 1px than on a regular HD screen at the same mouse sensitivity. On my 4k screen, I noticed that I see the selection box appear briefly when I try drawing a wire and it doesn't work. If I stand very still while I click or right click, everything works as intended. So what is considered a mouse movement that alters the non-moving behavior should probably be scaled with the pixel density.

- If the mouse moves slightly while selecting a component in the tree view, then the component is selected in the tree (greyed out) but the mouse is not moved back to the schematic and the component placement tool is not activated. When this happens, the tree view looks like this:
![image](https://cloud.githubusercontent.com/assets/7825368/26473336/db86d606-4178-11e7-806b-21e9ccaa85fb.png)

- The tree view issue happens even on a regular HD monitor, probably because of the larger mouse movement required to reach the selection zone, although less frequently than on a HiDPI monitor. I suggest removing the mouse movement detection in the tree view as there is no alternate behavior when moving the mouse anyway.

**Comment by hneemann** [comment]
fixed in v0.12
