### ISSUE TITLE
TestIO.dig and LED-matrix

### ISSUE THREAD

**Issue by kEviN1H** [hneemann/Digital#703]
TestIO.dig What's the difference between this file and another? Only in this file, LED-matrix will add a text box, and other files will not.
![frdcx 0](https://user-images.githubusercontent.com/4837382/114206140-a144a100-998d-11eb-97cf-a97a1108f65e.png)

**Comment by hneemann** [comment]
In the file with the additional text box in the circuit specific settings the checkbox "Circuit is generic" is set.
Uncheck this checkbox and the additional text field will disappear.
