### ISSUE TITLE
Documentation for expression syntax

### ISSUE THREAD

**Issue by Uberi** [hneemann/Digital#708]
First of all, huge fan of your work on Digital! Thanks for making a great piece of software that we use every day.

I would like to contribute a formal grammar for expressions in the "Test" component. It's based directly on the recursive descent parser in the source code (see "References" for details). I'm opening this as an issue because I'm not sure whether this is worth including, and where it would go if it is.

Potential ideas for contribution:

* Before writing this grammar, I had no idea that there were the built-in functions `ite()`, `signExt()`, and `random()`. **Potential improvement**: adding a brief explanation of what functions are available and what they do.
* I also did not know that the operator precedence was: <, <=, >, >=, =, !=, |, ^, &, >>, <<, +, -, *, /, %, and then all the unary operators. **Potential improvement**: adding information about what operators are available, and their precedence.
* I'm not sure if this is intentional, but the way the parser works now, once you use a `<` in an expression, you can't use `<=` afterwards in the same expression ([code](https://github.com/hneemann/Digital/blob/a2ab7f2848367b426f43ce923e8bb4b172fd0e8b/src/main/java/de/neemann/digital/testing/parser/Parser.java#L365)). Same thing for `>` and `>=`. If this is a bug, then one potential improvement is changing the parser such that `Expression` becomes `LessEqual ("<" LessEqual)*` instead.
* In theory, the existing parser could be replaced by a PEG parser generator (e.g., [Parboiled](https://en.wikipedia.org/wiki/Parboiled_(Java))) using this grammar, significantly reducing the amount of hand-written parsing code that needs to be written. However, I'm unsure how much work this would be, so I'll just float that as an idea for now.

Formal Grammar
---

```js
// Expression parsing
Expression
  = LessEqual ("<" Greater)*
LessEqual
  = Greater ("<=" Greater)*
Greater
  = GreaterEqual (">" Equal)*
GreaterEqual
  = Equal (">=" Equal)*
Equal
  = NotEqual ("=" NotEqual)*
NotEqual
  = Or ("!=" Or)*
Or
  = Xor ("|" Xor)*
Xor
  = And ("^" And)*
And
  = ShiftRight ("&" ShiftRight)*
ShiftRight
  = ShiftLeft (">>" ShiftLeft)*
ShiftLeft
  = Add ("<<" Add)*
Add
  = Sub ("+" Sub)*
Sub
  = Mul ("-" Mul)*
Mul
  = Div ("*" Div)*
Div
  = Mod ("/" Mod)*
Mod
  = Atom ("%" Atom)*
Atom
  = FunctionCall / Identifier / Number / "-" Atom / "~" Atom / "!" Atom / "(" Expression ")"

// Built-in functions:
// ite(condition, ifTrue, ifFalse) => condition != 0 ? ifTrue : ifFalse
// signExt(bits, value) => { let mask = (1 << bits) - 1; return (value & mask) | (value & (1 << (bits - 1)) ? ~mask : 0); }
// random(maxValue) => Math.random() * maxValue
FunctionCall
  = Identifier "(" Expression ("," Expression)* ")"

// Expression tokenization
Identifier
  = [a-zA-Z_\\][a-zA-Z_\\0-9]*
Number
  = NumberFixed / NumberFloat / NumberInteger
NumberFixed
  = NumberFloat ":" NumberInteger
NumberFloat
  = "0." [0-9]* / [1-9] [0-9]* ("." [0-9]*)? / "." [0-9]+
NumberInteger
  = "0" [xX] [0-9a-fA-F]+ / "0" [bB] [01]+ / "0" [0-7]* / "-"? [1-9] [0-9]*
```

You can paste this grammar into the left pane at https://pegjs.org/online, and then type Digital expressions such as `(-((a&0x800000)>>23))` into the right pane.

References
---

* Expression parsing: https://github.com/hneemann/Digital/blob/a2ab7f2848367b426f43ce923e8bb4b172fd0e8b/src/main/java/de/neemann/digital/testing/parser/Parser.java#L361
* Number parsing: https://github.com/hneemann/Digital/blob/a2ab7f2848367b426f43ce923e8bb4b172fd0e8b/src/main/java/de/neemann/digital/core/Bits.java#L136
* Tokenization: https://github.com/hneemann/Digital/blob/a2ab7f2848367b426f43ce923e8bb4b172fd0e8b/src/main/java/de/neemann/digital/hdl/hgs/Tokenizer.java#L97

**Comment by hneemann** [comment]
> I also did not know that the operator precedence was: <, <=, >, >=, =, !=, |, ^, &, >>, <<, +, -, *, /, %, and then all the unary operators. Potential improvement: adding information about what operators are available, and their precedence.

Intended is operator priority, which is also used in C and Java.

> I'm not sure if this is intentional, but the way the parser works now, once you use a < in an expression, you can't use <= afterwards in the same expression (code). Same thing for > and >=. If this is a bug, then one potential improvement is changing the parser such that Expression becomes LessEqual ("<" LessEqual)* instead.

This is a copy and paste error. If I were one of my students I would be very disappointed! DRY! :smile:
I fear there are more dark corners like this.

> In theory, the existing parser could be replaced by a PEG parser generator (e.g., Parboiled) using this grammar, significantly reducing the amount of hand-written parsing code that needs to be written. However, I'm unsure how much work this would be, so I'll just float that as an idea for now.

In the past I worked a lot with parser generators like javacc or antlr. But I have to say that I now prefer to implement the parsers myself. It's more fun and if the grammar is unusual, which it always seems to be in my uses cases, it's easier because it gives me more control.

In the branch [parserCleanup](https://github.com/hneemann/Digital/tree/parserCleanup) I have reworked the parser.
