### ISSUE TITLE
No way to export to ATF1508 TQFP100 JEDEC

### ISSUE THREAD

**Issue by Special-Kaye** [hneemann/Digital#716]
I need to program the ATF1508 100 pin CPLD Im new to digital however it is how I programmed the 44 pin version. Any help would be awesome thank you!

**Comment by hneemann** [comment]
I have added the missing devices. Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/) and let me know how it goes..

**Comment by hneemann** [comment]
closed in 0b6b0a59448967362e602fc5637741ea4c374f7a
