### ISSUE TITLE
A Java Exception has occured

### ISSUE THREAD

**Issue by HAWKbanido** [hneemann/Digital#727]
I've had used Digital before and worked normally. Suddenly, I just cannot open it any more. I've tried using de code on to the cmd and this showed:
![image](https://user-images.githubusercontent.com/83417438/116579760-18b08500-a8e9-11eb-9d9d-635be01cc7b9.png)
I've also tried updating Java.
What can I do?

**Comment by hneemann** [comment]
If the Digital.jar file was created correctly, the icons are included. Did you create the jar file yourself and accidentally not include the resources?

Try it from a folder that does not contain special characters or spaces. On my machine it works also in this case, but I want to be sure that it is not because of that.

**Comment by HAWKbanido** [comment]
I did not create the jar file myself. I've just extracted the .zip file. Its odd because it was working like a few days ago. Idk what happened or have any idea how to fix it...

**Comment by hneemann** [comment]
Have you tried to launch Digital from a folder where the path does not contain special characters or spaces?

**Comment by HAWKbanido** [comment]
Yes!

**Comment by hneemann** [comment]
Could you please rename the file Digital.jar to Digital.zip and attach the file to this ticket?

**Comment by HAWKbanido** [comment]
[Digital.zip](https://github.com/hneemann/Digital/files/6400856/Digital.zip)

**Comment by hneemann** [comment]
The file works perfectly. I have no idea what is going on with your machine.

**Comment by HAWKbanido** [comment]
Do you think it could be a problem with Java?

**Comment by hneemann** [comment]
Could you please try v0.27-34-g5d29331 which is available for download [here](https://infdigital.dhbw-mosbach.de/)?

It does not fix anything but it adds more detail to the exception.

**Comment by HAWKbanido** [comment]
![image](https://user-images.githubusercontent.com/83417438/116618862-0731a200-a916-11eb-8d6b-0e8a6d9d6a0d.png)

**Comment by hneemann** [comment]
It looks like the java process is not allowed to create temporary files because it lacks the rights to do so.
Seems like there is a problem with the permissions.

**Comment by hneemann** [comment]
Since this is more of a problem on your machine, and has little to do with the simulator, I am closing this ticket.
