### ISSUE TITLE
Feature request: add results to output for CLI test

### ISSUE THREAD

**Issue by phpeterson-usf** [hneemann/Digital#728]
I would like to integrate Digital's command-line testing facility with my [test framework](https://github.com/phpeterson-usf/autograder). In order to make that more useful, I would like to print the detailed output in the test results, rather than just ":passed" or ":failed"

Would you consider making a change like printing `TestResult.results` (via `TestResult::getValueTable()`) in `CommandLineTester::execute()`? in [this area](https://github.com/hneemann/Digital/blob/master/src/main/java/de/neemann/digital/cli/CommandLineTester.java#L83) of the code. 

I can submit a PR if needed, but it looks like just adding `out.println(tr.getValueTable());` would do it.

**Comment by hneemann** [comment]
This is not that easy, as there are users who depend on the current output. 
But I can add a new option.

**Comment by hneemann** [comment]
Does it make any sense to print the table if the test is passed? I would say no.

**Comment by hneemann** [comment]
Hmm! But the output created in case of an error using `out.println(tr.getValueTable());` already contains a diff:

```
unnamed: failed (6%)
C Q_3 Q_2 Q_1 Q_0 
0 1 1 1 1 
0 0 0 0 0 
0 0 0 0 1 
0 0 0 1 0 
0 0 0 1 1 
0 0 1 0 0 
0 0 1 0 E: 0 / F: 1  
0 0 1 1 0 
0 0 1 1 1 
0 1 0 0 0 
0 1 0 0 1 
0 1 0 1 0 
0 1 0 1 1 
0 1 1 0 0 
0 1 1 0 1 
0 1 1 1 0 
0 1 1 1 E: 0 / F: 1 

```

**Comment by phpeterson-usf** [comment]
Fair enough. The format of the diff was not obvious to me at first glance, but I see it shows the actual value with an E (for error?) in that column, and the expected value with an F (why F?)

**Comment by phpeterson-usf** [comment]
Ah ha :-) I can explain that to students if that notation is important. I would somewhat prefer a word but I'm picking nits now. I appreciate your help.

**Comment by hneemann** [comment]
> I would somewhat prefer a word

So do I! :smile: 
But it also appears in the GUI in the results table, and there it bothers when the text representation is to long.
