### ISSUE TITLE
Multiplexed seven segments not updating instantly

### ISSUE THREAD

**Issue by maltaisn** [hneemann/Digital#729]
I've got a slight issue with multiplexed seven segment displays: even at max frequency, the display is not refreshed the moment the common cathode is driven low. The display is only refreshed when on a particular drawn frame, its cathode happens to be low. With a several digits and at high frequency, cathodes appear low one at a time in random order until all displays are refreshed.

![test](https://user-images.githubusercontent.com/33690959/116632996-6697ae00-a926-11eb-84ac-c0f9ce07457e.gif)

At the indicated frequency of 2 MHz I would expect it to be instantaneous.
Here's a smaller circuit in case you want to test:  [circuit.zip](https://github.com/hneemann/Digital/files/6402287/circuit.zip)

**Comment by hneemann** [comment]
@maltaisn 
It is unbelievable that this problem could remain undetected for so long! 
Thanks for pointing this out!
