### ISSUE TITLE
ROM editing: Save current edited values on pressing "OK"

### ISSUE THREAD

**Issue by roy77** [hneemann/Digital#73]
In my current lecture the students have to calculate a machine code and write it to ROM. Much of them add the code and press "OK". They forgot to press return before pressing "OK" and so the changes are not applied. So saving the current changes on OK would be nice.

**Comment by codexp** [comment]
I confirm the issue. I've been wondering why last number has never been saved.

**Comment by hneemann** [comment]
@codexp 
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/).
