### ISSUE TITLE
Wire and Simulation Confusion

### ISSUE THREAD

**Issue by Zachdogg1** [hneemann/Digital#733]
I have a really quite simple 32 bit ALU I initially created in Logisim, which I then ported over to digital wire for wire. This ALU preforms as intended in logisim, however I cannot even start the simulation in digital as it insists that there is no input on many of my wires. I suspect the problem is that the D flip flops start not holding any value, meant to be fed values by a multiplexer with either the arithmetic values or a preset or reset. For some reason Digital seems to think that there are no inputs on the wires that feed the multiplexer output back to the flip flops. 
Error
![image](https://user-images.githubusercontent.com/16945486/116804119-e8800680-aae1-11eb-9510-6858b12fac59.png)
The full Circuit
![image](https://user-images.githubusercontent.com/16945486/116804128-f9307c80-aae1-11eb-93c3-25c826eff318.png)

The offending area (an error will pop for every wire here
![image](https://user-images.githubusercontent.com/16945486/116804138-0e0d1000-aae2-11eb-82f7-fc143dd26c38.png)

The (almost) identical circuit simulating mostly as intended in logisim
![image](https://user-images.githubusercontent.com/16945486/116804156-3563dd00-aae2-11eb-860b-e381f27757b4.png)

**Comment by hneemann** [comment]
In contrast to Logisim in Digital a splitter/merger has a direction.
You have to connect at least one red dot (output) to any wire.

It seems to me that the splitter at the bottom has the wrong direction.

**Comment by Zachdogg1** [comment]
Changing the rotation of the bottom splitter does not fix the issue, although I suspect that is not actually changing the direction by doing that. There is an output at the very top of the circuit, 32 bit taking in the q from every d flip flop and merging with a splitter

**Comment by xotmatrix** [comment]
For the bottom splitter I believe you want:
Input Splitting: 32
Output Splitting: 1*32

**Comment by Zachdogg1** [comment]
That fixed it, forgot to check and just blindly copy pasted an earlier 32 bit splitter
