### ISSUE TITLE
[Enhancement] CLI: Test all files in folder

### ISSUE THREAD

**Issue by Toliak** [hneemann/Digital#734]
**Description**
I would to suggest an idea: to provide an ability to pass directory path into `java -cp Digital.jar CLI test -cirl [forlder_here]`.

**Workaround (but not working)**
The workaround is to write a simple bash script that traverses directory and runs CLI test for every file.
Unfortunately, if there are no tests, CLI test will fail. (*)

I have a question about (*):
Why is lack of tests - a reason to fail? Is that behavior intended?

```
> java -cp Digital.jar CLI test "C:/.../LEDBlock.dig"
no test cases given
Tests have failed.

> echo %errorlevel%
1

```

**Comment by hneemann** [comment]
The reason to add tests to a circuit is to make sure that the circuit works correctly.
And one executes the tests to get a proof that the circuit works as required.
If there is no test, it cannot be proven.

**Comment by Toliak** [comment]
Ok, I understood. That makes a sense.
Therefore, workaround can be applied for folders traversing
