### ISSUE TITLE
Components close together hard to click on

### ISSUE THREAD

**Issue by rj45** [hneemann/Digital#736]
Thank you for this amazing program! I have an annoying but not show stopping UX issue:

When I try to right click on components that are close together it almost always pops open the "which one did you want" dialog, even if I zoom in really far. This seems like it's especially troublesome on constants attached to pins close together. In the previous version of Digital this was not nearly as bad and got much worse when I upgraded. I have linux if that matters.

![Right clicking a zoomed constant.](https://user-images.githubusercontent.com/775678/117206322-91ab5300-ada7-11eb-9c1b-0038a19d5455.png)

As you can see in the screenshot, the "Select" dialog is really not helpful. I have no idea which one of the three listed is the one I just right clicked on. And the one I right clicked on is huge, there should be no need to even display this dialog.

**Comment by hneemann** [comment]
@rj45 
Thank's for pointing that out!

The latest pre release fixes this issue.

**Comment by rj45** [comment]
Awesome, thank you so much! It works so much better! I also like that it displays the constant's value so I can see which one is which if I do happen to trigger the dialog. Very appreciated!
