### ISSUE TITLE
Colored Wires

### ISSUE THREAD

**Issue by jay20162016** [hneemann/Digital#743]
Colored wires are very useful for distinguishing different wires in a setting with many interconnecting wires.

**Comment by hneemann** [comment]
see #510

**Comment by jay20162016** [comment]
Well, that works, a few problems, though
1. That only works on hover, and only for single wires (can't highlight multiple wires), I was talking about permanently colored wires.
2. Same bug - I also have a retina display - I need to move my mouse very carefully over the wire to get the highlight
