### ISSUE TITLE
Stuttering when panning

### ISSUE THREAD

**Issue by milandamen** [hneemann/Digital#751]
When I pan the view (drag while holding right mouse button) the repainting noticeably stutters, and a single CPU core goes to 100% while the pan is ongoing. The effect seems worse when zoomed in than when zoomed all the way out, and is the same regardless whether a simulation is running or not. Disabling grid does not really improve performance much.

I did some quick profiles. Profile of when zoomed in:

![image](https://user-images.githubusercontent.com/6988524/119369517-8e272f80-bcb4-11eb-974f-3319ff83ccfd.png)

Profile when zoomed out:

![image](https://user-images.githubusercontent.com/6988524/119369651-b6af2980-bcb4-11eb-9dff-dbb05ca2187d.png)

It seems the biggest CPU hog are the SunGraphics2D functions.
Maybe a fix would be to only draw things that are in the viewport?

Circuit used to test: https://darvit.nl/s/32-bit_RISC-V_CPU_milandamen.dig

System specs:
OS: Kubuntu 20.04
CPU: AMD Threadripper 2950x
Screen resolution: 2560x1440

**Comment by hneemann** [comment]
Hmm! On my machine it works perfectly smooth. But there are circuits missing.
Please use the "File->Export->Export to ZIP file" function to create a ZIP file which contains all the required circuits.

**Comment by milandamen** [comment]
Here you go: https://darvit.nl/s/32-bit_RISC-V_CPU_milandamen.zip

**Comment by hneemann** [comment]
On my machine, panning is still perfectly smooth. Even when I zoom in.
Could it be that you are using software rendering or something similar?

**Comment by milandamen** [comment]
That may be possible, how do I check that?

**Comment by hneemann** [comment]
This does not seem to be a problem that I can solve.
