### ISSUE TITLE
Can not close output window after stopping simulation

### ISSUE THREAD

**Issue by 38569459** [hneemann/Digital#756]
OS: linux, with i3wm
Digital version: git-revision v0.27

![a](https://user-images.githubusercontent.com/37035950/120061895-84714380-c089-11eb-8211-d5cf5ae26645.png)

As you can see in the image above, the simulation stopped but the output screen still there, no button to close or move it.

**Comment by 38569459** [comment]
I suggest to either add close/move/resize button to output screen or allow output screen to be focusable when clicked.

**Comment by hneemann** [comment]
I can't tell why i3wm doesn't show a close button, but all window managers I've tested so far show a close button.

**Comment by 38569459** [comment]
i3wm normally don't show close button, so either the app must have it or allow the window to be focusable. In this case, the main screen somehow steal focus from the output screen. A quick fix will be add close/move/resize buttons to output screen, since tracking down why the main screen always steal focus is harder, i believe.

**Comment by hneemann** [comment]
> A quick fix will be add close/move/resize buttons to output screen, since tracking down why the main screen always steal focus is harder, i believe.

No, it is not. I have implemented it this way.
In the simulator there are some dialogs that do not allow any user interaction. And these can't take the focus either, because that doesn't make sense. That there are window managers out there which in this case don't allow closing the dialog surprised me.

**Comment by 38569459** [comment]
Then the only option left is to add some buttons to close it. In i3wm, you must focus the window before you can move/resize/close it, it's how i3wm works and there is nothing i can do about it.

**Comment by hneemann** [comment]
There is another solution: the dialog should not get the focus automatically, but the user should be able to give the focus to the dialog.
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/).

**Comment by 38569459** [comment]
Yes, I'm now able to focus the window and close it. Thank you for quick reply!
