### ISSUE TITLE
Only 64bits allowed in splitter

### ISSUE THREAD

**Issue by 38569459** [hneemann/Digital#759]
I'm building a circus with lots of wires, ex: 16x64bit data bus and tried to use splitter to make the wiring look better, but the splitter only allow 64bits so i can't do that.
![a](https://user-images.githubusercontent.com/37035950/120157540-54f34000-c21d-11eb-9db5-acda4209a0bb.png)

Each of the line above is 64bits data bus.

**Comment by hneemann** [comment]
That's right! All components support up to a maximum of 64 bits.

**Comment by 38569459** [comment]
Can you raise the limit? Since with a very large data bus, 64bits is quite limited.

**Comment by hneemann** [comment]
No.
Moreover, it will always be too small with a sufficiently wide data bus. :smile:

**Comment by 38569459** [comment]
Is there a data bus component in Digital? I want to avoid UI clutter since lots of wires don't look good.

**Comment by hneemann** [comment]
There is nothing available that offers more than 64 bits.
