### ISSUE TITLE
Bit extender?

### ISSUE THREAD

**Issue by 22459** [hneemann/Digital#76]
Hi,

is there a reason Digital doesn't have the bit extender?: [http://www.cburch.com/logisim/docs/2.5.0/en/libs/base/extender.html](http://www.cburch.com/logisim/docs/2.5.0/en/libs/base/extender.html) or did I just not find it in the component tree?

Thanks

**Comment by hneemann** [comment]
There is no reason. A bit extension is so simple that I thought a special component was unnecessary.
A bit extension is not a special logic. It's just a special kind of wiring:

![z](https://user-images.githubusercontent.com/7190563/32652967-6c161ad0-c606-11e7-9512-b50a0ca787f2.png)

**Comment by 22459** [comment]
Oh, I figured I should do something like that but couldn't figure out how. That makes sense. :)
Thanks.

**Comment by hneemann** [comment]
@22459 
If you want to use the new bit extender (which only works with signed values) you can use the last [pre release version](https://infdigital.dhbw-mosbach.de/).
