### ISSUE TITLE
Suggestions for objects to be added

### ISSUE THREAD

**Issue by RadiantUwU** [hneemann/Digital#766]
Resistor(can be made)
But something that can't be made, is properly checking the state of 1 bit pin
It can be in 5 states:
Low
High
High-Z
Resistive low
Resistive high
Could you please add resistor and pin checker?

**Comment by hneemann** [comment]
see  #30

**Comment by RadiantUwU** [comment]
I mean, resistor, okay, you cant add that, i can make one myself using transistors, but can you make a pinchecker which can check if the output is pulled or not

**Comment by hneemann** [comment]
What exactly is the pin checker supposed to do?
