### ISSUE TITLE
design the appearance of a circuit

### ISSUE THREAD

**Issue by hydrogenbomb1212** [hneemann/Digital#78]
logism allowed me to put in and output pins on the place i wanted, whenever i put then at the top middle, bottom or sides, it also allowed me top draw and write on a subcircuit circuit to choose how it looked in higher circuit, its the only thing that i really miss in digital.

**Comment by hneemann** [comment]
You are right! Digital differs in many aspects from Logisim.
The lack of custom shapes is already one of the open issues. See #39.
