### ISSUE TITLE
File as clock / signal input

### ISSUE THREAD

**Issue by YMasquel** [hneemann/Digital#788]
version: v0.27
Hello, as enhancement,
should it be possible to use a file for input signals input with : 
 -  timestamp (or delay from origin) ;
 -  level (high / low) .
This could help in signal analysis.
By the way, that's a great job and so easy to use.
Best regards, YMasquel.

**Comment by hneemann** [comment]
It is not possible to load a file but you can copy&paste the data to a test case.

**Comment by YMasquel** [comment]
Thank you for this information but after some brainstorming I think that the use of a ROM memory and a counter I can solve my problem. I'll study your proposal to see what is the simplest and the finest solution.

**Comment by hneemann** [comment]
The use of a ROM/counter is of course also possible, but a test case is much more flexible and powerful, as it allows programming of the input signals to a certain degree. Whereas in a ROM only fixed values can be stored.
