### ISSUE TITLE
Adding breakable fuses for shortcircuits

### ISSUE THREAD

**Issue by RadiantUwU** [hneemann/Digital#791]
Here's one of my ideas for a module:
A bi directional breakable fuse.
The user can add to it a reset pin, which will reset the breakable fuse in case if its blown out back to normal.
When a short circuit happens, the breakable fuse will blow out.
I hope this is possible to make, not sure if it really is but i hope so.

**Comment by hneemann** [comment]
This is difficult to implement in such a way that the user is not unpleasantly surprised. It would happen that users install fuses in the supply line of an IC and are surprised that it does not react when a short circuit occurs at one of the outputs or similar.
