### ISSUE TITLE
Outputs spaced differently

### ISSUE THREAD

**Issue by IvyBit** [hneemann/Digital#794]
I'm propably just missing something but it seems that inputs in a sub circuit (shape: layout) are grouped and outputs get spaced evenly now. Is there an option I'm missing?

**Comment by hneemann** [comment]
Inputs and outputs should behave the same.
Do you have an example circuit that shows this problem?

**Comment by IvyBit** [comment]
I've checked again and the issue is not related to the type of port.
[pixel-counter.zip](https://github.com/hneemann/Digital/files/6836654/pixel-counter.zip)

![image](https://user-images.githubusercontent.com/35197182/126076323-9941d7e7-f66e-4cc4-bad8-72cef2d8e19c.png)

**Comment by IvyBit** [comment]
... I'm an idiot. 
Sorry, of course the outputs get spaced evenly unless there's not enogh space to do so.

**Comment by IvyBit** [comment]
![image](https://user-images.githubusercontent.com/35197182/126549294-cd2ffcff-e3d4-4346-a69a-b9583ca88846.png)
Something is still weird, this is how the project opened up today.

**Comment by IvyBit** [comment]
Again.. the second I posted this I knew what was happening.
Windows server can have a nasty habit of caching files and forgetting them.
