### ISSUE TITLE
Allow "Run to Break" to be interrupted

### ISSUE THREAD

**Issue by ProxyPlayerHD** [hneemann/Digital#799]
it happens to me quite a few times where i'm working on a circuit, haven't saved in a while, and then go to test it using the Break component because i want to look at some specific timings.
i place it, set the maximum cycles, and then press the "Run to Break" button.

and around 5 nanoseconds later i remember that the wire i connected the Break to will never activate.

the program is completely unresponsive while it's doing the simulation so i always have to either wait it out or kill the program using the Task Manager.

it would be very nice if i could just press the Stop button or ESC to immediately stop the "Run to Break" function.

**Comment by hneemann** [comment]
Is releated to  #83

I really have to address this issue!

**Comment by hneemann** [comment]
@ProxyPlayerHD 
What number of timout cycles have you set in the break component?

**Comment by ProxyPlayerHD** [comment]
depends on the circuit.
but usually between 1M to 100M cycles.
i put them that high because otherwise i would have to do small adjustments, run the simulation, it didn't reach the point, do another small adjustment, repeat.

**Comment by hneemann** [comment]
@ProxyPlayerHD 
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/) (v0.27-88). While I'm not sure I like the implementation that much, it should work.

**Comment by ProxyPlayerHD** [comment]
hmm i don't see any difference, the program still freezes once you click "run to break"

**Comment by hneemann** [comment]
@ProxyPlayerHD 
That surprises me! Can you upload a minimal example where RunToBreak is not to be cancelled?

**Comment by ProxyPlayerHD** [comment]
is uploading a circuit needed?
<img width="438" alt="javaw_2021-08-02_16-14-48" src="https://user-images.githubusercontent.com/13576843/127875739-1dd82b26-f50f-47dc-8b6d-b8f9193a8099.png">
the counter is set to be 64 bits wide, and the Break component is set to 10M. it doesn't take long to reach the limit due to the simple circuit, but it'S still not interruptable while running.

**Comment by hneemann** [comment]
@ProxyPlayerHD 
This is the exact circuit I use for testing and it works just fine!
Are you sure you are using a pre-release v0.27-88 or later?

**Comment by ProxyPlayerHD** [comment]
the about page says "Build git-Revision: v0.27-88-g14f7168"

and just to clarify, so we're not accidentally talking about 2 different things, what exactly should you be able to do when you press "run to break"?
i assumed this would allow you to still click things in the menu bar, ie stopping the simulation and such, while the "run to break" is doing it's thing

**Comment by hneemann** [comment]
> I assumed this would allow you to still click things in the menu bar, ie stopping the simulation and such, while the "run to break" is doing it's thing

exactly!

![Unbenannt](https://user-images.githubusercontent.com/7190563/127883015-0fb61f2b-415c-4aa7-9c48-1195655c7b5a.gif)

**Comment by ProxyPlayerHD** [comment]
i was always using single gate mode, not regular simulation mode

**Comment by hneemann** [comment]
@ProxyPlayerHD 
You use the single gate mode? 
That's interesting! For what purpose?

**Comment by ProxyPlayerHD** [comment]
for example to see exactly when Outputs activate/deactivate or when Registers load in data.

or to single step through a CPU executing Instructions, so i can see each memory access. and such.

kinda a shame you can't look into sub circuits while the simulation is running.

**Comment by hneemann** [comment]
> it's important to see how all the output signals do their thing (with the data graph) since most circuits i make i put onto programmable logic like CPLDs or FPGAs.

Keep in mind that the exact timing at gate level in the simulation has little or nothing to do with the later timing in an FPGA or a CPLD at this level of detail!
The single gate mode is only meant to show students which influence the timing on gate level can have. The exact timing on gate level in a FPGA or CPLD will be completely different!

**Comment by ProxyPlayerHD** [comment]
it's a good enough estimate for the ~25MHz i'm running them at. and so far i never came across any noticable difference between what the simulation was doing and how the circuit worked on the actual hardware.

and in the worst case, i recently bought a Rigol DS1054Z Oscilloscope and did the "hack" to upgrade it to 100MHz. so i can always just look at the actual signals in real time.

**Comment by hneemann** [comment]
It is just important to know that you can not rely on the simulation in this regard.
I think you are generally well advised not to rely on a specific timing at gate level! 
It is more robust to rely only on the timing at clock level.

**Comment by ProxyPlayerHD** [comment]
either way the problem itself still remains.
single gate mode cannot be stopped while "run to break" is running...

**Comment by hneemann** [comment]
> either way the problem itself still remains.

That's right!  :smile: 
Please try [v0.27-94](https://infdigital.dhbw-mosbach.de/)

**Comment by ProxyPlayerHD** [comment]
alright that seems to work, it's very laggy but that's still much much better than just straight up freezing the whole program.

**Comment by hneemann** [comment]
> it's very laggy

Please try [v0.27-95](https://infdigital.dhbw-mosbach.de/). Still not perfect but better.
