### ISSUE TITLE
Wishlist item: AOI

### ISSUE THREAD

**Issue by tkoenig1** [hneemann/Digital#801]
It would be interesting to have AOI component. It can, of course, be generated from existing components, but it something that can bring advantages in CMOS, so it would be nice to have, especially when counting components.

**Comment by hneemann** [comment]
Wouldn't it only make sense if you count transistors?

**Comment by tkoenig1** [comment]
Counting components as a prerequisite for counting transistors, certainly.

**Comment by hneemann** [comment]
Hmm! 
But it is possible to build such a circuit from CMOS transistors. 
Then the transistors are counted correctly.

![21AOI](https://user-images.githubusercontent.com/7190563/127440503-1ce3b8d0-e12a-46f0-8ea0-8717569f82f5.png)

[21AOI.dig.zip](https://github.com/hneemann/Digital/files/6898206/21AOI.dig.zip)
