### ISSUE TITLE
74670 Component not working

### ISSUE THREAD

**Issue by hwreverse** [hneemann/Digital#804]
![image](https://user-images.githubusercontent.com/49004465/128543838-ffbd1038-547f-459c-b8d2-a5b3f18b68a5.png)

Hi there,

Long story short: Any circuit with the 74670 component does not run and gives the following error:

**No output connected to a wire([1;Splitter]). The state of the wire is undefined.
Occurred in file 74.670.dig**

Best regards,
Alexander

Sketch from the image attached to Issue report
[670d1.zip](https://github.com/hneemann/Digital/files/6946879/670d1.zip)

**Comment by hneemann** [comment]
In Digital it is not allowed not to connect inputs.
See also  #36

**Comment by hwreverse** [comment]
Thank you very much, it solved the problem.

**Comment by hwreverse** [comment]
As Digital did highlight the "VCC" net during the error, I was lead to believe (in error) that the error was related to this wire in particular.

**Comment by hneemann** [comment]
Highlighting a wire in light green indicates a logic 1, which is of course always the case with VCC. In case of an error it is highlighted in red.
But in your case there were no connected wires that could be highlighted.

**Comment by hwreverse** [comment]
That clears it up. Thank you very much for your fast response. And thank you for your great piece of software!
