### ISSUE TITLE
Wishlist item: Count Resistors

### ISSUE THREAD

**Issue by tkoenig1** [hneemann/Digital#805]
While resistors are not active components, it would still be interesting if it was possible to count them.

(Background: Just looking at simulating part of 6502 and similar chips. While the depletion
mode NMOS transistors can be modeled by pull-up resistors, it is still necessary
to count those by hand - and adding depletion mode transistors would probably be too
little gain, I think).

**Comment by hneemann** [comment]
There are no "real" FET's in the simulator. 
In the simulator, a FET is a resistorless switch that is switched with a control voltage. More like a relay. And with the currently implemented simulation engine it is also not possible to simulate resistors. See also #30
Therefore a depletion mode NFET would be equivalent to a PFET.
