### ISSUE TITLE
More than 1000 rows of measurements values

### ISSUE THREAD

**Issue by damouze** [hneemann/Digital#807]
Hi,

I have been using your simulator for a while now and I think it is awesome. 

However, I noticed that whenever you save the data from a measurement graph as a .csv file to disk, it only writes up to 1000 rows of data. 

I could not find a setting for it, so I was wondering if it were possible to extend this to allow for more data rows to be saved? Maybe expose the maximum as a setting in the settings menu? Another idea might be to do live logging of this measurement data to a file you specify beforehand.

**Comment by hneemann** [comment]
The maximum sample size is indeed hard coded to 1000! I will change that.
