### ISSUE TITLE
Graphical issues on windows 11

### ISSUE THREAD

**Issue by sjwatt** [hneemann/Digital#813]
UI graphics are completely broken after a few minutes on windows 11 on latest release. Repeatable for both Digital.exe and Digital_noD3D.exe. See attached images.
![Screenshot 2021-08-22 050116](https://user-images.githubusercontent.com/307604/130354333-9261b1ff-d651-494d-813d-371b80542abb.png)
![Screenshot 2021-08-22 050044](https://user-images.githubusercontent.com/307604/130354334-a521794a-add1-463d-9896-6743c1bcdfcd.png)

**Comment by hneemann** [comment]
Seems to be a duplacate of #227

Which java version are you using?
