### ISSUE TITLE
Disabling wires

### ISSUE THREAD

**Issue by PaulKappmeyer** [hneemann/Digital#818]
I've been building a 4-digit multiplexed seven-segment display. A two-bit binary counter is driven by an individual clock, which runs faster than the clock of the computer. The counter drives a 2-line to 4-line multiplexer, which activates a single segment of the display. And the data for the segments comes from an EEPROM.

After some experimenting, I got it to work just nicely (also using the “avoid flicker”-option of the displays).
Interestingly, I found that the display works better when setting the display clock not to “maximum” (or some really high value like 50kHz), but to a much lower value like 30 Hz. (I guess this is due to the individual simulation and graphic threads?)

Anyway, the flickering of the connected wires is just really annoying at such high clock speeds. So, I would like to ask if there is a way to disable the drawing (high or low state) of the wires.
I don’t want the wires to disappear completely, but it would be great if the wires had an option like “don’t show state” (or something like that) – so that they are drawn just like the wires that connect a multi-bit input.
Do you think this would be possible?

![Display](https://user-images.githubusercontent.com/42696082/131363414-773577a1-3d6c-4567-88e2-7231917c62c2.png)

**Comment by hneemann** [comment]
It is possible to define your own customized color scheme. 
There you could set all wire states to the same color. This way the flickering would disappear.

**Comment by PaulKappmeyer** [comment]
Thanks for your fast respond :-).

But I think this is not the solution I was looking for.
The screenshot I’ve attached is just a small part of a bigger circuit. I want the wires in the remaining parts of the circuit to act just normal, but to stay blue (or whatever color) in this display section.

I guess I could use an embedded circuit, but this isn’t quite what I want, since the connections to the segments would remain.

**Comment by xotmatrix** [comment]
When I was using Logisim, I created an output display module like this. I was able to make a custom shape that I could plug the 7-segment displays into without wires. It was all very tidy. I wonder if the same thing can be done with custom SVG shape in Digital? I've never tried making a custom shape before. Worth exploring.
![javaw_2021-08-30_12-36-01](https://user-images.githubusercontent.com/14209329/131373671-dfe5ec80-a301-4a11-a648-556d7b71abc8.png)
![javaw_2021-08-30_12-30-47](https://user-images.githubusercontent.com/14209329/131373685-f09c4e93-1f3f-4d86-9d10-c42fe7128651.png)
![javaw_2021-08-30_12-29-15](https://user-images.githubusercontent.com/14209329/131373703-fdc4ae28-4051-41f7-aac8-70661c2f9f46.png)
![javaw_2021-08-30_12-36-30](https://user-images.githubusercontent.com/14209329/131373707-c25ff54d-1a27-4302-a681-2d2693e7c9fc.png)

**Comment by PaulKappmeyer** [comment]
Thanks for your answer. This could definitely be an interesting approach. I also didn’t use custom shapes before.
But I think that one might run into some problems with the pin connections. I made some tests and attached a screenshot:
1.	This circuit works; I tried to put the pins directly on top of each other
2.	This circuit works too; I tried to connect the two inputs directly together (you can barely see the blue line at the left of the gate)
3.	This circuit does not work; I tried to make a connection “inside” of the gate
![Connections](https://user-images.githubusercontent.com/42696082/131379278-ef4019e9-7242-44eb-8275-a936a002c166.png)
So, I would guess, that the pins of the segment-displays would have to be just on top of the pins of the embedded circuit.

But honestly, this would still be an unsatisfying solution for my purpose. I rather wonder, if it wouldn’t be possible to add like a third drawing option to the wires – like:
1.	High state (e.g. light green)
2.	Low state (e.g. dark green)
3.	Neutral state (independent of the state, just indicating that data is changing/or transferd on this wire)

**Comment by hneemann** [comment]
Also in Digital it is possible to create a circuit with a custom shape to which a seven-segment display can be connected by placing it on top.

[customShape.zip](https://github.com/hneemann/Digital/files/7078426/customShape.zip)

**Comment by hneemann** [comment]
@PaulKappmeyer 
I'm sorry, but I don't think I'll implement a special drawing mode for specific wires in a circuit.

**Comment by xotmatrix** [comment]
@hneemann That's exactly what I was trying to describe. I'm so pleased it works.

**Comment by PaulKappmeyer** [comment]
![Display Splitter](https://user-images.githubusercontent.com/42696082/131525889-2f686fdc-2592-438e-b7d4-c80e287cdcde.png)
So I guess that I found another compromise:

When using splitters/mergers and directly putting the pins on top of each other one can make sure, that this part contains no single-bit wires, but multi-bit wires instead, which don’t switch their color. So now all blinking wires (except the clock wire) are gone. 
I guess I could have used tunnels too, but tunnels require a bit of working naming them all correctly.

The splitters show their pin numbers, which now slightly overlap with the seven-segment display. I guess there is no way around this, but the overlapping is so slightly – especially at low zoom levels – that this is no problem there.
I didn’t know that the splitters had a maximum spreading value (it seems like it is ten). Why is that?

**Comment by hneemann** [comment]
> I didn’t know that the splitters had a maximum spreading value (it seems like it is ten). Why is that?

There is no particular reason for this. I don't want the value to be completely unlimited, and 10 seemed enough. 
I can also set the value to 20, that's no problem.

**Comment by PaulKappmeyer** [comment]
Thanks for the addition. It is just a nice way to bring one part of a signal to another location in the circuit using a splitter with a very large spreading.
If there is nothing to add here, I will close this issue.
