### ISSUE TITLE
Chinese translation update

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#820]
@itviewer 
This is a request for updating the language files for a planned new release.
I would appreciate your continued support.

[lang_diff_zh.xml.zip](https://github.com/hneemann/Digital/files/7109341/lang_diff_zh.xml.zip)

**Comment by itviewer** [comment]
[lang_diff_zh.zip](https://github.com/hneemann/Digital/files/7113039/lang_diff_zh.zip)

**Comment by hneemann** [comment]
@itviewer 
Thank you again for your help!

There were some syntax errors when importing the file. Can you take a look at it again?

```
zh: Param count does not match: err_errorWritingFile_N="写文件时发生错误。", expected: 1, found 0
zh: Param count does not match: err_file_N0_ExistsTwiceBelow_N1="文件 {0} 存在多次", expected: 2, found 1
zh: Param 1 is missing in: err_wrongNumOfArgsIn_N0_InLine_N1_found_N2_expected_N3="函数 {0} 的参数个数不正确（期望 {3} 个，发现 {2}个）"
zh: Missing closing '}': msg_fixesCreated_N="Fixtures: {0"

```

**Comment by itviewer** [comment]
[lang_diff_zh.zip](https://github.com/hneemann/Digital/files/7113896/lang_diff_zh.zip)

**Comment by hneemann** [comment]
This time it worked perfectly.
Thanks again for your help!
