### ISSUE TITLE
French translation update

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#821]
@maltaisn 
This is a request for updating the language files for a planned new release.
I would appreciate your continued support.

[lang_diff_fr.xml.zip](https://github.com/hneemann/Digital/files/7109344/lang_diff_fr.xml.zip)

**Comment by maltaisn** [comment]
[lang_diff_fr.xml.zip](https://github.com/hneemann/Digital/files/7110546/lang_diff_fr.xml.zip)

**Comment by hneemann** [comment]
@maltaisn 
Thank you again for your help and support!
