### ISSUE TITLE
Spanish translation update

### ISSUE THREAD

**Issue by hneemann** [hneemann/Digital#822]
@angelmicelti 
This is a request for updating the language files for a planned new release.
I would appreciate your continued support.

[lang_diff_es.xml.zip](https://github.com/hneemann/Digital/files/7109349/lang_diff_es.xml.zip)

**Comment by angelmicelti** [comment]
Here you are!
[lang_diff_es.zip](https://github.com/hneemann/Digital/files/7146686/lang_diff_es.zip)

**Comment by hneemann** [comment]
@angelmicelti 
Thanks again for your help!
