### ISSUE TITLE
Memory (ROM ou EEPROM) content encoding

### ISSUE THREAD

**Issue by d-teif** [hneemann/Digital#824]
Just a suggestion, I don't know if is it relevant.
With memory (ROM or EEPROM), if you have only just a few values at lower and  upper memory, it will generate a big design file. For example, with 24 bits address and 32 bits values, the file generated  is about 34 MB full of 0 values.

Perhaps a chained list, or hash table with only value or memory blocks not empty (0)

 Best regards

**Comment by hneemann** [comment]
@d-teif 
A valid hint. Thanks for it!
