### ISSUE TITLE
Italian translation update

### ISSUE THREAD

**Issue by psiwray** [hneemann/Digital#825]
I'll leave here the updated Italian translation file, since I've had trouble reaching @hneemann via mail. I don't know how to integrate it directly by myself so I'll leave that for another person: [lang_diff_it.zip](https://github.com/hneemann/Digital/files/7149987/lang_diff_it.zip). Thanks and pardon myself for this way of doing things, I promise it's just temporary.

**Comment by hneemann** [comment]
@psiwray 
Never mind! It doesn't matter how the file is transferred.
Thanks for your help!
