### ISSUE TITLE
The Relay Switch cause oscillate

### ISSUE THREAD

**Issue by qingwa2009** [hneemann/Digital#828]
I want to use one Relay switch to simulate a oscillator, 
just connect vcc -> relay(closed state) -> gnd
but it can`t work!
Can you fixed this?

**Comment by hneemann** [comment]
In normal operation, the simulator waits until the circuit has stabilized. If a circuit does not stabilize, it generates an error message.
However, there is a special asynchronous mode that allows the simulation of circuits that never stabilize.
To use this mode, the circuit must stabilize at least at the start of the simulation.
Attached you will find a circuit that simulates a relay oscillation. Start the circuit in single gate mode and close the switch.

[asyncExample.dig.zip](https://github.com/hneemann/Digital/files/7161353/asyncExample.dig.zip)
