### ISSUE TITLE
Strange generic parameter bug in v0.28

### ISSUE THREAD

**Issue by YulienPohl** [hneemann/Digital#830]
Having a generic circuit which controls the number of inputs, the number 6 does not work.
[bug.zip](https://github.com/hneemann/Digital/files/7163835/bug.zip)

**Comment by hneemann** [comment]
@YulienPohl 
This was a really interesting and surprising bug.  :-(
Thanks for pointing this out!

Please use the latest [pre release](https://infdigital.dhbw-mosbach.de/).
