### ISSUE TITLE
Modifying clock properties causes lockup.

### ISSUE THREAD

**Issue by Usoilworker** [hneemann/Digital#836]
When attempting to modify Clock input with right mouse click, process quits responding no printout in task window {LINUX - Debian OpenJDK}

**Comment by hneemann** [comment]
I also use Debian and everything works very well for me.
Can you describe in more detail what exactly you did?

**Comment by hneemann** [comment]
Contact lost!

**Comment by Usoilworker** [comment]
Sorry for the delay in response... Issue with digital 
resolved when visual studio installed a few of it's dependencies.
