### ISSUE TITLE
RAM losing data when starting simulation 

### ISSUE THREAD

**Issue by SgtSchultz71** [hneemann/Digital#838]
I've noticed that when I load my RAM with data before starting a simulation, _sometimes_ that data disappears. I have to then go back into the RAM module and type in the data once more. What is also strange is that this only seems to happen in the first memory cell. I am not sure if this is a bug or somehow intentional but I was curious as to why this occurs.

![image](https://user-images.githubusercontent.com/44954122/133783561-4f35eec9-68d7-4920-94da-b008798d14ec.png)

**Comment by hneemann** [comment]
This seems to be a problem similar to #835

**Comment by SgtSchultz71** [comment]
Yes indeed! I failed to find that particular entry to the forum but it makes sense. Thank you!

**Comment by hneemann** [comment]
@SgtSchultz71 
You're welcome! :smile:
