### ISSUE TITLE
Random short on a data bus (simple 8 bit processor)

### ISSUE THREAD

**Issue by lefuturiste** [hneemann/Digital#842]
Hi.

Thanks to the developer of this very cool software.

I built a simple 8 bit computer to do Fibonacci sequence with Digital.

All the assembly code and files is here :

https://github.com/lefuturiste/8bit-computer

but it errors randomly (sometimes the computer run fine for 5 seconds other time it crashed immediately) :

```
Error calculating a step
More than one output is active on a wire, causing a short circuit.
```
It's highlighting the data bus.

But for me, I don't know how something like that could happen with the data bus, may be is it because of the registers, I don't know.

I also tried with very simple program that load things into the registers and it didn't work either;

Can someone can help be to have way to debug this issue?

**Comment by hneemann** [comment]
A pull down is missing, which leads to certain wires being undefined at times, which can lead to unpredictable effects.

![computer](https://user-images.githubusercontent.com/7190563/134622725-e57aea5e-41cd-42a5-9dff-1f4048af929b.png)

So many wired Or's are used that it becomes confusing. Maybe these should be replaced by real OR gates. In my opinion it is not a good idea if a design relies so massively on High-Z states and pull resistors have to be inserted everywhere.

**Comment by lefuturiste** [comment]
Ok, many thanks for pointing the missing pull down it worked perfectly. 
Now I want to know more about how I can avoid pull resistors.
What are "wired Or's" and how these can be replaced by OR gates.

For example to say to a register to a register to store smth I use a "STORE" flag line which is pull down. What's the better solution to your opinion ?

![image](https://user-images.githubusercontent.com/20988163/134633834-2a83b4cd-74ea-4466-af63-65d119988a3f.png)

**Comment by hneemann** [comment]
Replace this:
![or1](https://user-images.githubusercontent.com/7190563/134708872-3c4d036a-157f-42a3-909d-cae0dd94f6ff.png)
by this:
![or2](https://user-images.githubusercontent.com/7190563/134708904-77aa03e7-1275-403d-9eb9-922d458e6ba5.png)
or this:
![or2b](https://user-images.githubusercontent.com/7190563/134709119-a72233ab-bf07-4415-89ed-b47b1ceafb0a.png)
