### ISSUE TITLE
XOR symbol in text

### ISSUE THREAD

**Issue by eliask05** [hneemann/Digital#844]
This question is probably OS-specific. For reference, I am using Digital under windows.

![Pr_3_08_sol](https://user-images.githubusercontent.com/41453704/134784034-497aa1c0-f81c-4718-9fc0-a958ddff3584.png)

I like to include equations in the circuits when I give problems and solutions to students. Using the windows character map application, I can insert summation, product and XNOR symbols since they are included in the default font (Arial). The XOR symbol, however, is not included. In the attached screenshot, edited in paint,  I got it from the symbol font but this is not possible in Digital since the text is in a single font and that is Arial.

Any suggestions on how I can get the XOR symbol, if at all possible?

**Comment by hneemann** [comment]
It must be a OS specific problem. On my system (Debian) it works without an issue:

![xor](https://user-images.githubusercontent.com/7190563/134796631-0b8ccc2a-cf44-4ee2-b8b9-a1828d81351c.png)

But I am not a Windows expert. In fact, I'm not even a Windows user, so I can't give advice.

Here is the circuit i have used to create the screenshot above, just in case it is a unicode codepoint problem:

[xor.dig.zip](https://github.com/hneemann/Digital/files/7230869/xor.dig.zip)

**Comment by eliask05** [comment]
Thank you! It actually displays fine on my Windows system, but how did you enter the symbol in the text box?

**Comment by eliask05** [comment]
OK, I figured it out. I used BabelMap which is much more powerful and user friendly than character map.
Thanks for the help, I am closing the issue.

**Comment by hneemann** [comment]
@eliask05 
Up to now the LaTeX commands `\sum, \prod, \wedge, \vee` and `\neg` are available.
I will add `\oplus` and `\odot`.

Is something else missing?

**Comment by eliask05** [comment]
Great! I wasn't aware of the LaTeX commands. I think the following may be also useful:
\pm \mp \div \cdot \times and \otimes

**Comment by hneemann** [comment]
@eliask05 
I have added them. Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/).

**Comment by eliask05** [comment]
Thank you! They work great. I have modified the "TextFormatExample.dig" example file in case you wanted to document them
[TextFormatExample.zip](https://github.com/hneemann/Digital/files/7232258/TextFormatExample.zip)
.

**Comment by hneemann** [comment]
@eliask05 
Thanks! :smile:
