### ISSUE TITLE
Spreading-option for plexer-components

### ISSUE THREAD

**Issue by PaulKappmeyer** [hneemann/Digital#846]
Hello,
I’m trying to hook the outputs of a decoder-component up to leds.

The plexer-components tend to have a lot of outputs (just like the splitter/merger-component), but the don’t line up with the leds since the outputs are just one grid unit apart. So, I’m searching for a spreading-option to be able to control the spacing between the outputs on the decoder-/demultiplexer-component (the inputs on the multiplexer-component)
Could this be added?

**Comment by hneemann** [comment]
There are two possibilities: Either you reduce the size of the LEDs or you connect the plexer via wires with a 90° angle.

![z](https://user-images.githubusercontent.com/7190563/135132156-b31fbf8c-97f9-43d7-a979-118f08fa243b.png)

I do not think that I will implement a way to increase the size of the shape.
