### ISSUE TITLE
Dual Port Byte Addressable RAM

### ISSUE THREAD

**Issue by TheWildJarvi** [hneemann/Digital#850]
Hi Helmut, I was wondering if you could expand the 32bit byte addressable RAM options to also include a dual port byte addressable RAM? Currently I am making that myself from the dual port ram modules and the provided 32bit byte addressable memory, but I am sure there are others who could also use such a component. 

Jarvi

**Comment by hneemann** [comment]
Dual ported RAM is already something that is rarely used. A byte-addressable 32-bit variant will be needed even less often. So I don't think it is necessary to add this to the standard library.
