### ISSUE TITLE
Plus key accelerators do not work with English language keyboards

### ISSUE THREAD

**Issue by xotmatrix** [hneemann/Digital#87]
On English language keyboards, because of the + key is really a shifted = key, a plus keypress is not detected. This affects both the zoom control and the input pin number control.

At the end of topic linked below there seems to be a fairly comprehensive solution which works with multiple keyboards and adds NumPad support as well.

https://community.oracle.com/thread/1356291

**Comment by hneemann** [comment]
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/) version  and let me know how it works on your machine.

**Comment by xotmatrix** [comment]
This fix works somewhat. It does require holding the shift key for + which I think is rather awkward. Applications that use +/- in this sort of way rarely if ever require that of English language keyboard users; the unshifted = key is treated like the + key of other keyboards. That's in part why I linked that particular solution above.

**Comment by hneemann** [comment]
So the common way to handle this is: Name it [+] but use [=] instead? :-)
You will find that behavior in the latests pre release.

**Comment by xotmatrix** [comment]
Perfect! Thank you.
