### ISSUE TITLE
Analysis seems to skip parts of the circuit

### ISSUE THREAD

**Issue by damouze** [hneemann/Digital#872]
I am building logical circuit to be loaded onto an ATF750CL (a GAL22v10 pin-compatible device). When I do the analysis of the circuit, it seems to skip an entire part of the circuit and sets one of the outputs to simply be high, which in the simulation is certainly not the case.

This is the circuit I have created: 

![complete_latch](https://user-images.githubusercontent.com/84080957/139446249-31a46615-031a-4686-b833-c4f25b4824c4.png)

As you can see it has a separate circuit to that generates an output signal based on two of the input signals. However, when I run the analysis, this is the expression it outputs:

![complete_latch_analysis](https://user-images.githubusercontent.com/84080957/139446578-0e8e2513-4316-4d0d-afd9-f56367496b9b.png)

As far as I can see, the entire bottom circuit was not analyzed and the output pin is simply set to high. This may very well be correct behaviour, but it is not what I am expecting. Is there a way to tell Digital to take the entire circuit into consideration?

**Comment by damouze** [comment]
> 
> 
> The circuit analyzer does not expect the clock to be an input of a combinational circuit. The clock is only considered as a trigger for storing data in the flip-flops. The analysis assumes that the circuit to be analyzed is a Mealy automaton.

Thanks for your reply. 

So, what do I do if I want to generate an output signal that is partly based on the clock signal?

**Comment by hneemann** [comment]
Unfortunately, you can't do that with this simulator. The simulator is not a synthesis tool for GALs, which basically means that not all possibilities of the PLD are supported.
You will have to switch to another tool, e.g. WinCUPL.

**Comment by xotmatrix** [comment]
> The simulator is not a synthesis tool for GALs
I found this out trying to add an Output Enable pin to my circuit. It's a free feature on a GAL but it caused Digital to hate life. I learned a lot about WinCUPL and PLDs that day, so it was a blessing in disguise.

**Comment by damouze** [comment]
> 
> 
> Unfortunately, you can't do that with this simulator. The simulator is not a synthesis tool for GALs, which basically means that not all possibilities of the PLD are supported. You will have to switch to another tool, e.g. WinCUPL.

Ok fair enough. I am still a fan though ;-).
