### ISSUE TITLE
Multiple Mux Bug

### ISSUE THREAD

**Issue by yannisdran** [hneemann/Digital#895]
The feature of mux is unusable, as I am not able to create 2-1 or 4-1 mux.
Additionally, I can't convert it back to another form, if I choose wrong values:
This is a classic 2-1 mux:
![image](https://user-images.githubusercontent.com/2004337/149855182-fe2a37ee-1d47-4be7-bd13-ab645e7bba4d.png)
converting it to a 4-1 mux, it doesn't gives me 2 selectors as I ordered it to:
![image](https://user-images.githubusercontent.com/2004337/149855271-a5ecfe71-ef4b-4d27-a148-d1302c31a721.png)
![image](https://user-images.githubusercontent.com/2004337/149855289-9513e524-3410-4a83-beeb-f44836348a28.png)
Also I experience other bugs as this one:
![image](https://user-images.githubusercontent.com/2004337/149855730-49077671-c306-45bf-a6b0-3845e329a525.png)
Win10-64bit.

**Comment by hneemann** [comment]
Seems to be a missunderstanding, see also #378
