### ISSUE TITLE
LED matrix "avoid flicker" issue

### ISSUE THREAD

**Issue by hoggardb** [hneemann/Digital#898]
There seems to be an issue regarding the "avoid flicker" option in the LED matrix.  The file shown below represents a simple security monitoring system.  As expected, the LEDs in the circuit experience flickering when a "door or window" is open.  I was experimenting with the LED matrix to see if the avoid flicker option would eliminate this.

In the example shown here, with the clock set to max frequency, and with the "door 1" input having a HIGH value, I set the LED matrix C input to 0.  This caused the 1st LED on the first row to flicker rapidly (when I though the avoid flicker option would make it stay on).  Then I changed the C input to 1.  After doing so, the first LED turned off (as expected), and the 2nd LED started flickering.  After changing the C input to 2, the second LED remained on (I expected it to turn off) and the 3rd LED started flickering.  In the screenshot below, I changed the C input to 3, and the third LED remained on (I expected it to turn off), and the 4th LED started flickering.

I don't see where the avoid flicker option is actually stopping the flickering, and furthermore, it seems to make the chosen LED stay in whatever state it happens to be in at the time that the column address changes.

![image](https://user-images.githubusercontent.com/38236592/150859763-f291b908-b6bd-4d80-b762-1f118fda47f1.png)
[test.zip](https://github.com/hneemann/Digital/files/7928728/test.zip)

**Comment by hneemann** [comment]
The option "avoid flicker" switches on and off in the LED display memory. If the option is not set, the display works as if there is no memory. So it's like a simple LED display that only lights the column that is currently selected. All other LEDs are dark.
If the option is on, the display remembers the state of the currently not activated columns and controls the LEDs accordingly.
