### ISSUE TITLE
text in data editor too small on linux with a 4k display

### ISSUE THREAD

**Issue by keithr-git** [hneemann/Digital#929]
When I edit the contents of a ROM, the lines for hex numbers are drawn very small, squished together in a way that makes it impossible to read what they contain.

I'm running linux, and have a 4K display. Let me know if you need more system details.

Here's a screenshot:

![screenshot](https://user-images.githubusercontent.com/1937326/155441269-aaab60f6-9620-4ad0-8548-69bf2248a270.png)

**Comment by hneemann** [comment]
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/).

**Comment by keithr-git** [comment]
Perfect! Thank you!
