### ISSUE TITLE
Using ASM with Digital and the display 

### ISSUE THREAD

**Issue by SirClickALot** [hneemann/Digital#963]
Hi,

I am using the excellent accompanying assembler to help me get across the idea of basic assembly language programming to a school level student. 

I see that ASM talks nicely to Digital when using one or more of the Example circuits: 

1. Processor. dig
2. ProcessorIntr.dig
3. ProcessorVonNeumann.dig

My questionas are:

1. When the example programs output to the TERMINAL, what's the easiest way to show that output on the screen?
2. How do I go about displaying the contents of the ``Graphics RAM`` when using the ``Processor. dig``
3. How do I go about displaying the contents of the ``LEDMatrix`` when using the  ``ProcessorVonNeumann.dig``

I would be very grateful for a tad more guidance if anyone has the time to spare to help out.

Many thanks

**Comment by hneemann** [comment]
You have to connect the required hardware to the processor. After that the content written to it shows up automatically.

The easiest way to use the terminal is to start with `Processor.dig` replace the GraphicRAM with the Terminal (Custom->IO->Terminal) and write some characters to the io port 0x0f.
