### ISSUE TITLE
"Probe" components do not connect on line

### ISSUE THREAD

**Issue by FilipSzkandera** [hneemann/Digital#969]
<img width="644" alt="Screenshot 2022-06-21 at 13 46 08" src="https://user-images.githubusercontent.com/61631453/174791746-5aeed8c5-6fe0-44d4-a690-048b936b1629.png">

This is just a small inconvenience, but in would be really neat and minimalistic in larger designs if this would work.

**Comment by xotmatrix** [comment]
See: #486
