### ISSUE TITLE
Feature Request: Option for register asynchronous clear

### ISSUE THREAD

**Issue by davidsummers** [hneemann/Digital#97]
The Register component doesn't currently have a way to asynchronously clear the value.

Could that be implemented?

I'm working on a Program Counter and it would be very nice to be able to have a Reset signal clear the Program Counter to 0 no matter what the state of the Clock signal is.

A Clear, either as an option or always there would be very helpful.

Thanks for a great program.

**Comment by hneemann** [comment]
Do you need an enable input? If not then you can use a D-FF with asynchronous clear. D-FFs are also able to store more than one bit.

**Comment by davidsummers** [comment]
Good point, I hadn't investigated all the components thoroughly.

I can do this by using a D-FF and just adding an AND GATE on the clock input.

Thanks, I'll use that instead for now.

**Comment by hneemann** [comment]
It's not a good idea to use a clock signal which has passed a logic gate. It's better to use a muxer in front of the D-FF and simply store the value which is already stored if not enabled.

**Comment by hneemann** [comment]
Here is an example of two identical state machines (a 3-bit counter). The only difference is, that the right one has a delay in the clock signal of one of the flip-flops.

![delay](https://user-images.githubusercontent.com/7190563/34638606-354096e8-f2cf-11e7-9c7d-b25c36ffe0f5.gif)

**Comment by davidsummers** [comment]
Wow, I hadn't seen that behaviour yet but I'm sure I will as I do more.

Thanks for the expert advice.

Very interesting.
