### ISSUE TITLE
Digital.jar not found

### ISSUE THREAD

**Issue by jluke1** [hneemann/Digital#973]
"If there are any problems starting Digital on your system, please try to run Digital from a command line within the Digital folder:

java -jar Digital.jar"

There is no file Digital.jar anywhere in the Digital tree.
mvn install did create target/Digital.jar but gave an error
message "may be a directory"

macOS 10.15.7

John Luke

**Comment by hneemann** [comment]
There is no need to clone the repo or download the sources to build the jar yourself. 
Just download the latest release by clicking the "Download" button.

**Comment by jluke1** [comment]
Ah OK I just automatically cloned the repo. Did not notice the big green download button.
Maybe you should include Digital.jar in the repo to avoid confusion.

the target/Digital.jar did work though. Nice piece of software.

Thanks
John Luke
