### ISSUE TITLE
Control-Click issue in Macos solved

### ISSUE THREAD

**Issue by jongena** [hneemann/Digital#974]
version: v0.29
The issue with control-click in Macos (Monterey 12.4) is solved in two ways:
1. Use the bluetooth Magic Mouse
2. Use **two** fingers to click on the trackpad (while holding the control key); this is the standard setting 
in System Preferences. You can change it to one finger in the right or left bottom corner of the trackpad.

The remarkable thing is that Control-Click in most cases works also with one finger on the trackpad, but also with two fingers.
For some reason it works only with two fingers on the trackpad when running Digital.
I hope this is helpful to all interested !
Jef Ongena

**Comment by hneemann** [comment]
In the preferences it is possible to select the macOS ctrl-click behavior. 
Maybe you should try this out.
