### ISSUE TITLE
ROM 64-bit data bug?

### ISSUE THREAD

**Issue by davidsummers** [hneemann/Digital#98]
I have been using 64-bit data ROM for the last several days but I hadn't tried this.

I tried putting a number 0x8000000000000000 or over and it just shows a red box and doesn't let me complete the dialog.

I put in 0x7fffffffffffffff and it worked fine.

I'm guessing this is a small bug related to JAVA long?

Hopefully a quick fix?

Thanks for a great program.

**Comment by hneemann** [comment]
That was a unexpectedly big deal. :-)
Please try the latest [pre-release](https://infdigital.dhbw-mosbach.de/).

**Comment by davidsummers** [comment]
Confirmed fixed.

Thanks!
